Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-09, with the labels that each got.

#846 Fix virustotal vis
  server/integration-files/visualizations/overview/overview-virustotal.js
Labels: bugfix

#849 Fixed agents coverage percentage when there are no agents
  public/controllers/management/status.js
  server/controllers/wazuh-api.js
Labels: bugfix

#850 Added new syscheck configuration items
  public/templates/agents/agents-configuration.html
  public/templates/management/configuration.html
Labels: [app] enhancement, [app] interface, [release] 3.6, [wazuh] core

#852 Implemented Refresh function for Settings/Logs tab
  public/controllers/settings/index.js
  public/templates/settings/settings-logs.html
  public/templates/settings/settings.head
Labels: [app] enhancement, [app] frontend, [app] interface

#859 Code quality(eslint, mocha, tslint)
  .eslintrc.json
  .tslint.yml
  index.js
  init.js
  package.json
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/management/logs.js
  public/controllers/management/monitoring.js
  public/controllers/management/status.js
  public/controllers/overview/index.js
  public/directives/wz-dynamic/wz-dynamic.js
  public/directives/wz-table/wz-table.js
  public/kibana-integrations/kibana-discover.js
  public/kibana-integrations/kibana-visualization.js
  public/kibana-integrations/saved-object-loader.js
  public/kibana-integrations/saved-objects.js
  public/services/file-saver.js
  public/services/region-maps.js
  public/utils/base64.js
  public/utils/filter-handler.js
  public/utils/generate-metric.js
  server/controllers/error-response.js
  server/controllers/index.js
  server/controllers/wazuh-api-elastic.js
  server/controllers/wazuh-api.js
  server/controllers/wazuh-elastic.js
  server/controllers/wazuh-reporting.js
  server/initialize.js
  server/integration-files/visualizations/agents/agents-pci.js
  server/integration-files/visualizations/cluster/monitoring.js
  server/integration-files/visualizations/overview/overview-general.js
  server/lib/elastic-wrapper.js
  server/lib/get-configuration.js
  server/lib/parse-cron.js
  server/logger.js
  server/monitoring.js
  server/reporting/audit-request.js
  server/reporting/gdpr-request.js
  server/reporting/overview-request.js
  server/reporting/pci-request.js
  server/reporting/rootcheck-request.js
  server/reporting/syscheck-request.js
  server/reporting/vulnerability-request.js
  server/routes/wazuh-api-elastic.js
  server/routes/wazuh-api.js
  server/routes/wazuh-elastic.js
  server/routes/wazuh-reporting.js
  test/server/wazuh-api-elastic.js
  test/server/wazuh-api.js
  test/server/wazuh-elastic.js
  util/get-path.js
Labels: [app] enhancement

#872 Updated known fields for Kibana
  server/integration-files/known-fields.js
Labels: [elastic] kibana

#873 Redesign inventory tab
  public/controllers/agent/agents.js
  public/less/layout.less
  public/templates/agents/agents-syscollector.html
Labels: [app] enhancement

#879 Fix syscollector behaviour
  public/templates/agents/agents-syscollector.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
Labels: bugfix

#880 [3.6.1_6.4.0-410] Bump revision and update CHANGELOG.md
  CHANGELOG.md
  README.md
  package.json
Labels: release

#897 Update changelog and bump revision 411
  CHANGELOG.md
  package.json
Labels: release

#912 Fix filterpill align
  public/less/layout.less
  public/templates/kibana-template/kibana-filterbar-template.html
Labels: bugfix
