Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-11, with the labels that each got.

#1012 Fixed broken report list pagination
  package.json
  public/controllers/misc/reporting.js
  public/templates/management/reporting.html
Labels: bugfix

#1019 Admin mode for the Wazuh API requests
  config.yml
  public/services/resolves/get-config.js
  server/controllers/wazuh-api.js
Labels: enhancement

#1033 Increased the number of rows in syscollector packages/processes tables
  public/templates/agents/agents-syscollector.html
Labels: enhancement, wazuh 3.7

#1037 New Feedbacks and improvements in configuration sections
  public/controllers/agent/agents.js
  public/controllers/management/configuration.js
  public/less/common.less
  public/services/app-state.js
  public/templates/agents/agents.head
  public/templates/management/configuration/client/client.html
  public/templates/management/configuration/configuration.head
  public/templates/management/configuration/welcome.html
Labels: bug, enhancement, wazuh 3.7

#1030 Dev-tools new feature autocomplete
  public/controllers/dev-tools/dev-tools.js
  public/utils/codemirror/index.js
  public/utils/codemirror/show-hint.css
  public/utils/codemirror/show-hint.js
  server/controllers/wazuh-api.js
  server/routes/wazuh-api.js
  util/api-request-list.js
  util/excluded-devtools-autocomplete-keys.js
Labels: enhancement, wazuh 3.7

#982 New directive wz-config-viewer
  public/directives/index.js
  public/directives/wz-config-viewer/wz-config-viewer.html
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/templates/management/configuration/active-response/active-response.html
  public/templates/management/configuration/active-response/agents-active-response.html
  public/templates/management/configuration/active-response/commands.html
  public/templates/management/configuration/agentless/agentless.html
  public/templates/management/configuration/alerts/email-alerts.html
  public/templates/management/configuration/alerts/general-alerts.html
  public/templates/management/configuration/alerts/labels.html
  public/templates/management/configuration/alerts/reports.html
  public/templates/management/configuration/alerts/syslog.html
  public/templates/management/configuration/amazon-s3/amazon-s3.foot
  public/templates/management/configuration/cis-cat/cis-cat.foot
  public/templates/management/configuration/client-buffer/client-buffer.html
  public/templates/management/configuration/client/client.html
  public/templates/management/configuration/cluster/cluster.html
  public/templates/management/configuration/database-output/database-output.html
  public/templates/management/configuration/global-configuration/global.html
  public/templates/management/configuration/global-configuration/remote.html
  public/templates/management/configuration/integrations/integrations.html
  public/templates/management/configuration/integrity-monitoring/integrity-monitoring.foot
  public/templates/management/configuration/inventory/inventory.html
  public/templates/management/configuration/log-collection/localfile.html
  public/templates/management/configuration/log-collection/socket.html
  public/templates/management/configuration/open-scap/open-scap.foot
  public/templates/management/configuration/osquery/osquery.html
  public/templates/management/configuration/policy-monitoring/policy-monitoring.foot
  public/templates/management/configuration/registration-service/registration-service.html
  public/templates/management/configuration/ruleset/ruleset.foot
  public/templates/management/configuration/vulnerabilities/vulnerabilities.foot
  public/templates/management/configuration/wazuh-commands/wazuh-commands.html
Labels: enhancement

#1032 New table for syscheck agent files
  public/controllers/agent/agents.js
  public/directives/wz-table/lib/listeners.js
  public/templates/agents/agents-fim.html
  public/templates/agents/agents.head
  util/csv-key-equivalence.js
Labels: enhancement
