Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-12, with the labels that each got.

#1054 Updated AWS geolocation
  server/integration-files/known-fields.js
  server/integration-files/visualizations/overview/overview-aws.js
  server/lib/elastic-wrapper.js
Labels: enhancement

#1056 Added /elastic/alerts route
  server/controllers/wazuh-elastic.js
  server/routes/wazuh-elastic.js
  test/server/wazuh-elastic.js
Labels: backend

#1057 AWS rework
  public/controllers/overview/overview.js
  public/templates/overview/overview-aws.html
  public/templates/overview/overview.head
  server/controllers/wazuh-elastic.js
  server/integration-files/visualizations/overview/overview-aws.js
Labels: enhancement

#1059 Improved syscollector tables
  public/directives/wz-table/lib/parse-value.js
  public/templates/agents/agents-syscollector.html
  util/csv-key-equivalence.js
  util/process-state-equivalence.js
Labels: enhancement

#1058 New tags and filters search bar
  public/controllers/agent/agents-preview.js
  public/directives/index.js
  public/directives/wz-table/lib/data.js
  public/directives/wz-table/lib/listeners.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-tag-filter/wz-tag-filter.html
  public/directives/wz-tag-filter/wz-tag-filter.js
  public/directives/wz-tag-filter/wz-tag-filter.less
  public/templates/agents-prev/agents-prev.html
Labels: enhancement

#1067 New directive for tables with data as parameter
  public/directives/index.js
  public/directives/wz-data-table/index.js
  public/directives/wz-data-table/wz-data-table-directive.js
  public/directives/wz-data-table/wz-data-table.html
Labels: enhancement

#1074 Wazuh logo adapted to low resolutions
  public/directives/wz-menu/wz-menu.html
  public/img/new_logo_white_wolf.png
  public/less/common.less
Labels: enhancement

#1076 Bug fixes
  public/controllers/agent/agents.js
  public/img/icons/osquery.png
  public/img/icons/osquery.svg
  public/less/common.less
  public/templates/agents/agents-welcome.html
  public/templates/management/configuration/log-collection/localfile.html
  public/templates/overview/overview-welcome.html
  public/utils/config-handler.js
Labels: bug

#1081 Fix updateWazuhIndexDocument method
  server/controllers/wazuh-api-elastic.js
  server/controllers/wazuh-api.js
  server/controllers/wazuh-elastic.js
  server/initialize.js
  server/lib/elastic-wrapper.js
  server/routes/wazuh-api-elastic.js
Labels: backend

#1082 Code quality review
  .eslintrc.json
  package.json
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/dev-tools/dev-tools.js
  public/controllers/management/configuration.js
  public/controllers/management/decoders.js
  public/controllers/management/groups.js
  public/controllers/management/logs.js
  public/controllers/management/management.js
  public/controllers/management/monitoring.js
  public/controllers/management/rules.js
  public/controllers/management/status.js
  public/controllers/misc/blank-screen-controller.js
  public/controllers/misc/health-check.js
  public/controllers/misc/reporting.js
  public/controllers/overview/overview.js
  public/controllers/settings/settings.js
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/directives/wz-data-table/wz-data-table-directive.js
  public/directives/wz-menu/wz-menu.js
  public/directives/wz-table/lib/click-action.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-tag-filter/wz-tag-filter.js
  public/factories/discover-pending-updates.js
  public/factories/loaded-visualizations.js
  public/factories/misc.js
  public/factories/raw-visualizations.js
  public/factories/share-agent.js
  public/factories/tab-visualizations.js
  public/factories/vis-handlers.js
  public/factories/vis2png.js
  public/factories/wazuh-config.js
  public/services/api-request.js
  public/services/api-tester.js
  public/services/app-state.js
  public/services/common-data.js
  public/services/data-factory.js
  public/services/generic-request.js
  public/services/pattern-handler.js
  public/services/vis-factory-handler.js
  server/controllers/error-response.js
  server/controllers/wazuh-api-elastic.js
  server/controllers/wazuh-api.js
  server/controllers/wazuh-elastic.js
  server/controllers/wazuh-reporting.js
  server/controllers/wazuh-utils.js
  util/get-path.js
Labels: enhancement

#1088 Fix typo new filters bar
  public/directives/wz-tag-filter/wz-tag-filter.js
Labels: bug

#1089 Fix typo autocomplete also
  public/directives/wz-tag-filter/wz-tag-filter.js
Labels: bug

#1097 Fix typo tags filter bar
  public/directives/wz-tag-filter/wz-tag-filter.js
Labels: bug

#1102 Some UI improvements and bug fixes
  CHANGELOG.md
  public/controllers/dev-tools/dev-tools.js
  public/less/common.less
  public/services/reporting.js
  public/templates/agents-prev/agents-prev.html
  public/templates/dev-tools/dev-tools.html
  public/templates/management/groups/groups.html
  public/templates/management/monitoring/configuration.html
  public/templates/management/monitoring/nodes-detail.html
  public/templates/management/monitoring/nodes-list.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/rules/rules-detail.html
Labels: bug, enhancement

#1113 Reduced shards and replicas for common app indices
  config.yml
  public/services/resolves/get-config.js
  server/initialize.js
  server/lib/replicas-shards-helper.js
  server/monitoring.js
Labels: enhancement

#1111 Add netaddr table for inventory
  public/controllers/agent/agents.js
  public/templates/agents/agents-syscollector.html
  util/csv-key-equivalence.js
Labels: enhancement

#1105 Edit config.yml file from the app
  CHANGELOG.md
  public/controllers/agent/agents.js
  public/controllers/settings/settings.js
  public/directives/wz-menu/wz-menu.js
  public/less/common.less
  public/less/layout.less
  public/templates/settings/settings-configuration.html
  server/controllers/wazuh-api.js
  server/controllers/wazuh-utils.js
  server/lib/update-configuration.js
  server/routes/wazuh-utils.js
  util/api-request-list.js
Labels: enhancement
