Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-03, with the labels that each got.

#282 Minor adjustment to new metrics
  public/less/main.less
  public/templates/agents/agents-audit.html
  public/templates/agents/agents-general.html
  public/templates/agents/agents-vuls.html
  public/templates/overview/overview-audit.html
  public/templates/overview/overview-fim.html
  public/templates/overview/overview-general.html
  public/templates/overview/overview-vuls.html
Labels: enhancement, visualization

#283 Hotfix to current visualization directive
  public/kibana-integrations/kibana-visualization.js
Labels: bug, visualization

#293 Prevents accesing undefined array position
  public/kibana-integrations/kibana-visualization.js
Labels: bug, kibana, visualization

#295 Groups redesign
  public/directives/wz-search-bar/wz-search-bar.html
  public/directives/wz-table-header/wz-table-header.html
  public/directives/wz-table/wz-table.html
  public/less/agents.less
  public/less/angular-md.less
  public/less/common.less
  public/less/manager.less
  public/less/ruleset.less
  public/less/tables.less
  public/templates/agents-prev/agents-prev.html
  public/templates/manager/groups/groups-preview.html
  public/templates/manager/manager-osseclog.html
Labels: css, enhancement

#296 Query filter patch
  public/controllers/agents.js
  public/kibana-integrations/kibana-discover.js
  public/templates/agents/agents.head
Labels: bug, kibana, visualization

#299 Minor redesign on agents tab
  public/templates/agents-prev/agents-prev.html
Labels: enhancement

#306 Dev metrics
  public/controllers/agents.js
  public/controllers/overview.js
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-virustotal.html
  public/templates/manager/ruleset/ruleset-decoders.html
  public/templates/manager/ruleset/ruleset-rules.html
  public/templates/overview/overview-aws.html
  public/templates/overview/overview-virustotal.html
Labels: enhancement

#308 Better checks
  public/controllers/blank-screen-controller.js
  public/services/api-tester.js
  public/services/app-state.js
  public/services/routes.js
  public/templates/error-handler/blank-screen.html
  server/api/wazuh-elastic.js
  server/initialize.js
Labels: elasticsearch, enhancement, kibana

#311 Fix API version check, dismissing patch number
  public/controllers/health-check.js
Labels: api, bugfix, enhancement

#314 Fix tables scroll moz
  public/directives/wz-table/wz-table.less
  public/templates/agents-prev/agents-prev.head
  public/templates/manager/groups/groups.head
  public/templates/manager/manager-osseclog.html
  public/templates/manager/ruleset/ruleset.head
Labels: enhancement, firefox

#315 Finished Agent configuration tabs and several HTML/CSS adjustments
  public/controllers/agents.js
  public/controllers/manager.js
  public/directives/wz-menu/wz-menu.html
  public/directives/wz-menu/wz-menu.less
  public/directives/wz-search-bar/wz-search-bar.html
  public/directives/wz-table/wz-table.html
  public/less/cleaned.less
  public/less/common.less
  public/less/height.less
  public/less/layout.less
  public/less/loader.js
  public/less/media-queries.less
  public/less/typography.less
  public/templates/agents-prev/agents-prev.head
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-configuration.html
  public/templates/agents/agents-pci.html
  public/templates/agents/agents.head
  public/templates/error-handler/blank-screen.html
  public/templates/health-check/health-check.html
  public/templates/manager/groups/groups-preview.html
  public/templates/manager/manager-configuration.html
  public/templates/manager/manager-osseclog.html
  public/templates/manager/manager-status.html
  public/templates/manager/manager.head
  public/templates/manager/ruleset/ruleset-decoders.html
  public/templates/manager/ruleset/ruleset-rules.html
  public/templates/manager/ruleset/ruleset.head
  public/templates/overview/overview-pci.html
  public/templates/overview/overview.head
  public/templates/settings/settings.html
Labels: css, enhancement, html

#316 Properly destroying visualizations
  public/controllers/agents.js
  public/controllers/overview.js
  public/kibana-integrations/kibana-visualization.js
  public/templates/overview/overview-fim.html
Labels: bug, elasticsearch, visualization

#340 Added errorHandler service to Datahandler factory
  public/services/data-handler.js
Labels: api, enhancement, frontend

#342 Fixed multiple agent.id issue
  public/controllers/agents.js
Labels: bug, kibana
