Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-10, with the labels that each got.

#925 Changed Overview/Agents OpenSCAP visualization titles
  public/templates/agents/agents-oscap.html
  public/templates/overview/overview-oscap.html
Labels: [app] enhancement

#937 Fix if condition
  public/controllers/agent/agents.js
Labels: bugfix

#939 Added support to open Discover or Configuration tabs from agents table
  public/controllers/agent/agents.js
  public/directives/wz-table/wz-table.html
  public/directives/wz-table/wz-table.js
  public/factories/share-agent.js
  public/less/common.less
Labels: [app] enhancement, [app] frontend, [app] interface

#940 Added is_sync API call
  public/controllers/agent/agents.js
  public/templates/management/configuration/welcome.html
Labels: [app] enhancement

#943 Update CHANGELOG.md and README.md
  CHANGELOG.md
  README.md
Labels: [release] 3.7, release

#944 Several 3.7-6.4 testing bugfixes
  public/controllers/agent/agents.js
  public/controllers/overview/index.js
  public/controllers/settings/index.js
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
  public/templates/overview/overview-welcome.html
  public/templates/overview/overview.head
  public/templates/settings/settings-about.html
  public/templates/settings/settings-first-use.html
  public/templates/settings/settings-logs.html
Labels: bugfix

#945 Several Groups tab bugfixes
  public/templates/management/groups/groups.html
  util/csv-key-equivalence.js
Labels: [app] interface, bugfix

#948 More app bugfixes
  public/directives/wz-table/wz-table.js
  public/templates/management/configuration/active-response/active-response.head
Labels: bugfix

#956 Update CHANGELOG.md
  CHANGELOG.md
Labels: release, wazuh 3.7

#957 Fix wrong condition
  public/kibana-integrations/kibana-visualization.js
Labels: bugfix

#961 Dynamic known fields for wazuh-monitoring. Fix manager field
  server/controllers/wazuh-reporting.js
  server/integration-files/monitoring-known-fields.js
  server/lib/elastic-wrapper.js
  server/monitoring.js
  util/csv-key-equivalence.js
Labels: bugfix

#966 Fix grammar
  public/templates/management/configuration/active-response/active-response.head
  public/templates/management/configuration/active-response/commands.html
  public/templates/management/configuration/agentless/agentless.html
  public/templates/management/configuration/alerts/email-alerts.html
  public/templates/management/configuration/alerts/general-alerts.html
  public/templates/management/configuration/cis-cat/cis-cat.head
  public/templates/management/configuration/cis-cat/ciscat-benchmarks.html
  public/templates/management/configuration/cis-cat/ciscat-general.html
  public/templates/management/configuration/client-buffer/client-buffer.html
  public/templates/management/configuration/client/client.html
  public/templates/management/configuration/global-configuration/global-configuration.head
  public/templates/management/configuration/global-configuration/global.html
  public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
  public/templates/management/configuration/log-collection/localfile.html
  public/templates/management/configuration/osquery/osquery.html
  public/templates/management/configuration/policy-monitoring/pm-unix.html
  public/templates/management/configuration/welcome.html
  public/utils/tab-names.js
Labels: enhancement

#971 3.7 several fixes
  public/controllers/management/monitoring.js
  public/controllers/misc/health-check.js
  public/controllers/settings/index.js
  public/directives/wz-table/lib/click-action.js
  public/directives/wz-table/lib/pagination.js
  public/services/resolves/settings-wizard.js
  public/services/routes.js
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/settings/settings-pattern.html
  server/controllers/wazuh-api.js
  server/integration-files/visualizations/overview/overview-aws.js
Labels: enhancement

#972 Update CHANGELOG.md
  CHANGELOG.md
Labels: release, wazuh 3.7

#974 Fix race condition with the Wazuh filters
  public/kibana-integrations/kibana-discover.js
  public/templates/agents/agents.head
Labels: bugfix

#976 Node selector for Management > Status
  public/controllers/management/status.js
  public/templates/management/status.html
Labels: enhancement

#979 Aborted request wz-table
  CHANGELOG.md
  public/directives/wz-table/lib/data.js
  public/directives/wz-table/lib/init.js
  public/directives/wz-table/lib/pagination.js
  public/directives/wz-table/lib/sort.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
Labels: enhancement

#981 Refactor Promise.all output
  public/controllers/agent/agents.js
  public/controllers/management/monitoring.js
  public/controllers/management/status.js
  public/controllers/overview/index.js
  server/controllers/wazuh-api.js
Labels: enhancement

#980 Node selector for Management > Logs
  CHANGELOG.md
  public/controllers/management/logs.js
  public/less/layout.less
  public/templates/management/logs.html
Labels: enhancement

#985 API calls improved
  package.json
  public/controllers/agent/agents.js
  public/controllers/management/status.js
  public/directives/wz-menu/wz-menu.js
  public/templates/management/status.html
  server/lib/elastic-wrapper.js
Labels: bugfix, enhancement

#995 Added group selector for the agent list
  CHANGELOG.md
  package.json
  public/controllers/agent/agents-preview.js
  public/templates/agents-prev/agents-prev.html
  server/controllers/wazuh-api.js
Labels: enhancement

#998 Retro-fix updateWazuhIndexDocument for X-Pack
  package.json
  server/lib/elastic-wrapper.js
Labels: bugfix

#997 More optimizations
  package.json
  public/controllers/overview/index.js
  public/services/pattern-handler.js
  public/services/resolves/get-ip.js
  server/controllers/wazuh-elastic.js
Labels: enhancement

#1000 More improvements
  CHANGELOG.md
  package.json
  public/controllers/management/status.js
  public/templates/management/monitoring/disabled.html
  public/templates/management/monitoring/monitoring.head
  public/templates/management/monitoring/monitoring.jade
Labels: bugfix

#1001 Replace not so clear expressions, fix some grammar typos
  package.json
  public/directives/wz-no-config/wz-no-config.html
  public/directives/wz-table/lib/parse-value.js
  public/templates/agents/agents.head
  public/templates/management/configuration/agentless/agentless.html
  public/templates/management/configuration/alerts/alerts.head
  public/templates/management/configuration/alerts/labels.html
  public/templates/management/configuration/alerts/reports.html
  public/templates/management/configuration/alerts/syslog.html
  public/templates/management/configuration/amazon-s3/amazon-buckets.html
  public/templates/management/configuration/amazon-s3/amazon-general.html
  public/templates/management/configuration/amazon-s3/amazon-s3.head
  public/templates/management/configuration/client-buffer/client-buffer.html
  public/templates/management/configuration/client/client.html
  public/templates/management/configuration/cluster/cluster.html
  public/templates/management/configuration/configuration.head
  public/templates/management/configuration/database-output/database-output.html
  public/templates/management/configuration/global-configuration/global-configuration.head
  public/templates/management/configuration/global-configuration/global.html
  public/templates/management/configuration/global-configuration/remote.html
  public/templates/management/configuration/integrations/integrations.html
  public/templates/management/configuration/integrity-monitoring/fim-general.html
  public/templates/management/configuration/inventory/inventory.html
  public/templates/management/configuration/log-collection/localfile.html
  public/templates/management/configuration/log-collection/socket.html
  public/templates/management/configuration/open-scap/openscap-evaluations.html
  public/templates/management/configuration/policy-monitoring/policy-monitoring.head
  public/templates/management/configuration/registration-service/registration-service.html
  public/templates/management/configuration/vulnerabilities/vulnerabilities-feeds.html
  public/templates/management/configuration/vulnerabilities/vulnerabilities.head
  public/templates/management/configuration/wazuh-commands/wazuh-commands.html
  public/templates/management/configuration/welcome.html
  public/templates/management/management.head
  public/templates/management/monitoring/monitoring.head
  public/templates/overview/overview-welcome.html
  public/templates/overview/overview.head
  public/templates/settings/settings.head
  server/controllers/wazuh-reporting.js
  server/reporting/generic-table.js
Labels: enhancement

#1005 Fix safari redirect issue when using surrounding documents feature
  package.json
  public/services/routes.js
Labels: bugfix
