Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-08, with the labels that each got.

#758 Fix specific node vis (cluster.node missing)
  public/kibana-integrations/kibana-visualization.js
Labels: bugfix

#760 [ Dev tools ] Removed unused deps. Better error handling
  public/controllers/dev-tools.js
Labels: [app] enhancement

#763 Added missing who data field
  server/integration-files/known-fields.js
Labels: [app] enhancement

#766 Refactor agents autocomplete. Deprecated old data handler
  public/app.js
  public/controllers/agents.js
  public/factories/data-handler-composer.js
  public/services/data-factory.js
  public/services/data-handler.js
  public/services/index.js
  public/templates/agents/agents.head
  public/utils/codemirror/index.js
  public/utils/when-scrolled/when-scrolled.js
Labels: bugfix

#768 Optimizations
  package.json
  public/controllers/agents.js
  public/controllers/dev-tools.js
  public/controllers/groups.js
  public/controllers/manager.js
  public/controllers/osseclog.js
  public/controllers/reporting.js
  public/controllers/ruleset.js
  public/controllers/settings.js
  public/directives/wz-welcome-card/wz-welcome-card.js
  public/factories/vis2png.js
  public/img/icon.svg
  public/img/icon_blue.png
  public/img/logo_blue.png
  public/img/logo_white.png
  public/kibana-integrations/kibana-discover.js
  public/services/resolves/check-timestamp.js
  public/services/resolves/get-ip.js
  public/services/resolves/go-to-kibana.js
  public/services/resolves/settings-wizard.js
  public/services/routes.js
  public/templates/manager/groups/groups-preview.html
  public/templates/manager/groups/groups.head
  public/templates/manager/groups/groups.html
  public/templates/manager/groups/groups.jade
  public/templates/manager/manager.jade
Labels: [app] enhancement

#752 [ 3.5.x >= ] Adapt Wazuh 3.5
  public/controllers/agents.js
  server/integration-files/known-fields.js
Labels: [app] enhancement

#753 [ 3.5.x >= ] New syscollector table. New log levels. Multi search enabled for wz-table
  package.json
  public/controllers/agents.js
  public/directives/wz-table/wz-table.js
  public/templates/agents/agents-syscollector.html
  public/templates/manager/manager-osseclog.html
  util/csv-key-equivalence.js
Labels: [app] enhancement

#782 [3.5-6.3] Fixed Decoders detail view when only parents filter enabled
  public/directives/wz-table/wz-table.js
Labels: [app] frontend, bugfix

#790 [3.5-6.3] Fix error when first line is a comment or empty
  public/controllers/dev-tools.js
Labels: bugfix

#791 [3.5-6.3] Fix api double message + fix previous location
  public/services/resolves/settings-wizard.js
  public/services/routes.js
Labels: bugfix

#792 Auto-resize tables depending on screen height
  public/directives/wz-table/wz-table-rows.js
  public/directives/wz-table/wz-table.js
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-syscollector.html
  public/templates/manager/groups/groups.html
  public/templates/manager/manager-osseclog.html
  public/templates/manager/monitoring/nodes-list.html
  public/templates/manager/ruleset/decoders/decoders-detail.html
  public/templates/manager/ruleset/decoders/decoders-list.html
  public/templates/manager/ruleset/rules/rules-detail.html
  public/templates/manager/ruleset/rules/rules-list.html
Labels: [app] enhancement

#795 Updating API ID
  public/controllers/health-check.js
  public/services/resolves/settings-wizard.js
  server/controllers/wazuh-api.js
Labels: bugfix

#799 Updated CHANGELOG and package.json for next app release
  CHANGELOG.md
  README.md
  package.json
Labels: release

#808 Several UI changes to make the app compatible with Internet Explorer 11
  public/directives/wz-welcome-card/wz-welcome-card.html
  public/templates/agents-prev/agents-prev.head
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-audit.html
  public/templates/agents/agents-ciscat.html
  public/templates/agents/agents-configuration.html
  public/templates/agents/agents-fim.html
  public/templates/agents/agents-gdpr.html
  public/templates/agents/agents-general.html
  public/templates/agents/agents-oscap.html
  public/templates/agents/agents-pci.html
  public/templates/agents/agents-pm.html
  public/templates/agents/agents-syscollector.html
  public/templates/agents/agents-virustotal.html
  public/templates/agents/agents-vuls.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
  public/templates/dev-tools/dev-tools.html
  public/templates/discover/discover.head
  public/templates/error-handler/blank-screen.html
  public/templates/health-check/health-check.html
  public/templates/management/configuration.html
  public/templates/management/logs.html
  public/templates/management/management.head
  public/templates/management/monitoring/monitoring.head
  public/templates/management/monitoring/nodes-detail.html
  public/templates/management/monitoring/nodes-list.html
  public/templates/management/reporting.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/management/ruleset/ruleset.head
  public/templates/management/status.html
  public/templates/management/welcome.html
  public/templates/overview/overview-audit.html
  public/templates/overview/overview-aws.html
  public/templates/overview/overview-ciscat.html
  public/templates/overview/overview-fim.html
  public/templates/overview/overview-gdpr.html
  public/templates/overview/overview-general.html
  public/templates/overview/overview-oscap.html
  public/templates/overview/overview-pci.html
  public/templates/overview/overview-pm.html
  public/templates/overview/overview-virustotal.html
  public/templates/overview/overview-vuls.html
  public/templates/overview/overview-welcome.html
  public/templates/overview/overview.head
  public/templates/settings/settings-about.html
  public/templates/settings/settings-api.html
  public/templates/settings/settings-extensions.html
  public/templates/settings/settings-pattern.html
  public/templates/settings/settings.head
Labels: [app] html, [app] interface, [browser] explorer, bugfix

#811 Ignore monitoring vis
  public/factories/vis-handlers.js
Labels: [app] enhancement

#812 Added logs in critical catch statements
  server/controllers/wazuh-api-elastic.js
  server/controllers/wazuh-api.js
  server/controllers/wazuh-elastic.js
Labels: [app] enhancement

#817 Hot replicas modifying
  server/initialize.js
  server/lib/elastic-wrapper.js
  server/lib/replicas-shards-helper.js
  server/monitoring.js
Labels: [app] enhancement

#838 Replace "View Discover" and "View panel" buttons
  public/templates/agents/agents.head
  public/templates/overview/overview.head
Labels: [app] enhancement, [app] html, [app] interface

#839 Update CHANGELOG, README and bump revision 405
  CHANGELOG.md
  README.md
  config.yml
  package.json
Labels: release
