Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-06, with the labels that each got.

#517 Manager consistency
  public/controllers/agents-preview.js
  public/controllers/manager.js
  public/templates/agents-prev/agents-prev.html
  public/templates/manager/manager-status.html
Labels: bugfix

#524 Parallel reporting but it's still on foreground mode
  public/controllers/overview.js
  public/factories/vis2png.js
Labels: enhancement

#531 Fix agents issue
  public/controllers/agents.js
Labels: bugfix

#533 Reduced vis tab checking to 2 elements
  public/controllers/agents.js
Labels: enhancement

#536 Fix reloading broken under configuration tab
  public/controllers/agents.js
Labels: bugfix

#537 Added filter by agent version to agents preview
  public/controllers/agents-preview.js
  public/templates/agents-prev/agents-prev.html
Labels: enhancement

#538 Added filter by node in agents preview
  public/controllers/agents-preview.js
  public/templates/agents-prev/agents-prev.html
Labels: enhancement

#542 Fix monitoring main function
  server/monitoring.js
Labels: bugfix

#543 Brand-new app UI redesign for Overview and Agents
  public/controllers/agents.js
  public/controllers/overview.js
  public/directives/wz-menu/wz-menu.html
  public/directives/wz-menu/wz-menu.less
  public/directives/wz-table/wz-table.less
  public/less/common.less
  public/less/layout.less
  public/less/typography.less
  public/services/resolves/settings-wizard.js
  public/templates/agents/agents-configuration.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.foot
  public/templates/agents/agents.head
  public/templates/agents/agents.jade
  public/templates/auth/login.html
  public/templates/error-handler/blank-screen.html
  public/templates/manager/manager-osseclog.html
  public/templates/manager/reporting/main.html
  public/templates/manager/ruleset/decoders/decoders-list.html
  public/templates/manager/ruleset/rules/rules-list.html
  public/templates/overview/overview-welcome.html
  public/templates/overview/overview.head
  public/templates/overview/overview.jade
  public/templates/settings/settings.html
Labels: 3.2, html, redesign, refactoring

#545 Not updating .wazuh when changing extensions
  public/controllers/agents.js
  public/controllers/overview.js
  public/controllers/settings.js
  public/services/app-state.js
  public/services/resolves/settings-wizard.js
  server/controllers/wazuh-api-elastic.js
  server/routes/wazuh-api-elastic.js
Labels: bugfix

#546 Checking if GDPR is available from the Wazuh API before parsign
  public/templates/overview/overview-gdpr.html
  server/controllers/wazuh-api.js
Labels: bugfix

#548 Fix agent changed condition
  public/controllers/agents.js
Labels: bugfix

#552 Fix OS platform selector
  public/controllers/agents-preview.js
  public/services/data-handler.js
  public/templates/agents-prev/agents-prev.html
Labels: bugfix

#556 Fix set default manager resets extensions
  public/controllers/settings.js
Labels: bugfix

#557 Bump app revision for 393 release
  package.json
Labels: 3.2, upgrade

#560 Added missing header
  server/controllers/wazuh-api.js
  server/initialize.js
Labels: bugfix

#563 Moved generated data to optimize directory
  server/controllers/wazuh-api.js
  server/logger.js
Labels: [app] enhancement

#566 Added package condition from vulnerability known fields
  server/integration-files/known-fields.js
Labels: bugfix

#575 Fix missing dependency
  public/directives/wz-menu/wz-menu.js
Labels: bugfix

#582 Paginated tables + new data factory + syscollector tab
  public/controllers/agents-preview.js
  public/controllers/agents.js
  public/controllers/groups.js
  public/controllers/monitoring.js
  public/controllers/osseclog.js
  public/controllers/ruleset.js
  public/directives/index.js
  public/directives/wazuh-table/controller.js
  public/directives/wazuh-table/key-equivalence.js
  public/directives/wazuh-table/template.html
  public/directives/wz-search-bar/wz-search-bar.html
  public/directives/wz-search-bar/wz-search-bar.js
  public/directives/wz-table-header/wz-table-header.html
  public/directives/wz-table-header/wz-table-header.js
  public/directives/wz-table-header/wz-table-header.less
  public/directives/wz-table/wz-table.html
  public/directives/wz-table/wz-table.js
  public/directives/wz-table/wz-table.less
  public/factories/data-handler-composer.js
  public/less/common.less
  public/less/height.less
  public/services/data-factory.js
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-syscollector.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
  public/templates/agents/agents.jade
  public/templates/manager/groups/groups-preview.html
  public/templates/manager/manager-osseclog.html
  public/templates/manager/ruleset/decoders/decoders-detail.html
  public/templates/manager/ruleset/decoders/decoders-list.html
  public/templates/manager/ruleset/rules/rules-detail.html
  public/templates/manager/ruleset/rules/rules-list.html
  public/utils/tab-names.js
Labels: [app] enhancement, bugfix

#591 Fix toggleExtension function
  public/controllers/settings.js
Labels: bugfix

#593 Added loading ring, no result box and no result counter
  public/directives/wazuh-table/template.html
Labels: [app] enhancement

#601 New extension - CIS-CAT alerts
  config.yml
  public/controllers/agents.js
  public/controllers/overview.js
  public/controllers/settings.js
  public/factories/tab-visualizations.js
  public/services/common-data.js
  public/services/resolves/settings-wizard.js
  public/templates/agents/agents-ciscat.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.jade
  public/templates/overview/overview-ciscat.html
  public/templates/overview/overview-welcome.html
  public/templates/overview/overview.jade
  public/templates/settings/settings-about.html
  public/templates/settings/settings-extensions.html
  public/templates/settings/settings-first-use.html
  public/utils/agents-metrics.js
  public/utils/overview-metrics.js
  public/utils/tab-names.js
  server/integration-files/known-fields.js
  server/integration-files/visualizations/agents/agents-ciscat.js
  server/integration-files/visualizations/agents/index.js
  server/integration-files/visualizations/overview/index.js
  server/integration-files/visualizations/overview/overview-ciscat.js
  server/lib/default-ext.js
  server/reporting/tab-description.js
Labels: [app] enhancement, [app] html, [elastic] visualizations, [release] 3.3

#605 Fix query-string version to avoid uglifyjs related error
  package.json
Labels: bugfix

#610 Fixed flex layout on Ruleset tabs
  public/templates/manager/ruleset/decoders/decoders-list.html
  public/templates/manager/ruleset/rules/rules-list.html
Labels: [app] frontend, [app] html, [app] interface, bugfix

#612 Added missing provider in load time
  public/app.js
Labels: bugfix

#624 Ignore pretty in dev tools query parser
  public/controllers/dev-tools.js
Labels: bugfix

#626 Fix visualization names on Agents/CIS-CAT template
  public/templates/agents/agents-ciscat.html
Labels: [app] frontend, [app] html, [elastic] visualizations, bugfix

#640 Resolve getIp before health check is fired
  public/services/routes.js
Labels: bugfix
