Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2018-05, with the labels that each got.

#428 Added message for successful API removal
  public/controllers/settings.js
Labels: 3.2, api, feature request, frontend

#429 Fix OSCAP visualization when showing long agent names
  server/integration-files/visualizations/overview/overview-oscap.js
Labels: 3.2, backend, bugfix, visualization

#431 CSV exporting
  package.json
  public/app.js
  public/controllers/agents-preview.js
  public/controllers/csv-generator.js
  public/controllers/groups.js
  public/controllers/osseclog.js
  public/controllers/ruleset.js
  public/services/csv-request.js
  public/services/error-handler.js
  public/templates/agents-prev/agents-prev.html
  public/templates/manager/groups/groups-preview.html
  public/templates/manager/manager-osseclog.html
  public/templates/manager/ruleset/decoders/decoders-list.html
  public/templates/manager/ruleset/rules/rules-list.html
  server/controllers/wazuh-api.js
  server/routes/wazuh-api.js
Labels: 3.2, backend, enhancement, frontend

#442 Fix minor bugs
  public/services/data-handler.js
Labels: bugfix

#447 Fixed UI issue on Agents when using Safari web browser
  public/templates/agents-prev/agents-prev.foot
  public/templates/agents-prev/agents-prev.head
  public/templates/agents-prev/agents-prev.html
  public/templates/agents-prev/agents-prev.jade
  public/templates/manager/manager-status.html
  public/templates/manager/manager.head
  public/templates/manager/ruleset/ruleset.head
Labels: 3.2, bugfix, html, safari

#446 Improvements for Manager/Ruleset
  public/controllers/manager.js
  public/controllers/ruleset.js
  public/directives/wz-table-header/wz-table-header.less
  public/directives/wz-table/wz-table.js
  public/templates/manager/manager.head
  public/templates/manager/ruleset/decoders/decoders-detail.html
  public/templates/manager/ruleset/decoders/decoders-list.html
  public/templates/manager/ruleset/rules/rules-detail.html
  public/templates/manager/ruleset/rules/rules-list.html
  public/templates/manager/ruleset/ruleset.head
Labels: 3.2, bugfix, frontend, html

#459 Fix discover to panels preserve extra filters on filter-bar
  public/controllers/agents.js
  public/controllers/overview.js
  public/kibana-integrations/kibana-discover.js
Labels: 3.2, bugfix, discover

#460 Removed useless Elasticsearch request
  server/controllers/wazuh-elastic.js
Labels: 3.2, backend

#461 Fix changing agent not render
  public/controllers/agents.js
Labels: 3.2, bugfix, discover

#463 Added more options to wrong url parameter checking
  server/controllers/error-response.js
Labels: 3.2, backend

#464 Check if it's a local change cross tabs or same tab
  public/controllers/agents.js
  public/controllers/overview.js
Labels: 3.2, bugfix

#465 Fix extensions wrong situation
  public/controllers/settings.js
  public/templates/settings/settings.html
Labels: 3.2, bugfix

#466 Fix gdpr
  server/controllers/wazuh-api.js
Labels: 3.2, backend

#474 Fix cluster.name filter
  public/controllers/agents.js
  public/controllers/overview.js
Labels: 3.2, bugfix

#477 Refreshing known fields on settings while updating index pattern
  public/controllers/settings.js
Labels: 3.2, bugfix

#478 Prevents get the agent key
  server/controllers/wazuh-api.js
Labels: 3.2, bugfix

#480 Add specific filter for monitoring
  public/kibana-integrations/kibana-visualization.js
Labels: 3.2, bugfix

#483 Allowing to show monitoring data without ingesting information
  config.yml
  server/monitoring.js
Labels: 3.2, backend, bugfix

#485 Fix monitoring non-cluster filter
  public/kibana-integrations/kibana-visualization.js
Labels: 3.2, bugfix

#486 Prevents stop searching if "this.end" is true
  public/services/data-handler.js
Labels: 3.2, bugfix

#488 Fix ignoring enter on main Discover
  public/kibana-integrations/kibana-discover.js
Labels: 3.2, bugfix

#493 Prevents "000" agents in md-autocomplete
  public/services/data-handler.js
Labels: 3.2, bugfix

#495 Fix API password replacement
  server/controllers/wazuh-api-elastic.js
Labels: 3.2, bugfix

#497 Added two missing fields. Non searchable
  server/integration-files/known-fields.js
Labels: bugfix
