Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2019-02, with the labels that each got.

#1208 Change method to resizing wazuh logo
  public/directives/wz-menu/wz-menu.html
  public/img/icon_fail.svg
  public/less/common.less
  public/templates/error-handler/blank-screen.html
Labels: bug

#1204 2nd iteration ruleset configuration editions
  public/controllers/management/cdblists.js
  public/controllers/management/config-groups.js
  public/controllers/management/config-ruleset.js
  public/controllers/management/decoders.js
  public/controllers/management/edition.js
  public/controllers/management/groups.js
  public/controllers/management/rules.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/templates/management/configuration/config-edition/config-edition.html
  public/templates/management/configuration/config-groups/config-groups.html
  public/templates/management/configuration/config-ruleset/config-ruleset.html
  public/templates/management/groups/groups.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/rules/rules-detail.html
Labels: enhancement

#1207 2nd iteration back button
  index.js
  public/app.js
  public/controllers/management/cdblists.js
  public/controllers/management/config-groups.js
  public/controllers/management/config-ruleset.js
  public/controllers/management/decoders.js
  public/controllers/management/groups.js
  public/controllers/management/management.js
  public/controllers/management/rules.js
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-tag-filter/wz-tag-filter.less
  public/directives/wz-welcome-card/wz-welcome-card.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/factories/tab-visualizations.js
  public/img/icon.svg
  public/less/common.less
  public/less/component.less
  public/less/layout.less
  public/less/typography.less
  public/less/ui_framework.css
  public/services/save-config.js
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-fim.html
  public/templates/agents/agents-gdpr.html
  public/templates/agents/agents-general.html
  public/templates/agents/agents-pci.html
  public/templates/agents/agents-welcome.html
  public/templates/management/groups/groups.html
  public/templates/overview/overview-fim.html
  public/templates/overview/overview-vuls.html
  public/utils/cdblist-to-object.js
  public/utils/config-handler.js
  server/integration-files/known-fields.js
  server/integration-files/visualizations/agents/agents-fim.js
  server/integration-files/visualizations/agents/agents-gdpr.js
  server/integration-files/visualizations/agents/agents-general.js
  server/integration-files/visualizations/agents/agents-pci.js
  server/integration-files/visualizations/overview/overview-fim.js
  server/integration-files/visualizations/overview/overview-general.js
  server/integration-files/visualizations/overview/overview-vuls.js
Labels: enhancement

#1212 Fixes and improvements cdb lists management
  public/controllers/management/config-ruleset.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-list-manage/wz-list-manage.js
  public/less/common.less
  public/less/layout.less
  public/templates/management/configuration/config-ruleset/config-ruleset.html
Labels: bug

#1222 Restart manager/cluster button
  public/app.js
  public/controllers/management/config-groups.js
  public/controllers/management/config-ruleset.js
  public/controllers/management/edition.js
  public/controllers/management/management.js
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/less/height.less
  public/less/layout.less
  public/services/config-handler.js
  public/services/index.js
  public/services/save-config.js
  public/templates/agents/agents-welcome.html
  public/templates/management/configuration/config-edition/config-edition.html
  public/templates/management/configuration/config-groups/config-groups.html
  public/templates/management/configuration/config-ruleset/config-ruleset.html
  public/templates/management/configuration/configuration.head
  public/templates/management/management.head
Labels: enhancement

#1226 Fix disable button behavior
  public/controllers/management/management.js
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: bug

#1233 Refactor local ruleset edition, configuration management, config view
  public/controllers/management/cdblists.js
  public/controllers/management/configuration.js
  public/controllers/management/decoders.js
  public/controllers/management/edition.js
  public/controllers/management/rules.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-multiple-selector/wz-multiple-selector.html
  public/directives/wz-table/lib/parse-value.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/less/typography.less
  public/services/config-handler.js
  public/templates/agents/agents-fim.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
  public/templates/management/configuration/active-response/active-response.html
  public/templates/management/configuration/active-response/agents-active-response.html
  public/templates/management/configuration/active-response/commands.html
  public/templates/management/configuration/agentless/agentless.html
  public/templates/management/configuration/alerts/email-alerts.html
  public/templates/management/configuration/alerts/general-alerts.html
  public/templates/management/configuration/alerts/labels.html
  public/templates/management/configuration/alerts/reports.html
  public/templates/management/configuration/alerts/syslog.html
  public/templates/management/configuration/amazon-s3/amazon-s3.foot
  public/templates/management/configuration/cis-cat/cis-cat.foot
  public/templates/management/configuration/client-buffer/client-buffer.html
  public/templates/management/configuration/client/client.html
  public/templates/management/configuration/cluster/cluster.html
  public/templates/management/configuration/config-edition/config-edition.html
  public/templates/management/configuration/config-groups/config-groups.html
  public/templates/management/configuration/config-ruleset/config-ruleset.html
  public/templates/management/configuration/configuration.head
  public/templates/management/configuration/configuration.pug
  public/templates/management/configuration/database-output/database-output.html
  public/templates/management/configuration/global-configuration/global.html
  public/templates/management/configuration/global-configuration/remote.html
  public/templates/management/configuration/integrations/integrations.html
  public/templates/management/configuration/integrity-monitoring/integrity-monitoring.foot
  public/templates/management/configuration/inventory/inventory.html
  public/templates/management/configuration/log-collection/localfile.html
  public/templates/management/configuration/log-collection/socket.html
  public/templates/management/configuration/open-scap/open-scap.foot
  public/templates/management/configuration/osquery/osquery.html
  public/templates/management/configuration/policy-monitoring/policy-monitoring.foot
  public/templates/management/configuration/registration-service/registration-service.html
  public/templates/management/configuration/ruleset/ruleset.foot
  public/templates/management/configuration/vulnerabilities/vulnerabilities.foot
  public/templates/management/configuration/wazuh-commands/wazuh-commands.html
  public/templates/management/configuration/welcome.html
  public/templates/management/groups/groups.html
  public/templates/management/ruleset/cdblists/cdblists-detail.html
  public/templates/management/ruleset/cdblists/cdblists-list.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/management/status.html
  public/templates/management/welcome.html
Labels: enhancement

#1218 Update API request list model
  util/api-request-list.js
Labels: enhancement

#1229 Restart agents
  public/controllers/agent/agents.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/less/common.less
  public/less/height.less
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
Labels: enhancement

#1243 Wazuh monitoring enhancements
  config.yml
  public/services/resolves/get-config.js
  public/templates/settings/settings-configuration.html
  public/utils/config-equivalences.js
  server/lib/index-date.js
  server/lib/update-configuration.js
  server/monitoring.js
Labels: enhancement

#1244 Testing fixes on ruleset edition
  public/controllers/management/config-ruleset.js
  public/controllers/management/decoders.js
  public/controllers/management/management.js
  public/controllers/management/rules.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/img/new_logo_white.svg
  public/img/new_logo_white_wolf.svg
  public/less/common.less
  public/less/layout.less
  public/templates/agents/agents-welcome.html
  public/templates/management/configuration/config-edition/config-edition.html
  public/templates/management/ruleset/cdblists/cdblists-detail.html
  public/templates/management/ruleset/cdblists/cdblists-list.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/management/ruleset/ruleset.head
  public/templates/management/status.html
  server/controllers/wazuh-reporting.js
Labels: bug, enhancement, testing

#1253 Switches design and other improvements
  public/controllers/management/decoders.js
  public/controllers/management/management.js
  public/controllers/management/rules.js
  public/directives/index.js
  public/directives/wz-kbn-switch/wz-kbn-switch.html
  public/directives/wz-kbn-switch/wz-kbn-switch.js
  public/directives/wz-table/wz-table.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/settings/settings-extensions.html
Labels: enhancement

#1256 Fix truncate text in tables
  public/directives/wz-table/wz-table.html
Labels: bug

#1258 Show tooltip only in truncated texts
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
Labels: enhancement

#1257 Show "configuration assessment" configuration
  public/directives/wz-config-viewer/wz-config-viewer.html
  public/templates/management/configuration/policy-monitoring/pm-configuration-assessment.html
  public/templates/management/configuration/policy-monitoring/policy-monitoring.head
  public/templates/management/configuration/policy-monitoring/policy-monitoring.pug
  public/templates/management/configuration/welcome.html
Labels: enhancement

#1261 Fix virus total extension switch
  public/templates/settings/settings-extensions.html
Labels: bug

#1263 UI/UX improvements (1)
  public/controllers/agent/agents.js
  public/controllers/management/decoders.js
  public/controllers/management/edition.js
  public/controllers/management/management.js
  public/controllers/management/rules.js
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/directives/wz-data-table/wz-data-table-directive.js
  public/directives/wz-kbn-switch/wz-kbn-switch.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/directives/wz-tag-filter/wz-tag-filter.less
  public/directives/wz-welcome-card/wz-welcome-card.html
  public/directives/wz-welcome-card/wz-welcome-card.ts
  public/directives/wz-xml-file-editor/wz-xml-file-editor.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.less
  public/less/common.less
  public/less/layout.less
  public/less/typography.less
  public/services/config-handler.js
  public/services/data-factory.js
  public/templates/agents/agents-sca.html
  public/templates/agents/agents-welcome.html
  public/templates/management/configuration/config-edition/config-edition.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/management/status.html
  public/templates/management/welcome.html
  public/templates/overview/overview-welcome.html
  public/utils/remove-hash-key.js
  server/controllers/wazuh-elastic.js
  server/integration-files/visualizations/agents/agents-sca.js
  server/reporting/tab-description.js
Labels: enhancement

#1267 Fix rules save
  public/controllers/management/rules.js
Labels: bug

#1269 Fix decoders save
  public/controllers/management/decoders.js
Labels: bug
