Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2019-10, with the labels that each got.

#1834 Fix when exporting as csv the files in a group
  server/controllers/wazuh-api.js
Labels: bug

#1810 Add E2E tests to the enviroment
  package.json
  public/controllers/overview/components/welcome.js
  public/directives/wz-menu/wz-menu.html
  public/templates/overview/overview-fim.html
  public/templates/overview/overview-general.html
  public/utils/strings-tools.js
  server/integration-files/visualizations/overview/overview-fim.js
  test/functional/apps/overview/_integrity_monitoring.ts
  test/functional/apps/overview/_security_events.ts
  test/functional/apps/overview/index.ts
  test/functional/config.js
  test/functional/page_objects/api_page.js
  test/functional/page_objects/index.js
  test/functional/page_objects/wazuh_common_page.js
  test/functional/services/area_chart.ts
  test/functional/services/array_helper.ts
  test/functional/services/es_area_chart.ts
  test/functional/services/es_pie_chart.ts
  test/functional/services/es_table_viz.ts
  test/functional/services/extension_popover.js
  test/functional/services/index.js
  test/functional/services/pie_chart.ts
  test/functional/services/table_viz.ts
Labels: testing:e2e

#1846 Improve API messages and styles
  public/controllers/management/components/reporting-table.js
  public/controllers/settings/components/add-api.js
  public/controllers/settings/components/api-is-down.js
  public/controllers/settings/settings.js
  public/less/common.less
Labels: enhancement
