Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2019-07, with the labels that each got.

#1569 Several 3.9.3 fixes
  public/controllers/management/status.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.html
  public/kibana-integrations/loader/embedded_visualize_handler.ts
  public/services/ruleset-handler.js
  public/templates/management/configuration/integrity-monitoring/fim-ignored.html
  public/templates/management/configuration/policy-monitoring/pm-ignored.html
  public/templates/management/configuration/policy-monitoring/policy-monitoring.head
  public/templates/management/configuration/policy-monitoring/policy-monitoring.pug
  public/templates/management/ruleset/files/files.html
  server/integration-files/visualizations/agents/agents-fim.js
  server/lib/elastic-wrapper.js
Labels: bug

#1588 Fix dynamic height in dev tools
  package.json
  public/controllers/dev-tools/dev-tools.js
  server/integration-files/visualizations/agents/agents-fim.js
Labels: bug

#1528 React component to select modules in configuration exporting
  public/controllers/agent/agents.js
  public/controllers/agent/components/export-configuration.js
  public/controllers/agent/components/welcome.js
  public/controllers/agent/index.js
  public/controllers/management/groups.js
  public/controllers/misc/reporting.js
  public/less/common.less
  public/less/layout.less
  public/services/reporting.js
  public/templates/agents/agents-welcome.html
  public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
  public/templates/management/configuration/welcome.html
  public/templates/management/groups/groups.html
  public/templates/management/reporting.html
  public/utils/components-os-support.js
  server/controllers/wazuh-reporting.js
  server/reporting/agent-configuration.js
Labels: enhancement

#1590 Improve processes tables
  public/directives/wz-table-eui/wz-table-directive.js
  public/templates/agents/agents-syscollector.html
  util/csv-key-equivalence.js
Labels: UI/UX, enhancement

#1599 [backport-6.8] Improve processes tables
  public/templates/agents/agents-syscollector.html
  util/csv-key-equivalence.js
Labels: UI/UX, enhancement

#1603 [backport-7.1.1] Improve processes tables
  public/templates/agents/agents-syscollector.html
  util/csv-key-equivalence.js
Labels: UI/UX, enhancement

#1637 Fix pinned agent filters
  public/kibana-integrations/kibana-discover.js
Labels: bug

#1635 Fix eui tables pagination in searches
  public/directives/wz-table-eui/components/table.js
  public/directives/wz-table-eui/wz-table-directive.js
Labels: bug
