Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2019-05, with the labels that each got.

#1419 Fix table fields in not custom Columns
  public/directives/wz-table/wz-table.html
Labels: bug

#1429 Fix logs viewer height and dev-tools resizable
  public/controllers/dev-tools/dev-tools.js
  public/controllers/management/logs.js
  public/directives/wz-config-viewer/wz-config-viewer.js
Labels: bug

#1441 Improve dynamic height
  public/directives/wz-config-viewer/wz-config-viewer.html
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.less
  public/templates/management/configuration/cluster/cluster.html
  public/templates/management/configuration/config-edition/config-edition.html
  public/templates/management/groups/groups.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/files/files.html
  public/templates/management/ruleset/rules/rules-detail.html
Labels: bug, enhancement

#1442 Minor fixes in agents configuration
  public/controllers/management/configuration.js
  public/templates/management/configuration/alerts/labels.html
  public/templates/management/configuration/client/client.html
Labels: bug

#1437 No filter by path in config validation
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: bug, operations

#1447 Fix discover background
  public/less/common.less
Labels: bug

#1406 Add timezone offset to dates
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/management/logs.js
  public/controllers/misc/reporting.js
  public/directives/wz-table/lib/parse-value.js
  public/directives/wz-table/wz-table-directive.js
  public/services/index.js
  public/services/time-service.js
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-sca.html
  public/templates/agents/agents-syscollector.html
  public/templates/agents/agents-welcome.html
  public/templates/management/reporting.html
Labels: enhancement

#1451 Fix logs viewer top scrolling
  public/controllers/management/logs.js
  public/directives/wz-config-viewer/wz-config-viewer.js
Labels: bug

#1453 Remove API button moved
  public/templates/settings/settings-api.html
Labels: enhancement

#1454 Fix Zulu identifier in reports creation date
  public/services/time-service.js
Labels: bug

#1470 No longer using "ansicolors" as a dependency
  server/initialize.js
  server/lib/refresh-known-fields.js
  server/monitoring.js
Labels: installation, oss

#1478 Fix SCA result status and file width cells
  public/directives/wz-table/wz-table.html
  public/templates/agents/agents-sca.html
Labels: bug

#1477 Change level by groups in visualization title
  public/templates/agents/agents-general.html
  server/integration-files/visualizations/agents/agents-general.js
Labels: bug
