Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2019-03, with the labels that each got.

#1275 Wazuh icon proportions adapted
  index.js
  public/hack-icon-style.js
  public/less/icon-style.less
Labels: enhancement

#1272 Refresh rules and decoders after editing them
  public/controllers/management/decoders.js
  public/controllers/management/rules.js
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/rules/rules-detail.html
Labels: enhancement

#1271 Added new columns in SCA policies tables
  public/directives/wz-table/wz-table.html
  public/less/layout.less
  public/templates/agents/agents-sca.html
  util/csv-key-equivalence.js
Labels: enhancement

#1276 Merge dynamic known fields, added new cron task
  init.js
  public/services/routes.js
  server/controllers/wazuh-elastic.js
  server/index-pattern-cron-job.js
  server/lib/elastic-wrapper.js
Labels: enhancement

#1282 Delete and verify overwriting on rules/decoders/lists files
  index.js
  public/controllers/management/decoders.js
  public/controllers/management/files.js
  public/controllers/management/index.js
  public/controllers/management/rules.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/hack-icon-style.js
  public/services/ruleset-handler.js
  public/templates/management/configuration/welcome.html
  public/templates/management/ruleset/cdblists/cdblists-list.html
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/files/files.head
  public/templates/management/ruleset/files/files.html
  public/templates/management/ruleset/files/files.pug
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/management/ruleset/ruleset.head
  public/templates/management/ruleset/ruleset.pug
Labels: enhancement

#1288 Add name filter tag
  public/controllers/agent/agents-preview.js
Labels: enhancement

#1284 Daemons status design changed
  public/controllers/management/status.js
  public/less/common.less
  public/templates/management/status.html
Labels: enhancement

#1290 Management view UI improvements
  public/controllers/management/decoders.js
  public/controllers/management/files.js
  public/controllers/management/rules.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/templates/management/management.head
  public/templates/management/ruleset/decoders/decoders-detail.html
  public/templates/management/ruleset/files/files.head
  public/templates/management/ruleset/files/files.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/welcome.html
Labels: bug, enhancement

#1291 Change the operators between tags
  public/directives/wz-tag-filter/wz-tag-filter.html
  public/directives/wz-tag-filter/wz-tag-filter.js
  public/directives/wz-tag-filter/wz-tag-filter.less
Labels: enhancement

#1292 Logs viewer
  public/controllers/management/logs.js
  public/directives/wz-config-viewer/wz-config-viewer.html
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/directives/wz-config-viewer/wz-config-viewer.less
  public/directives/wz-table/wz-table-directive.js
  public/services/data-factory.js
  public/templates/management/logs.html
Labels: enhancement

#1293 UI modifications for visualizations and more
  .eslintignore
  public/app.js
  public/controllers/dev-tools/dev-tools.js
  public/controllers/management/cdblists.js
  public/directives/wz-list-manage/wz-list-manage.html
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/less/common.less
  public/less/typography.less
  public/less/ui_framework.css
  public/templates/agents-prev/agents-prev.html
  public/templates/agents/agents-audit.html
  public/templates/agents/agents-ciscat.html
  public/templates/agents/agents-fim.html
  public/templates/agents/agents-gdpr.html
  public/templates/agents/agents-general.html
  public/templates/agents/agents-oscap.html
  public/templates/agents/agents-osquery.html
  public/templates/agents/agents-pci.html
  public/templates/agents/agents-pm.html
  public/templates/agents/agents-sca.html
  public/templates/agents/agents-virustotal.html
  public/templates/agents/agents-vuls.html
  public/templates/agents/agents-welcome.html
  public/templates/agents/agents.head
  public/templates/dev-tools/dev-tools.html
  public/templates/management/groups/groups.html
  public/templates/management/logs.html
  public/templates/management/monitoring/main-timelions.html
  public/templates/management/ruleset/cdblists/cdblists-list.html
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/files/files.html
  public/templates/management/ruleset/rules/rules-detail.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/overview/overview-audit.html
  public/templates/overview/overview-aws.html
  public/templates/overview/overview-ciscat.html
  public/templates/overview/overview-fim.html
  public/templates/overview/overview-gdpr.html
  public/templates/overview/overview-general.html
  public/templates/overview/overview-oscap.html
  public/templates/overview/overview-osquery.html
  public/templates/overview/overview-pci.html
  public/templates/overview/overview-pm.html
  public/templates/overview/overview-virustotal.html
  public/templates/overview/overview-vuls.html
  public/templates/settings/settings-api.html
  public/utils/table-col-resizable.js
  server/integration-files/visualizations/overview/overview-fim.js
  server/integration-files/visualizations/overview/overview-general.js
Labels: enhancement, frontend

#1301 Add/remove agents even if it's the default group
  public/templates/management/groups/groups.html
Labels: pending-api

#1305 Refresh check agent sync in configuration
  public/controllers/agent/agents.js
Labels: enhancement

#1304 Ruleset Files moved to rules/decoders section
  public/controllers/management/decoders.js
  public/controllers/management/files.js
  public/controllers/management/management.js
  public/controllers/management/rules.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/templates/management/ruleset/decoders/decoders-list.html
  public/templates/management/ruleset/decoders/decoders.head
  public/templates/management/ruleset/files/files.head
  public/templates/management/ruleset/files/files.html
  public/templates/management/ruleset/rules/rules-list.html
  public/templates/management/ruleset/rules/rules.head
  public/templates/management/ruleset/ruleset.head
Labels: enhancement

#1307 Fixes cluster nodes details
  public/controllers/management/edition.js
  public/directives/wz-menu/wz-menu.less
  public/directives/wz-table/lib/click-action.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-tag-filter/wz-tag-filter.less
  public/templates/management/monitoring/nodes-detail.html
  public/templates/management/monitoring/nodes-list.html
  public/templates/management/ruleset/files/files.html
Labels: bug

#1309 Some UI fixes
  public/less/common.less
  public/templates/management/configuration/integrity-monitoring/fim-whodata.html
Labels: bug

#1310 Show no results message in logs
  public/controllers/management/logs.js
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/templates/management/logs.html
Labels: enhancement

#1315 Enable agents remove option in default group
  public/directives/wz-table/wz-table.html
Labels: enhancement

#1317 Testing fixes
  public/controllers/agent/agents.js
  public/controllers/management/cdblists.js
  public/controllers/management/config-groups.js
  public/controllers/management/config-ruleset.js
  public/controllers/management/groups.js
  public/controllers/management/logs.js
  public/directives/wz-config-viewer/wz-config-viewer.js
  public/directives/wz-list-manage/wz-list-manage.js
  public/directives/wz-table/lib/pagination.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/services/reporting.js
  public/templates/management/groups/groups.html
  public/utils/table-col-resizable.js
Labels: bug

#1321 No agents view and how to register agents
  CHANGELOG.md
  public/controllers/agent/agents-preview.js
  public/controllers/dev-tools/dev-tools.js
  public/directives/index.js
  public/directives/wz-register-agents/wz-register-agents.html
  public/directives/wz-register-agents/wz-register-agents.js
  public/directives/wz-register-agents/wz-register-agents.less
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/img/agent.png
  public/less/common.less
  public/templates/agents-prev/agents-prev.html
Labels: enhancement

#1334 Adapt Wazuh app for Kibana v6.7.0
  CHANGELOG.md
  README.md
  index.js
  package.json
  public/hack-icon-style.js
  public/img/icon.svg
  public/kibana-integrations/kbn-global-timepicker/kbn_global_timepicker.html
  public/kibana-integrations/kbn_top_nav/bread_crumbs/bread_crumbs.html
  public/kibana-integrations/kbn_top_nav/bread_crumbs/bread_crumbs.js
  public/kibana-integrations/kbn_top_nav/kbn_top_nav.html
  public/kibana-integrations/kibana-discover.js
  public/kibana-integrations/kibana-filter-bar.js
  public/kibana-integrations/loader/embedded_visualize_handler.ts
  public/kibana-integrations/loader/types.ts
  public/kibana-integrations/loader/visualize_data_loader.ts
  public/less/common.less
  public/less/icon-style.less
  public/templates/agents/agents.head
  public/templates/kibana-template/kibana-discover-template.html
  public/templates/kibana-template/kibana-filterbar-template.html
  public/templates/management/monitoring/monitoring.head
  public/templates/overview/overview-aws.html
  public/templates/overview/overview.head
  server/integration-files/visualizations/agents/agents-audit.js
  server/integration-files/visualizations/agents/agents-ciscat.js
  server/integration-files/visualizations/agents/agents-fim.js
  server/integration-files/visualizations/agents/agents-general.js
  server/integration-files/visualizations/agents/agents-oscap.js
  server/integration-files/visualizations/agents/agents-pm.js
  server/integration-files/visualizations/agents/agents-virustotal.js
  server/integration-files/visualizations/agents/agents-vuls.js
  server/integration-files/visualizations/cluster/monitoring.js
  server/integration-files/visualizations/overview/overview-audit.js
  server/integration-files/visualizations/overview/overview-ciscat.js
  server/integration-files/visualizations/overview/overview-general.js
  server/integration-files/visualizations/overview/overview-pm.js
  server/integration-files/visualizations/overview/overview-virustotal.js
Labels: enhancement
