Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2019-01, with the labels that each got.

#1119 Refresh known fields on health check
  public/controllers/misc/health-check.js
  server/controllers/wazuh-elastic.js
  server/initialize.js
  server/lib/refresh-known-fields.js
  server/monitoring.js
Labels: enhancement

#1120 Less strict memory check
  package.json
  public/services/resolves/check-ram.js
Labels: backport

#1121 Update master branch
  package.json
  public/services/resolves/check-ram.js
Labels: backport

#1096 Xml file editor and multi-item selector
  CHANGELOG.md
  public/controllers/agent/agents.js
  public/controllers/management/groups.js
  public/directives/index.js
  public/directives/wz-multiple-selector/wz-multiple-selector.html
  public/directives/wz-multiple-selector/wz-multiple-selector.js
  public/directives/wz-multiple-selector/wz-multiple-selector.less
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/directives/wz-tag-filter/wz-tag-filter.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.html
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
  public/directives/wz-xml-file-editor/wz-xml-file-editor.less
  public/less/common.less
  public/less/layout.less
  public/services/group-handler.js
  public/services/index.js
  public/templates/agents/agents-welcome.html
  public/templates/management/groups/groups.html
  public/utils/codemirror/formatting.js
  public/utils/codemirror/index.js
  public/utils/codemirror/xml.js
  server/controllers/wazuh-api.js
  server/routes/wazuh-api.js
Labels: enhancement

#1127 Some 3.8 fixes
  public/controllers/agent/agents.js
  public/controllers/management/groups.js
  public/directives/wz-table/wz-table-directive.js
  public/less/layout.less
Labels: enhancement

#1128 Fix xml files editor validator
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: bug

#1131 Fixes in XML and multiple selector directives
  public/directives/wz-multiple-selector/wz-multiple-selector.html
  public/utils/codemirror/formatting.js
Labels: bug

#1132 Minor fixes
  public/controllers/management/groups.js
  public/directives/wz-tag-filter/wz-tag-filter.js
Labels: bug

#1153 Groups management with permissions
  public/controllers/agent/agents.js
  public/controllers/management/groups.js
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/templates/agents/agents-welcome.html
  public/templates/management/groups/groups.html
Labels: enhancement, frontend

#1168 Show readable API error response messages
  server/controllers/wazuh-api.js
  util/api-errors-equivalence.js
Labels: enhancement

#1165 Customized empty results message in tables directive
  public/directives/wz-table/wz-table-directive.js
  public/directives/wz-table/wz-table.html
  public/templates/management/groups/groups.html
Labels: enhancement

#1159 Escape xml not allowed symbols in validation
  public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: bug
