Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2020-11, with the labels that each got.

#2572 [4.0-7.9] Enhance render Windows file permissions
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/common/util/index.ts
  public/components/common/util/truncate-horizontal-components/truncate-horizontal-components.tsx
Labels: enhancement

#2596 updated macOS package URL
  public/controllers/agent/components/register-agent.js
Labels: operations

#2655 fix(fronted): fixed the check of API and APP version in health check
  CHANGELOG.md
  public/components/health-check/health-check.tsx
Labels: bug
