Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-06, with the labels that each got.

#3345 Fix/elastic UI upgrade breaking changes in 7.11 and 7.12 3318
  CHANGELOG.md
  public/components/add-modules-data/module-guide.js
  public/components/overview/compliance-table/components/requirements/requirements.tsx
  public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
  public/components/overview/mitre/components/tactics/tactics.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/components/wz-search-bar/components/wz-search-badges/context-menu.tsx
  public/controllers/agent/components/register-agent.js
Labels: 7.12

#3349 Fix error due short graphs
  CHANGELOG.md
  public/kibana-integrations/kibana-vis.js
Labels: 7.12

#3355 Fix/3320 visualization label overlap
  CHANGELOG.md
  server/integration-files/visualizations/agents/agents-audit.ts
  server/integration-files/visualizations/agents/agents-aws.ts
  server/integration-files/visualizations/agents/agents-ciscat.ts
  server/integration-files/visualizations/agents/agents-docker.ts
  server/integration-files/visualizations/agents/agents-fim.ts
  server/integration-files/visualizations/agents/agents-gcp.ts
  server/integration-files/visualizations/agents/agents-gdpr.ts
  server/integration-files/visualizations/agents/agents-general.ts
  server/integration-files/visualizations/agents/agents-hipaa.ts
  server/integration-files/visualizations/agents/agents-mitre.ts
  server/integration-files/visualizations/agents/agents-nist.ts
  server/integration-files/visualizations/agents/agents-oscap.ts
  server/integration-files/visualizations/agents/agents-osquery.ts
  server/integration-files/visualizations/agents/agents-pci.ts
  server/integration-files/visualizations/agents/agents-pm.ts
  server/integration-files/visualizations/agents/agents-tsc.ts
  server/integration-files/visualizations/agents/agents-virustotal.ts
  server/integration-files/visualizations/agents/agents-vuls.ts
  server/integration-files/visualizations/agents/agents-welcome.ts
  server/integration-files/visualizations/cluster/monitoring.ts
  server/integration-files/visualizations/cluster/statistics.ts
  server/integration-files/visualizations/overview/overview-audit.ts
  server/integration-files/visualizations/overview/overview-aws.ts
  server/integration-files/visualizations/overview/overview-ciscat.ts
  server/integration-files/visualizations/overview/overview-docker.ts
  server/integration-files/visualizations/overview/overview-fim.ts
  server/integration-files/visualizations/overview/overview-gcp.ts
  server/integration-files/visualizations/overview/overview-gdpr.ts
  server/integration-files/visualizations/overview/overview-general.ts
  server/integration-files/visualizations/overview/overview-hipaa.ts
  server/integration-files/visualizations/overview/overview-mitre.ts
  server/integration-files/visualizations/overview/overview-nist.ts
  server/integration-files/visualizations/overview/overview-oscap.ts
  server/integration-files/visualizations/overview/overview-osquery.ts
  server/integration-files/visualizations/overview/overview-pci.ts
  server/integration-files/visualizations/overview/overview-pm.ts
  server/integration-files/visualizations/overview/overview-tsc.ts
  server/integration-files/visualizations/overview/overview-virustotal.ts
  server/integration-files/visualizations/overview/overview-vuls.ts
Labels: 7.12

#3358 Fix export to csv table button 7.11 & 7.12
  CHANGELOG.md
  server/integration-files/visualizations/agents/agents-audit.ts
  server/integration-files/visualizations/agents/agents-aws.ts
  server/integration-files/visualizations/agents/agents-ciscat.ts
  server/integration-files/visualizations/agents/agents-docker.ts
  server/integration-files/visualizations/agents/agents-fim.ts
  server/integration-files/visualizations/agents/agents-gcp.ts
  server/integration-files/visualizations/agents/agents-gdpr.ts
  server/integration-files/visualizations/agents/agents-general.ts
  server/integration-files/visualizations/agents/agents-hipaa.ts
  server/integration-files/visualizations/agents/agents-mitre.ts
  server/integration-files/visualizations/agents/agents-nist.ts
  server/integration-files/visualizations/agents/agents-oscap.ts
  server/integration-files/visualizations/agents/agents-osquery.ts
  server/integration-files/visualizations/agents/agents-pci.ts
  server/integration-files/visualizations/agents/agents-pm.ts
  server/integration-files/visualizations/agents/agents-tsc.ts
  server/integration-files/visualizations/agents/agents-virustotal.ts
  server/integration-files/visualizations/agents/agents-vuls.ts
  server/integration-files/visualizations/overview/overview-audit.ts
  server/integration-files/visualizations/overview/overview-aws.ts
  server/integration-files/visualizations/overview/overview-ciscat.ts
  server/integration-files/visualizations/overview/overview-docker.ts
  server/integration-files/visualizations/overview/overview-fim.ts
  server/integration-files/visualizations/overview/overview-gcp.ts
  server/integration-files/visualizations/overview/overview-gdpr.ts
  server/integration-files/visualizations/overview/overview-general.ts
  server/integration-files/visualizations/overview/overview-hipaa.ts
  server/integration-files/visualizations/overview/overview-mitre.ts
  server/integration-files/visualizations/overview/overview-nist.ts
  server/integration-files/visualizations/overview/overview-oscap.ts
  server/integration-files/visualizations/overview/overview-osquery.ts
  server/integration-files/visualizations/overview/overview-pci.ts
  server/integration-files/visualizations/overview/overview-pm.ts
  server/integration-files/visualizations/overview/overview-tsc.ts
  server/integration-files/visualizations/overview/overview-virustotal.ts
  server/integration-files/visualizations/overview/overview-vuls.ts
Labels: 7.12

#3377 Added lowercase levels in storeError
  CHANGELOG.md
  public/react-services/error-orchestrator/error-orchestrator-base.ts
Labels: error-handling

#3368 [Feature] Mitre Att&ck Intelligence + adapt Framework
  CHANGELOG.md
  common/api-info/endpoints.json
  common/api-info/security-actions.json
  public/components/common/hooks/index.ts
  public/components/common/hooks/use_async_action.test.tsx
  public/components/common/hooks/use_async_action.ts
  public/components/common/modules/discover/discover.tsx
  public/components/common/modules/main-agent.tsx
  public/components/common/modules/main-overview.tsx
  public/components/common/modules/modules-defaults.js
  public/components/common/panels/__snapshots__/panel_split.test.tsx.snap
  public/components/common/panels/index.ts
  public/components/common/panels/panel_split.test.tsx
  public/components/common/panels/panel_split.tsx
  public/components/common/tables/index.ts
  public/components/common/tables/table-default.tsx
  public/components/common/tables/table-with-search-bar.tsx
  public/components/common/tables/table-wz-api.tsx
  public/components/common/util/index.ts
  public/components/common/util/markdown/__snapshots__/markdown.test.tsx.snap
  public/components/common/util/markdown/markdown.test.tsx
  public/components/common/util/markdown/markdown.tsx
  public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
  public/components/overview/mitre/components/techniques/components/search-bar-tecniques/search-bar-techniques.tsx
  public/components/overview/mitre/components/techniques/components/technique/index.ts
  public/components/overview/mitre/components/techniques/components/technique/teqnique.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/components/overview/mitre/lib/index.ts
  public/components/overview/mitre/lib/mitre_techniques.ts
  public/components/overview/mitre/mitre.tsx
  public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
  public/components/overview/mitre_attack_intelligence/all_resources.tsx
  public/components/overview/mitre_attack_intelligence/all_resources_search_results.tsx
  public/components/overview/mitre_attack_intelligence/index.ts
  public/components/overview/mitre_attack_intelligence/intelligence.test.tsx
  public/components/overview/mitre_attack_intelligence/intelligence.tsx
  public/components/overview/mitre_attack_intelligence/intelligence_left_panel.tsx
  public/components/overview/mitre_attack_intelligence/intelligence_right_panel.tsx
  public/components/overview/mitre_attack_intelligence/resource.tsx
  public/components/overview/mitre_attack_intelligence/resource_button.scss
  public/components/overview/mitre_attack_intelligence/resource_button.tsx
  public/components/overview/mitre_attack_intelligence/resource_detail_flyout.tsx
  public/components/overview/mitre_attack_intelligence/resource_detail_references_table.tsx
  public/components/overview/mitre_attack_intelligence/resources.tsx
  public/components/wz-search-bar/lib/filters-to-object.ts
  public/controllers/management/components/management/ruleset/rule-info.js
  public/styles/common.scss
Labels: enhancement

#3376 feat(error-orchestrator): Improved on createGetterSetter
  public/components/common/error-boundary/error-boundary.tsx
  public/kibana-services.ts
  public/plugin.ts
  public/react-services/error-orchestrator/error-orchestrator-business.ts
  public/react-services/error-orchestrator/error-orchestrator.service.ts
  public/react-services/error-orchestrator/types.ts
  public/react-services/index.ts
  public/utils/create-getter-setter.ts
Labels: error-handling

#3378 Fix creation of json file after a ui log
  public/react-services/error-orchestrator/error-orchestrator-base.ts
  server/lib/base-logger.ts
Labels: error-handling

#3387 Identity components with hocs
  public/components/common/hocs/error-boundary/with-error-boundary.tsx
  public/components/common/hocs/utils/utils.tsx
  public/controllers/management/index.js
Labels: error-handling

#3373 Implement try catch strategy on WzLog
  public/controllers/management/components/management/mg-logs/logs.js
  public/react-services/error-orchestrator/README.md
  public/react-services/error-orchestrator/error-orchestrator.service.ts
Labels: error-handling

#3384 Fix creation of log files
  CHANGELOG.md
  common/constants.ts
  public/components/common/error-boundary/error-boundary.tsx
  server/controllers/wazuh-utils/ui-logs.controller.test.ts
  server/controllers/wazuh-utils/ui-logs.controller.ts
  server/controllers/wazuh-utils/wazuh-utils.ts
  server/lib/base-logger.ts
  server/lib/filesystem.ts
Labels: error-handling

#3395 Now for level.Error always displayError
  public/react-services/error-orchestrator/error-orchestrator-base.ts
  public/react-services/error-orchestrator/error-orchestrator-ui.ts
Labels: error-handling

#3393 Refactor try catch in Settings section
  CHANGELOG.md
  public/components/settings/api/add-api.js
  public/components/settings/api/api-is-down.js
  public/components/settings/api/api-table.js
  public/components/settings/configuration/components/bottom-bar.tsx
  public/components/settings/configuration/components/categories/components/category/components/__snapshots__/field-form.test.tsx.snap
  public/components/settings/configuration/components/categories/components/category/components/field-form.test.tsx
  public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
  public/components/settings/modules/modules.js
  public/components/settings/settings-logs/logs.js
  public/controllers/settings/index.js
  public/react-services/app-state.js
  public/react-services/error-orchestrator/error-orchestrator-base.ts
Labels: error-handling

#3404 Refactor try catch in Controller/Agent section
  CHANGELOG.md
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-table.js
  public/controllers/agent/components/checkUpgrade.tsx
  public/controllers/agent/components/register-agent.js
Labels: error-handling

#3374 Implement try catch strategy ManagementController
  CHANGELOG.md
  public/components/common/hooks/index.ts
  public/controllers/management/management.js
  public/plugin.ts
Labels: error-handling

#3408 Refactor try catch strategy on Overview section.
  CHANGELOG.md
  public/components/visualize/wz-visualize.js
  public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
  public/controllers/overview/components/alerts-stats.js
  public/controllers/overview/components/overview-actions/agents-selection-table.js
  public/controllers/overview/components/overview-actions/agents-selector.scss
  public/controllers/overview/components/overview-actions/overview-actions.js
  public/controllers/overview/components/select-agent.js
  public/controllers/overview/components/stats.test.tsx
  public/controllers/overview/index.js
  public/controllers/overview/overview.js
Labels: error-handling

#3390 Implement try catch strategy Security
  CHANGELOG.md
  public/components/security/main.tsx
  public/components/security/policies/create-policy.tsx
  public/components/security/policies/edit-policy.tsx
  public/components/security/policies/policies-table.tsx
  public/components/security/roles-mapping/components/roles-mapping-create.tsx
  public/components/security/roles-mapping/components/roles-mapping-edit.tsx
  public/components/security/roles-mapping/components/roles-mapping-table.tsx
  public/components/security/roles-mapping/helpers/rule-editor.helper.ts
  public/components/security/roles-mapping/roles-mapping.tsx
  public/components/security/roles/edit-role.tsx
  public/components/security/roles/roles-table.tsx
  public/components/security/users/components/create-user.tsx
  public/components/security/users/components/edit-user.tsx
  public/components/security/users/components/users-table.tsx
  public/components/security/users/users.tsx
Labels: error-handling
