Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-05, with the labels that each got.

#3217 Fixed fields overlap in the agent summary screen
  CHANGELOG.md
  public/components/common/welcome/agents-info.js
  public/styles/common.scss
Labels: bug

#3197 [Refactor] Health check
  CHANGELOG.md
  public/app.js
  public/components/common/hocs/index.ts
  public/components/common/hooks/index.ts
  public/components/common/hooks/use-app-config.ts
  public/components/common/hooks/useRootScope.ts
  public/components/eui-loader.js
  public/components/health-check/components/__snapshots__/check-result.test.tsx.snap
  public/components/health-check/components/check-result.test.tsx
  public/components/health-check/components/check-result.tsx
  public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
  public/components/health-check/container/health-check.container.test.tsx
  public/components/health-check/container/health-check.container.tsx
  public/components/health-check/health-check.tsx
  public/components/health-check/index.ts
  public/components/health-check/lib/check-kibana-settings.ts
  public/components/health-check/lib/check-time-filter.ts
  public/components/health-check/lib/index.ts
  public/components/health-check/services/check-api.service.ts
  public/components/health-check/services/check-fields.service.ts
  public/components/health-check/services/check-kibana-settings.ts
  public/components/health-check/services/check-max-buckets.ts
  public/components/health-check/services/check-pattern-support.service.ts
  public/components/health-check/services/check-pattern.service.ts
  public/components/health-check/services/check-setup.service.ts
  public/components/health-check/services/check-template.service.ts
  public/components/health-check/services/check-time-filter.ts
  public/components/health-check/services/index.ts
  public/components/wz-menu/wz-menu.js
  public/react-services/index.ts
  public/react-services/load-app-config.service.ts
  public/react-services/wazuh-config.js
  public/redux/actions/appConfigActions.ts
  public/redux/reducers/appConfigReducers.ts
  public/redux/reducers/rootReducers.js
  public/redux/types.ts
Labels: enhancement

#3237 [Fix] Visualize button on Events (Discover component)
  CHANGELOG.md
  public/kibana-integrations/kibana-discover.js
Labels: bug

#3243 Vulnerabilities inventory cleanup 3242
  CHANGELOG.md
  public/components/agents/vuls/inventory/flyout.tsx
  public/components/agents/vuls/main.tsx
Labels: 4.2, enhancement

#3175 Improve api selector
  CHANGELOG.md
  public/components/common/globalBreadcrumb/globalBreadcrumb.scss
  public/components/common/globalBreadcrumb/globalBreadcrumb.tsx
  public/components/wz-menu/wz-menu.js
  public/components/wz-menu/wz-menu.scss
  public/styles/dark_theme/wz_theme_dark.scss
Labels: UI/UX, enhancement

#3292 Bugfix/3273 error check wazuh no security
  CHANGELOG.md
  server/controllers/wazuh-api.ts
Labels: bug

#3254 Rename config tag
  CHANGELOG.md
  public/components/add-modules-data/module-guide.js
Labels: 5.0

#3260 Fix 3209/improving and removing WUI error logs
  CHANGELOG.md
  server/controllers/wazuh-api.ts
  server/lib/update-registry.ts
  server/start/cron-scheduler/save-document.ts
  server/start/index.ts
  server/start/initialize/index.ts
  server/start/monitoring/index.ts
  server/start/tryCatchForIndexPermissionError.ts
Labels: enhancement

#3256 Fix/graph single api 3239
  CHANGELOG.md
  public/kibana-integrations/kibana-vis.js
Labels: 4.2, bug

#3297 [SCA] Fix the render of the checks in a SCA check
  CHANGELOG.md
  public/components/agents/sca/components/rule-text.tsx
  public/components/agents/sca/inventory.tsx
Labels: bug

#3279 Replace empty registry value name in FIM inventory
  CHANGELOG.md
  public/components/agents/fim/inventory/lib/empty-field-handler.js
  public/components/agents/fim/inventory/lib/index.ts
  public/components/agents/fim/inventory/registryValues/registryValues.tsx
  public/components/common/modules/events-enhance-discover-fields.ts
  public/styles/common.scss
Labels: 4.3, enhancement

#3258 [Health check] Add logs with the details about the check
  CHANGELOG.md
  common/constants.ts
  public/components/add-modules-data/WzSampleDataWrapper.js
  public/components/health-check/components/__snapshots__/check-result.test.tsx.snap
  public/components/health-check/components/check-result.test.tsx
  public/components/health-check/components/check-result.tsx
  public/components/health-check/components/inspect-logs-button.tsx
  public/components/health-check/components/result-icons.tsx
  public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
  public/components/health-check/container/health-check.container.test.tsx
  public/components/health-check/container/health-check.container.tsx
  public/components/health-check/services/check-api.service.ts
  public/components/health-check/services/check-fields.service.ts
  public/components/health-check/services/check-kibana-settings.service.ts
  public/components/health-check/services/check-kibana-settings.ts
  public/components/health-check/services/check-max-buckets.ts
  public/components/health-check/services/check-pattern-support.service.ts
  public/components/health-check/services/check-pattern.service.ts
  public/components/health-check/services/check-setup.service.ts
  public/components/health-check/services/check-template.service.ts
  public/components/health-check/services/check-time-filter.ts
  public/components/health-check/services/index.ts
  public/components/health-check/types/check_logger.ts
  public/components/health-check/types/result-icons-presets.ts
  public/components/settings/miscellaneous/miscellaneous.tsx
  public/components/settings/settings-logs/logs.js
  public/components/wz-menu/wz-menu-settings.js
  public/controllers/settings/index.js
  public/controllers/settings/settings.js
  public/services/resolves/get-config.js
  public/styles/common.scss
  public/templates/settings/settings.html
  server/controllers/wazuh-api.ts
  server/start/cron-scheduler/error-handler.ts
Labels: enhancement
