Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-07, with the labels that each got.

#3410 Implement try catch strategy in Ruleset
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
  public/controllers/management/components/management/ruleset/actions-buttons.js
  public/controllers/management/components/management/ruleset/decoder-info.js
  public/controllers/management/components/management/ruleset/list-editor.js
  public/controllers/management/components/management/ruleset/main-ruleset.test.tsx
  public/controllers/management/components/management/ruleset/rule-info.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/controllers/management/components/management/ruleset/ruleset-filter-bar.js
  public/controllers/management/components/management/ruleset/ruleset-table.js
  public/controllers/management/components/management/ruleset/section-selector.js
  public/controllers/management/components/management/ruleset/utils/ruleset-handler.ts
  public/controllers/management/components/management/ruleset/utils/valid-configuration.js
Labels: error-handling

#3417 Refactor try catch on Agent Fim SCA
  CHANGELOG.md
  public/components/agents/fim/inventory.tsx
  public/components/agents/fim/inventory/filterBar.tsx
  public/components/agents/fim/inventory/flyout.tsx
  public/components/agents/fim/inventory/registry-table.tsx
  public/components/agents/fim/inventory/registryValues/registryValues.tsx
  public/components/agents/fim/inventory/table.tsx
  public/components/agents/fim/main.tsx
  public/components/agents/prompts/prompt-agent-feature-version.tsx
  public/components/agents/prompts/prompt-agent-no-support-module.tsx
  public/components/agents/prompts/prompt-no-active-agent.tsx
  public/components/agents/prompts/prompt-no-selected-agent.tsx
  public/components/agents/prompts/prompt-select-agent.tsx
  public/components/agents/sca/components/compliance-text.tsx
  public/components/agents/sca/components/index.ts
  public/components/agents/sca/components/rule-text.tsx
  public/components/agents/sca/inventory.tsx
  public/components/agents/sca/main.tsx
Labels: error-handling

#3432 Changed all context value of all try-catch implementations
  CHANGELOG.md
  public/components/security/policies/create-policy.tsx
  public/components/security/policies/edit-policy.tsx
  public/components/security/policies/policies-table.tsx
  public/components/security/roles-mapping/components/roles-mapping-create.tsx
  public/components/security/roles-mapping/components/roles-mapping-edit.tsx
  public/components/security/roles-mapping/components/roles-mapping-table.tsx
  public/components/security/roles-mapping/helpers/rule-editor.helper.ts
  public/components/security/roles-mapping/roles-mapping.tsx
  public/components/security/roles/edit-role.tsx
  public/components/security/roles/roles-table.tsx
  public/components/settings/api/add-api.js
  public/components/settings/api/api-is-down.js
  public/components/settings/api/api-table.js
  public/components/settings/configuration/components/bottom-bar.tsx
  public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
  public/components/settings/modules/modules.js
  public/components/visualize/wz-visualize.js
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-table.js
  public/controllers/agent/components/checkUpgrade.tsx
  public/controllers/agent/components/register-agent.js
  public/controllers/management/components/management/mg-logs/logs.js
  public/controllers/management/management.js
  public/react-services/error-orchestrator/README.md
Labels: error-handling

#3415 Implement try catch strategy in Groups
  CHANGELOG.md
  public/components/security/main.tsx
  public/controllers/management/components/management/groups/__snapshots__/groups-main.test.tsx.snap
  public/controllers/management/components/management/groups/actions-buttons-agents.js
  public/controllers/management/components/management/groups/actions-buttons-files.js
  public/controllers/management/components/management/groups/actions-buttons-main.js
  public/controllers/management/components/management/groups/group-agents-table.js
  public/controllers/management/components/management/groups/group-files-table.js
  public/controllers/management/components/management/groups/groups-editor.js
  public/controllers/management/components/management/groups/groups-main.js
  public/controllers/management/components/management/groups/groups-main.test.tsx
  public/controllers/management/components/management/groups/groups-table.js
  public/controllers/management/components/management/groups/utils/groups-handler.js
  public/controllers/management/components/management/groups/utils/valid-configuration.js
Labels: error-handling

#3453 Fixed dispatch for updateCurrentAgentData
  public/components/common/welcome/components/agent-sections.ts
  public/components/common/welcome/components/menu-agent.js
Labels: 4.3, bug

#3427 Added try-catch strategy in Reporting section
  CHANGELOG.md
  public/controllers/management/components/management/reporting/__snapshots__/reporting-main.test.tsx.snap
  public/controllers/management/components/management/reporting/reporting-main.test.tsx
  public/controllers/management/components/management/reporting/reporting-table.js
  public/controllers/management/components/management/reporting/utils/actions-buttons-main.js
  public/controllers/management/components/management/reporting/utils/reporting-handler.js
Labels: FE:testing, error-handling

#3442 Implement/try catch in Components > Overview
  CHANGELOG.md
  public/components/overview/compliance-table/compliance-table.tsx
  public/components/overview/metrics/metrics.tsx
  public/components/overview/mitre/components/tactics/tactics.tsx
  public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/components/overview/mitre/mitre.tsx
  public/components/overview/mitre_attack_intelligence/resource.tsx
  public/components/overview/mitre_attack_intelligence/resource_detail_references_table.tsx
  public/components/overview/mitre_attack_intelligence/resources.tsx
Labels: FE:testing, error-handling

#3429 Refactor try catch in Management > Statistics
  CHANGELOG.md
  package.json
  public/controllers/management/components/management/statistics/statistics-main.test.tsx
  public/controllers/management/components/management/statistics/statistics-overview.js
  test/jest/config.js
Labels: FE:testing, error-handling

#3451 Refactor try catch in Management > Configuration
  CHANGELOG.md
  public/controllers/management/components/management/configuration/configuration-switch.js
  public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
  public/controllers/management/components/management/configuration/util-components/refresh-cluster-info-button.js
  public/controllers/management/components/management/configuration/util-hocs/loading.js
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
Labels: enhancement, error-handling

#3445 fix size api selector and add basic test
  CHANGELOG.md
  public/components/wz-menu/__snapshots__/wz-menu.test.tsx.snap
  public/components/wz-menu/wz-menu.js
  public/components/wz-menu/wz-menu.test.tsx
Labels: FE:testing

#3434 Refactor try catch in Management > Status
  CHANGELOG.md
  public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
  public/controllers/management/components/management/status/actions-buttons-main.js
  public/controllers/management/components/management/status/status-main.test.tsx
  public/controllers/management/components/management/status/status-overview.js
  public/controllers/management/components/management/status/utils/status-handler.js
Labels: FE:testing, FE:testingDone, error-handling

#3472 Refactor try-catch components/add-moludes-data
  CHANGELOG.md
  public/components/add-modules-data/sample-data.tsx
Labels: FE:testing, FE:testingDone, error-handling

#3412 Rule-test and Decoder-test flyouts click outside detector
  CHANGELOG.md
  public/components/agents/fim/inventory/registry-table.tsx
  public/components/agents/fim/inventory/table.tsx
  public/components/agents/vuls/inventory/table.tsx
  public/components/common/buttons/modal-confirm.tsx
  public/components/common/modules/discover/discover.tsx
  public/components/common/modules/events.tsx
  public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
  public/components/common/welcome/components/mitre_top/mitre_top.tsx
  public/components/notifications/modal.tsx
  public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
  public/components/overview/mitre/components/tactics/tactics.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/components/overview/mitre_attack_intelligence/resource_detail_flyout.tsx
  public/components/security/policies/create-policy.tsx
  public/components/security/policies/edit-policy.tsx
  public/components/security/policies/policies-table.tsx
  public/components/security/roles-mapping/components/roles-mapping-create.tsx
  public/components/security/roles-mapping/components/roles-mapping-edit.tsx
  public/components/security/roles/create-role.tsx
  public/components/security/roles/edit-role.tsx
  public/components/security/users/components/create-user.tsx
  public/components/security/users/components/edit-user.tsx
  public/components/security/users/users.tsx
  public/components/wz-agent-selector/wz-agent-selector.js
  public/controllers/management/components/management/configuration/util-components/configuration-path.js
  public/controllers/management/components/management/groups/groups-editor.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/controllers/overview/components/overview-actions/overview-actions.js
  public/directives/wz-logtest/components/logtest.tsx
Labels: FE:testing, enhancement

#3439 [Fix] Code overflows over the line numbers in API Console editor
  CHANGELOG.md
  public/utils/codemirror/codemirror.scss
Labels: bug

#3474 Refactor try-catch strategy on controllers, directives and factories
  public/controllers/dev-tools/dev-tools.ts
  public/controllers/misc/blank-screen-controller.js
  public/controllers/tools/index.ts
  public/controllers/tools/tools.ts
  public/directives/wz-logtest/components/logtest.tsx
  public/factories/vis2png.js
Labels: FE:testing, FE:testingDone, error-handling

#3440 [FIX] Don't open the main menu when changing the selected API or index pattern
  CHANGELOG.md
  public/components/wz-menu/wz-menu.js
Labels: FE:testing, bug

#3480 Added try-catch stratategy in common/tables
  CHANGELOG.md
  public/components/common/tables/__snapshots__/table-default.test.tsx.snap
  public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
  public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
  public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
  public/components/common/tables/components/export-table-csv.test.tsx
  public/components/common/tables/components/export-table-csv.tsx
  public/components/common/tables/table-default.test.tsx
  public/components/common/tables/table-default.tsx
  public/components/common/tables/table-with-search-bar.test.tsx
  public/components/common/tables/table-with-search-bar.tsx
  public/components/common/tables/table-wz-api.test.tsx
  public/components/common/tables/table-wz-api.tsx
Labels: FE:testing, FE:testingDone, error-handling

#3469 Refactor try catch strategy on controller/settings
  CHANGELOG.md
  public/controllers/settings/settings.js
Labels: FE:testingDone, error-handling

#3448 Implement try catch in Components > Wz files
  CHANGELOG.md
  public/components/wz-filter-bar/wz-filter-bar.js
  public/components/wz-menu/wz-menu-agent.js
  public/components/wz-menu/wz-menu.js
  public/components/wz-search-bar/lib/suggest-handler.ts
  public/components/wz-search-bar/wz-search-bar.tsx
Labels: FE:testing, FE:testingDone, error-handling

#3436 Implement try catch react-services
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
  public/controllers/agent/agents.js
  public/react-services/action-agents.js
  public/react-services/app-state.js
  public/react-services/check-daemons-status.js
  public/react-services/group-handler.js
  public/react-services/load-app-config.service.ts
  public/react-services/reporting.js
  public/react-services/saved-objects.js
  public/react-services/vis-factory-handler.js
  public/react-services/wz-agents.ts
  public/react-services/wz-authentication.ts
  public/react-services/wz-security-opendistro.test.js
  public/react-services/wz-security-xpack.test.js
Labels: FE:testing, FE:testingDone, error-handling

#3438 [Fix] Remove URL query param `redirectRule` on CDB Lists/Decoders
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/ruleset-table.js
Labels: bug

#3478 Implement/try catch in services
  CHANGELOG.md
  public/services/check-daemon-status.js
  public/services/common-data.js
  public/services/config-handler.js
  public/services/reporting.js
  public/services/resolves/api-count.js
  public/services/resolves/check-timestamp.js
  public/services/resolves/get-ip.js
  public/services/resolves/get-saved-search.js
  public/services/resolves/settings-wizard.js
Labels: FE:testing, FE:testingDone, error-handling

#3430 Notify when you are registering an agent without permissions
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: bug

#3443 fix error message in conf managment and add test
  CHANGELOG.md
  public/controllers/management/components/management/configuration/alerts/__snapshots__/alerts-configurations.test.tsx.snap
  public/controllers/management/components/management/configuration/alerts/alerts-configurations.test.tsx
  public/controllers/management/components/management/configuration/util-components/no-config.js
Labels: FE:testing, enhancement

#3458 [FIX] Index pattern selector doesn't display the ignored index patterns
  CHANGELOG.md
  public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
  public/components/wz-menu/wz-menu.js
Labels: bug

#3475 Added Sample Data Component
  CHANGELOG.md
  public/components/visualize/components/index.ts
  public/components/visualize/components/sample-data-warning.js
  public/components/visualize/components/sample-data-warning.test.js
  public/components/visualize/wz-visualize.js
Labels: enhancement
