Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-11, with the labels that each got.

#3674 Fixing EuiPannels in Overview Sections and disabled text in WzMenu
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
  public/components/common/welcome/management-welcome.js
  public/components/common/welcome/overview-welcome.js
  public/components/wz-menu/wz-menu-management.js
  public/components/wz-menu/wz-menu-settings.js
  public/controllers/agent/components/agents-preview.js
Labels: bug

#3676 Fix/3673 fixing double flyout clicking in a policy
  CHANGELOG.md
  public/components/security/policies/policies-table.tsx
  public/components/security/policies/policies.tsx
Labels: bug

#3672 Fixed Group Configuration and Management configuration error after trying to going back after you save
  CHANGELOG.md
  public/components/security/users/components/edit-user.tsx
  public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
  public/controllers/management/components/management/groups/groups-editor.js
Labels: bug

#3488 Bug/3296 cdb list view not working with ipv6
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/list-editor.js
Labels: bug, 4.3, FE:testingDone

#3446 Test decoders before matching rules
  CHANGELOG.md
  public/directives/wz-logtest/components/logtest.tsx
  public/react-services/wz-request.ts
Labels: enhancement, 4.3, FE:testingDone

#3604 Removed api selector toggle from the settings menu
  CHANGELOG.md
  common/constants.ts
  public/components/settings/configuration/utils/configuration-handler.js
  public/react-services/app-state.js
  public/react-services/wz-api-check.js
  public/services/resolves/get-config.js
  public/utils/config-equivalences.js
Labels: 4.3, FE:testingDone

#3466 Wrong active-response endpoint parameter from dev tools
  CHANGELOG.md
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/controllers/dev-tools/dev-tools.ts
  public/react-services/wz-request.ts
  server/controllers/wazuh-api.ts
Labels: bug, 4.3, FE:testing, FE:testingDone

#3605 Disable apply button at initial state and move agents to their original position
  CHANGELOG.md
  common/api-info/endpoints.json
  public/components/add-modules-data/sample-data.tsx
  public/components/common/hooks/use-filter-manager.ts
  public/components/management/groups/multiple-agent-selector.tsx
  public/components/security/roles-mapping/roles-mapping.tsx
  public/components/security/roles/services/get-roles.service.ts
  public/components/security/users/services/get-users.service.ts
  public/controllers/management/components/management/configuration/configuration-switch.js
  public/controllers/management/components/management/groups/groups-main.js
  public/controllers/management/components/management/management-main.js
  public/controllers/management/components/management/management-provider.js
  public/controllers/management/components/management/status/status-overview.js
  public/controllers/management/management.js
  public/kibana-services.ts
  public/react-services/toast-notifications.tsx
  public/react-services/wz-request.ts
Labels: bug, 4.3, FE:testingDone

#3639 Apply enhance #3622 -> Add filter bar on Network ports table
  CHANGELOG.md
  public/components/agents/syscollector/inventory.tsx
Labels: 4.3, FE:testingDone

#3651 Wazuh app not showing packages details in free bsd agent
  CHANGELOG.md
  public/components/agents/syscollector/columns/packages-columns.ts
  public/components/agents/syscollector/columns/ports-columns.ts
  public/components/agents/syscollector/columns/process-columns.ts
  public/components/agents/syscollector/inventory.tsx
Labels: bug, 4.3, FE:testingDone

#3652 Delete wazuh token called twice
  CHANGELOG.md
  public/app.js
Labels: 4.3, FE:testing, FE:testingDone

#3681 [FIX] [Compatibility] Get the valid index patterns to use in the app in Kibana 7.10.2 - 7.13.4
  CHANGELOG.md
  common/semver.ts
  public/components/common/modules/events.tsx
  public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
  public/components/health-check/services/check-index-pattern/check-index-pattern.service.ts
  public/components/health-check/services/check-pattern-support.service.ts
  public/components/visualize/wz-visualize.js
  public/react-services/pattern-handler.js
  public/react-services/saved-objects.js
Labels: enhancement

#3525 Added new fields in Inventory table and Flyout Details
  CHANGELOG.md
  public/components/agents/vuls/inventory/detail.tsx
  public/components/agents/vuls/inventory/flyout.tsx
  public/components/agents/vuls/inventory/table.tsx
Labels: FE:testing, FE:testingDone

#3649 change format permissions in FIM inventory
  CHANGELOG.md
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/agents/fim/inventory/table.tsx
  public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
  public/styles/inventory.scss
Labels: enhancement, 4.3, FE:testing, FE:testingDone

#3700 Fixing blank screen before Health-Check
  CHANGELOG.md
  public/services/resolves/api-count.js
Labels: bug, 4.3

#3692 Fixing error that shows we're using X-Pack when we have Basic
  CHANGELOG.md
  server/controllers/wazuh-api.ts
  server/lib/security-factory/security-factory.ts
  server/plugin.ts
Labels: bug, 4.3

#3689 Add id when agent is not pinned
  CHANGELOG.md
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/agents/fim/inventory/registryValues/registryValues.tsx
Labels: bug, 4.3

#3675 Add missing mitre tactics
  CHANGELOG.md
  public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
Labels: enhancement, 4.3

#3663 Updated deprecated and new references authd
  CHANGELOG.md
  common/api-info/endpoints.json
  common/api-info/security-actions.json
  public/controllers/management/components/management/configuration/registration-service/registration-service.js
  server/lib/api-request-list.json
Labels: 4.3

#3645 Multi-select component searcher handler
  CHANGELOG.md
  public/components/common/custom-search-bar/components/multi-select.tsx
Labels: 4.3

#3661 [Wazuh API] Fix the requests `GET //`
  CHANGELOG.md
  public/components/common/welcome/agents-info.js
  public/components/health-check/services/check-setup.service.ts
  public/components/wz-menu/components/wz-agent-info.js
  public/controllers/agent/agents-preview.js
  public/controllers/agent/components/agents-table.js
  public/controllers/management/monitoring.js
  server/controllers/wazuh-api.ts
  server/controllers/wazuh-utils/wazuh-utils.ts
Labels: bug, 4.3

#3561 Office 365 module
  CHANGELOG.md
  public/components/common/modules/panel/main-panel.tsx
Labels: 4.3

#3459 [FIX] Error opening rule file in Related rules of rule detail information
  public/controllers/management/components/management/ruleset/rule-info.js
Labels: bug, 4.3

#3554 Error in management configuration
  CHANGELOG.md
Labels: bug, 4.3
