Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-12, with the labels that each got.

#3691 Feature/3627 be able select columns in agents
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.scss
  public/controllers/agent/components/agents-table.js
Labels: 4.3

#3704 Related decoder link undefined parameters error
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/decoder-info.js
Labels: 4.3

#3724 Fixing bug when create filename with spaces and throws a bad error
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/ruleset-editor.js
Labels: 4.3

#3709 [FIX] [TELEMETRY] Hide the banner
  CHANGELOG.md
  kibana.json
  public/plugin.ts
  public/types.ts
Labels: enhancement

#3698 [FIX] [HEALH CHECK] Fix `listValidIndexPatterns.find is not a function` error
  CHANGELOG.md
  public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
  public/controllers/settings/settings.js
  public/react-services/saved-objects.js
Labels: bug

#3710 fix wrong deamons in filter list
  CHANGELOG.md
  public/controllers/management/components/management/mg-logs/logs.js
Labels: 4.3

#3732 add target blank in link table
  CHANGELOG.md
  package.json
  public/components/common/util/markdown/markdown.tsx
Labels: 4.3

#3731 Bugfix/3719 security user nonexistant unsubmitted changes warn
  CHANGELOG.md
  public/components/security/users/components/edit-user.tsx
Labels: 4.3

#3722 [Panel] [Office365] [GitHub] Update data when clearing the query filter
  CHANGELOG.md
  public/components/common/hooks/use-es-search.ts
Labels: bug

#3728 [FIX] [Monitoring] Retrieve data of all agents
  CHANGELOG.md
  server/start/monitoring/index.ts
Labels: bug

#3737 [FIX] Missing settings in `Management/Configuration/Global configuration/Global/Main settings`
  CHANGELOG.md
  public/controllers/management/components/management/configuration/global-configuration/global-configuration-global.js
Labels: bug, 4.3

#3738 [FIX] `Maximum call stack size exceeded` error exporting key-value pairs of a CDB List
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/list-editor.js
Labels: bug, 4.3

#3733 [FIX] [Styles] Fix filter button styles of Inventory and height `Evolution` card with no data
  CHANGELOG.md
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/agents/vuls/inventory/detail.tsx
  public/controllers/agent/components/agents-preview.js
  public/styles/dark_theme/wz_theme_dark.scss
  public/styles/inventory.scss
Labels: bug, 4.3

#3708 Fixing Flyouts in Kibana 7.14.2
  CHANGELOG.md
  public/components/agents/fim/inventory/flyout.tsx
  public/components/agents/fim/inventory/registry-table.tsx
  public/components/agents/fim/inventory/table.tsx
  public/components/agents/vuls/inventory/table.tsx
  public/components/common/flyouts/index.ts
  public/components/common/flyouts/wz-flyout.tsx
  public/components/common/modules/discover/discover.tsx
  public/components/common/modules/events.tsx
  public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
  public/components/common/welcome/components/mitre_top/mitre_top.tsx
  public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx
  public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
  public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/components/overview/mitre_attack_intelligence/resource_detail_flyout.tsx
  public/components/security/policies/create-policy.tsx
  public/components/security/policies/edit-policy.tsx
  public/components/security/roles-mapping/components/roles-mapping-create.tsx
  public/components/security/roles-mapping/components/roles-mapping-edit.tsx
  public/components/security/roles/create-role.tsx
  public/components/security/roles/edit-role.tsx
  public/components/security/users/components/create-user.tsx
  public/components/security/users/components/edit-user.tsx
  public/directives/wz-logtest/components/logtest.tsx
Labels: bug, 4.3

#3741 fix regex lookahead and lookbehind for safari
  CHANGELOG.md
  public/components/common/custom-search-bar/components/multi-select.tsx
Labels: bug

#3742 Added workflow wazuh package
  .github/workflows/create-wazuh-packages.yml
  CHANGELOG.md
Labels: enhancement

#3744 Added filters to Vulnerabilities - Inventory flyout details
  CHANGELOG.md
  public/components/agents/fim/inventory.tsx
  public/components/agents/vuls/inventory.tsx
  public/components/agents/vuls/inventory/detail.tsx
  public/components/agents/vuls/inventory/table.tsx
  public/components/common/tables/table-wz-api.tsx
Labels: 4.3

#3657 Columns are added to the report
  server/integration-files/visualizations/overview/overview-vuls.ts
  server/lib/reporting/printer.ts
Labels: enhancement, operations, 4.3
