Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-03, with the labels that each got.

#3007 Fix SCA selection policy showing information about another policy
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
Labels: bug

#3018 Fix pagination in SCA checks table when expanding some row
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
Labels: bug

#3013 Checking if data is loaded before show button for create role mapping
  CHANGELOG.md
  public/components/security/policies/policies.tsx
  public/components/security/roles-mapping/roles-mapping.tsx
  public/components/security/roles/roles.tsx
  public/components/security/users/users.tsx
  tsconfig.json
Labels: bug

#3021 Add run_as setting to Add new API view
  CHANGELOG.md
  public/components/settings/api/add-api.js
Labels: bug, enhancement

#3038 Overlay Wazuh menu to Kibana menu when is opened or docked
  CHANGELOG.md
  public/components/wz-menu/wz-menu.js
  public/components/wz-menu/wz-menu.scss
Labels: enhancement

#3035 Bugfix pinned agent framework mitre
  CHANGELOG.md
  public/components/overview/mitre/mitre.tsx
Labels: bug

#2985 Feature/2826 create index pattern configuration
  CHANGELOG.md
  common/constants.ts
  public/components/settings/configuration/components/bottom-bar.tsx
  public/components/settings/configuration/configuration.tsx
  public/components/wz-menu/wz-menu.js
  public/react-services/pattern-handler.js
  public/services/resolves/get-ip.js
  server/lib/update-configuration.ts
Labels: enhancement

#3049 Improve toast message when select default API
  CHANGELOG.md
  public/controllers/settings/settings.js
Labels: enhancement

#3062 Fixing bug changing master node configuration
  CHANGELOG.md
  public/components/health-check/health-check.tsx
  public/components/wz-menu/wz-menu.js
Labels: bug

#3047 Change all date formats
  CHANGELOG.md
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/agents/fim/inventory/table.tsx
  public/components/agents/sca/inventory.tsx
  public/components/agents/syscollector/components/syscollector-metrics.tsx
  public/components/common/modules/discover/discover.tsx
  public/components/common/welcome/agents-info.js
  public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
  public/components/common/welcome/components/sca_scan/sca_scan.tsx
  public/components/settings/settings-logs/logs.js
  public/components/wz-date-picker/components/condensed.tsx
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-table.js
  public/controllers/management/components/management/mg-logs/logs.js
  public/controllers/management/components/management/reporting/utils/columns-main.js
  public/controllers/management/components/management/ruleset/ruleset-filter-bar.js
  public/controllers/management/components/management/status/status-agent-info.js
  public/controllers/management/components/management/status/status-node-info.js
  public/controllers/overview/components/select-agent.js
  public/controllers/settings/settings.js
  public/react-services/time-service.js
Labels: enhancement

#3087 fix(frontend): Fix infinite loading user logging in status
  public/react-services/wz-authentication.ts
Labels: bug

#3086 Fix/events table
  CHANGELOG.md
  public/components/common/modules/events-enhance-discover-fields.ts
  public/components/common/modules/events.tsx
Labels: bug

#3048 Added custom message for each possible run_as setup
  CHANGELOG.md
  public/components/security/main.tsx
  public/components/settings/api/api-table.js
  server/controllers/wazuh-api.ts
  server/lib/cache-api-user-has-run-as.ts
Labels: enhancement

#3083 Bugfix report dark mode
  CHANGELOG.md
  kibana.json
  public/components/common/modules/main.tsx
  public/controllers/agent/components/register-agent.js
  public/templates/visualize/dashboards.html
Labels: 4.2

#3089 Change api selected as default message
  public/controllers/settings/settings.js
Labels: enhancement

#3090 withUserLogged missing in some files
  public/components/common/hocs/withUserAuthorization.tsx
  public/components/common/modules/main-mitre.tsx
  public/components/common/welcome/components/sca_scan/sca_scan.tsx
  public/components/security/main.tsx
  public/controllers/management/components/management/configuration/configuration-switch.js
  public/controllers/management/components/management/groups/group-detail.js
  public/controllers/management/components/management/groups/groups-overview.js
  public/controllers/management/components/management/ruleset/ruleset-overview.js
  public/controllers/management/components/management/status/status-overview.js
Labels: bug

#3091 Clear browser cache
  CHANGELOG.md
  public/assets/meta.json
  public/utils/check-plugin-version.ts
  scripts/generate-build-version.js
Labels: enhancement
