Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-01, with the labels that each got.

#2717 Fixed error due to new use of path in the export of lists
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/list-editor.js
Labels: bug

#2748 4.0 7.10 adapt reports new endpoints
  public/controllers/management/components/files-group-table.js
  public/controllers/management/components/management/configuration/configuration-overview.js
  public/controllers/management/components/management/groups/actions-buttons-agents.js
  public/controllers/management/components/management/groups/actions-buttons-files.js
  public/controllers/management/components/management/reporting/reporting-table.js
  public/controllers/management/groups.js
  public/react-services/reporting.js
  server/controllers/wazuh-reporting.ts
  server/reporting/syscheck-request.ts
  server/routes/wazuh-reporting.ts
Labels: newPlatform, np/browser-side, np/server-side

#2749 Fix ApiInterceptor.buildRequestOptions to destructurate data parameters
  server/lib/api-interceptor.ts
Labels: newPlatform, np/server-side

#2763 4.0-7.10 Fix Management/Statistics visualizations
  server/controllers/wazuh-elastic.ts
  server/integration-files/visualizations/cluster/statistics.js
Labels: newPlatform, np/browser-side

#2760 4.0-7.10 Adapt Open Distro 1.12
  kibana.json
  public/components/security/roles-mapping/roles-mapping.tsx
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  server/controllers/wazuh-api.ts
  server/controllers/wazuh-elastic.ts
  server/lib/security-factory/factories/default-factory.ts
  server/lib/security-factory/factories/opendistro-factory.ts
  server/lib/security-factory/factories/xpack-factory.ts
  server/lib/security-factory/security-factory.ts
  server/start/initialize.ts
  server/types.ts
  util/constants.ts
Labels: newPlatform, np/browser-side, np/server-side

#2769 Changed the way index pattern are refreshed
  public/react-services/pattern-handler.js
Labels: newPlatform, np/browser-side

#2770 Fixed content-type on header for request.
  server/controllers/wazuh-api.ts
Labels: enhancement, newPlatform

#2778 Add Queue job to backend
  server/controllers/error-response.old.js
  server/controllers/error-response.ts
  server/controllers/wazuh-api.ts
  server/initialize.old.js
  server/jobs/queue.old.js
  server/jobs/queue.test.ts
  server/jobs/queue.ts
  server/lib/cron-scheduler/save-document.ts
  server/lib/default-ext.ts
  server/lib/get-configuration.ts
  server/lib/index-date.ts
  server/lib/initial-wazuh-config.ts
  server/lib/manage-hosts.ts
  server/lib/update-configuration.ts
  server/lib/update-registry.ts
  server/logger.ts
  server/monitoring.old.js
  server/plugin.ts
  server/reporting/audit-request.ts
  server/reporting/base-query.ts
  server/reporting/clock-icon-raw.ts
  server/reporting/filter-icon-raw.ts
  server/reporting/gdpr-request.ts
  server/reporting/overview-request.ts
  server/reporting/pci-request.ts
  server/reporting/rootcheck-request.ts
  server/reporting/syscheck-request.ts
  server/reporting/tsc-request.ts
  server/reporting/vulnerability-request.ts
  server/start/initialize.ts
  util/api-errors-equivalence.ts
  util/constants.ts
  util/csv-key-equivalence.ts
  util/excluded-devtools-autocomplete-keys.ts
  util/get-path.ts
  util/process-state-equivalence.ts
  util/remove-key.ts
Labels: newPlatform, np/server-side

#2759 Fix bughunt in Management
  public/components/security/roles-mapping/components/rule-editor.tsx
  public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
  public/components/tools/devtools/devToolsHistory.tsx
  public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
  public/controllers/management/components/management/configuration/util-components/code-editor.js
  public/controllers/management/components/management/groups/groups-editor.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/services/routes.js
Labels: enhancement, newPlatform

#2780 Check monitoring and statistics index patterns
  public/components/health-check/health-check.tsx
  public/react-services/saved-objects.js
  public/services/resolves/get-ip.js
  server/controllers/wazuh-elastic.ts
  server/lib/cron-scheduler/save-document.ts
Labels: np/browser-side

#2774 Fixed unsopported components of solaris
  CHANGELOG.md
  public/utils/components-os-support.js
Labels: newPlatform, np/browser-side

#2784 Fix the report's creation date
  CHANGELOG.md
  server/controllers/wazuh-reporting.ts
Labels: back-end

#2794 4.0-7.10 - Fix calls to undefined method ErrorHandler.error
  public/components/security/roles-mapping/components/roles-mapping-table.tsx
  public/components/security/users/components/users-table.tsx
Labels: bug

#2787 Fixed/error pattern selector
  common/constants.ts
  public/components/health-check/health-check.tsx
  public/react-services/saved-objects.js
  public/utils/known-fields.js
  public/utils/monitoring-fields.ts
  public/utils/statistics-fields.ts
Labels: newPlatform, np/browser-side

#2796 4.0-7.10 - Add a Kibana log when the <KIBANA_PATH>/data directory is missing
  common/constants.ts
  server/start/initialize/index.ts
Labels: enhancement

#2797 Features/fix error timestamp security events
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
Labels: bug

#2799 4.0-7.10 - Fix imports of index type constants in saved-objects.js
  public/react-services/saved-objects.js
Labels: bug

#2798 4.0-7.10 capture the ENOENT error due to the data directory is missing in the /host/apis endpoint
  server/controllers/wazuh-hosts.ts
  server/start/initialize/index.ts
Labels: enhancement

#2843 Bugfix/2840 search file editor gone
  public/components/security/roles-mapping/components/rule-editor.tsx
  public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
  public/components/tools/devtools/devToolsHistory.tsx
  public/controllers/dev-tools/components/test-configuration.js
  public/controllers/management/components/management/configuration/util-components/code-editor.js
  public/controllers/management/components/management/groups/groups-editor.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
Labels: bug

#2815 4.0-7.10 Fix the pagination in SCA ckecks table
  public/components/agents/sca/inventory.tsx
Labels: bug

#2830 4.0-7.10 - Fix metrics are not updated after a bad request in search input
  public/components/overview/metrics/metrics.tsx
Labels: bug

#2846 Features/fixed bug with agent filter when it is pinned
  public/controllers/overview/overview.js
Labels: 4.0.4-7.10.0, bug

#2850 Features/fixed tooltip in the icon of view decoder file
  public/controllers/management/components/management/ruleset/utils/columns.js
Labels: 4.0.4-7.10.0, bug

#2825 fix(frontend): Fix searching in groups
  public/controllers/management/components/management/groups/groups-table.js
Labels: bug

#2853 Fixed bug in the table on Agents->Table-> Actions->Config icon
  public/controllers/agent/components/agents-table.js
Labels: 4.0.4-7.10.0, bug

#2828 4.0-7.10 - Update agents' info in Management Status after changing cluster node selected
  public/controllers/management/components/management/status/actions-buttons-main.js
Labels: bug

#2854 4.0-7.10 - Fix the SCA table with a wrong behaviour using the refresh button
  public/components/agents/sca/inventory.tsx
Labels: bug

#2858 4.0-7.10 - Fix the settings of statistics indices creation
  common/constants.ts
  init.js
  server/lib/cron-scheduler/apiRequest.ts
  server/lib/cron-scheduler/configured-jobs.ts
  server/lib/cron-scheduler/error-handler.ts
  server/lib/cron-scheduler/index.ts
  server/lib/cron-scheduler/predefined-jobs.ts
  server/lib/cron-scheduler/save-document.test.ts
  server/lib/cron-scheduler/save-document.ts
  server/lib/cron-scheduler/scheduler-handler.ts
  server/lib/cron-scheduler/scheduler-job.test.ts
  server/lib/cron-scheduler/scheduler-job.ts
  server/lib/cron-scheduler/types/api.ts
  server/start/cron-scheduler/save-document.ts
Labels: bug

#2861 Fixed bug in sca and regulatory compliance tables and in wz menu on f…
  public/components/overview/compliance-table/compliance-table.tsx
  public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
  public/components/overview/mitre/components/techniques/techniques.tsx
  public/components/overview/mitre/mitre.tsx
  public/components/wz-menu/wz-menu.scss
Labels: 4.0.4-7.10.0, bug

#2860 fix: Changed the Wazuh API default user to `wazuh-wui`
  CHANGELOG.md
  public/components/settings/api/api-is-down.js
  server/lib/initial-wazuh-config.ts
Labels: enhancement

#2865 Fixed css of layouts because of conflicts with kibana flyouts
  public/components/agents/fim/inventory/flyout.tsx
  public/components/common/modules/module.scss
  public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx
  public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
  public/components/security/policies/edit-policy.tsx
  public/components/security/policies/policies.tsx
  public/components/security/roles-mapping/components/roles-mapping-create.tsx
  public/components/security/roles-mapping/components/roles-mapping-edit.tsx
  public/components/security/roles/create-role.tsx
  public/components/security/roles/edit-role.tsx
  public/components/security/users/components/create-user.tsx
  public/components/security/users/components/edit-user.tsx
  public/controllers/overview/components/select-agent.js
Labels: 4.0.4-7.10.0, bug
