Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-08, with the labels that each got.

#3528 Fix/office agent
  server/lib/generate-alerts/generate-alerts-script.js
Labels: 4.3

#3531 Integrating dynamic filters
  CHANGELOG.md
  public/components/common/custom-search-bar/custom-search-bar.tsx
  public/components/common/hooks/use-kbn-loading-indicator.ts
  public/components/common/hooks/use-value-suggestions.ts
  public/components/overview/github-panel/config/search-bar-config.ts
Labels: enhancement

#3492 [Fix] Temporal fix to rendered correct Mitre section
  CHANGELOG.md
  public/components/overview/mitre/components/techniques/techniques.tsx
Labels: bug

#3541 [Module] [Office365] [Panel] Add the view for the module configuration
  public/components/common/hooks/use_async_action.ts
  public/components/common/modules/panel/components/index.ts
  public/components/common/modules/panel/components/module_configuration.scss
  public/components/common/modules/panel/components/module_configuration.tsx
  public/components/overview/office-panel/office-panel.tsx
  public/components/overview/office-panel/views/index.ts
  public/components/overview/office-panel/views/office-stats.scss
  public/components/overview/office-panel/views/office-stats.tsx
Labels: enhancement

#3560 [Module] [Office365] Add `rule.level` and `rule.id` fields to alerts table of each drill down view
  public/components/overview/office-panel/config/drilldown-ip-config.tsx
  public/components/overview/office-panel/config/drilldown-operations-config.tsx
  public/components/overview/office-panel/config/drilldown-rules-config.tsx
  public/components/overview/office-panel/config/drilldown-user-config.tsx
Labels: enhancement

#3556 [OFFICE MODULE] Dashboard errors with pinned agent
  public/components/agents/prompts/prompt_module_not_for_agent.tsx
  public/components/common/hocs/index.ts
  public/components/common/hocs/with_module_not_for_agent.tsx
  public/components/common/modules/modules-defaults.js
  public/components/common/welcome/agents-welcome.js
  public/controllers/overview/components/overview-actions/overview-actions.js
  public/controllers/overview/overview.js
  public/react-services/vis-factory-handler.js
  public/services/vis-factory-handler.js
  server/controllers/wazuh-elastic.ts
Labels: 4.3

#3569 Erasing windows update option in wrong cases
  CHANGELOG.md
  server/controllers/wazuh-reporting.ts
Labels: bug, 4.2

#3592 Added link to upgrade guide when Wazuh API version missmatch
  CHANGELOG.md
  public/components/health-check/components/check-result.tsx
  public/components/health-check/container/health-check.container.tsx
  public/components/health-check/services/check-setup.service.ts
Labels: enhancement
