Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-02, with the labels that each got.

#2873 Fixed bug in inventory of Windows Registry
  common/csv-key-equivalence.ts
  public/components/agents/fim/inventory.tsx
  public/components/agents/fim/inventory/filterBar.tsx
  public/components/agents/fim/inventory/flyout.tsx
  public/components/agents/fim/inventory/registry-table.tsx
  public/components/agents/sca/inventory.tsx
Labels: 4.1, bug

#2879 Bugfix filter event rules
  public/controllers/management/components/management/ruleset/main-ruleset.js
Labels: bug

#2903 [4.1-7.10] Fix the decoder details for keys as objects
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/decoder-info.js
Labels: 4.1.0-7.10.0, bug

#2894 Set secure cookies in SSL/TLS sessions
  server/controllers/wazuh-api.ts
  server/plugin.ts
Labels: 4.1.1, bug

#2930 Fix complex searches in WzSearchBar for query filter
  CHANGELOG.md
  public/components/wz-search-bar/lib/filters-to-object.ts
Labels: bug

#2941 [4.1-7.10] Allow access to agents section with agent:group permission
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
Labels: bug

#2935 Fixed bug in the filters of flyouts
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
Labels: 4.1.0-7.10.0, bug

#2876 Feature/add warning when configuring new role mapping
  public/components/security/main.tsx
  public/components/security/roles-mapping/components/rule-editor.tsx
Labels: enhancement

#2969 Add vulnerabilities module to macos agents
  CHANGELOG.md
  public/utils/components-os-support.js
Labels: enhancement

#2973 Stats in SCA policy stats didn't refresh
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
Labels: bug, enhancement

#2975 fix(frontend): Date format in FIM table and file/registry detail
  CHANGELOG.md
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/agents/fim/inventory/table.tsx
  public/components/agents/sca/inventory.tsx
Labels: enhancement

#2977 Bugfix, setting properly X-Frame-Options
  CHANGELOG.md
  server/plugin.ts
Labels: bug

#2976 Fix a non-stop error in Manage agents when the user has no permissions
  CHANGELOG.md
  public/components/management/groups/multiple-agent-selector.tsx
  public/controllers/management/components/management/groups/actions-buttons-agents.js
  public/controllers/management/components/management/groups/group-detail.js
Labels: bug, enhancement

#2956 Fixed that alerts table is empty when switching pinned agents
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
Labels: bug

#2980 Fix the unpin button in agent selection modal
  CHANGELOG.md
  public/controllers/overview/components/overview-actions/agents-selection-table.js
Labels: bug

#2964 Fix/wrong number of alerts
  CHANGELOG.md
  public/components/visualize/wz-visualize.js
Labels: bug

#2959 Fix main and "More" menus and add prompt to modules for unsupported agents
  CHANGELOG.md
  common/constants.ts
  public/components/agents/prompt-agent-no-support-module.tsx
  public/components/common/hocs/index.ts
  public/components/common/hocs/withAgentSupportModule.tsx
  public/components/common/modules/main-agent.tsx
  public/components/common/modules/main-overview.tsx
  public/components/common/welcome/agents-welcome.js
  public/components/common/welcome/components/menu-agent.js
  public/components/wz-menu/wz-menu-agent.js
  public/components/wz-menu/wz-menu-overview.js
  public/controllers/agent/agents.js
  public/controllers/management/components/management/configuration/configuration-settings.js
  public/controllers/management/components/management/configuration/utils/wz-utils.js
  public/react-services/wz-agents.ts
  public/utils/components-os-support.js
Labels: bug, enhancement

#2979 Support alerts index pattern with different ID and title
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
  public/controllers/agent/agents-preview.js
  public/controllers/management/components/management/statistics/hooks/use-build-statistics-visualizations.ts
  public/controllers/management/monitoring.js
  public/react-services/generic-request.js
  server/controllers/wazuh-elastic.ts
Labels: bug, enhancement

#2987 Generate security actions file with API info script
  common/api-info/endpoints.json
  common/api-info/security-actions.json
  package.json
  public/react-services/wz-user-permissions.ts
  scripts/generate-api-4.0-info/generate-api-4.0-info.js
  scripts/generate-api-4.0-info/generate-api-4.0-info.sh
  server/controllers/wazuh-api.ts
Labels: enhancement

#2961 Bugfix/2887 null pointer in filter wrong type
  CHANGELOG.md
  public/kibana-integrations/kibana-discover.js
Labels: enhancement

#2974 Added toast with a refresh button
  CHANGELOG.md
  public/components/visualize/wz-visualize.js
  public/kibana-integrations/kibana-vis.js
  public/react-services/pattern-handler.js
  public/react-services/saved-objects.js
  public/utils/known-fields.js
Labels: enhancement

#2710 fix route in getCurrentUser when AWS Elasticsearch is used
  server/lib/security-factory/factories/opendistro-factory.ts
Labels: bug, community

#2972 Bugfix delete old token
  CHANGELOG.md
  public/app.js
  public/react-services/wz-authentication.ts
Labels: enhancement

#2989 fix missing && from macOS agent deployment command
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: operations

#3012 Bugfix logout remove token x pack
  CHANGELOG.md
  public/app.js
Labels: enhancement

#3020 Registry_values aren't not displayed for Windows agents
  public/components/agents/fim/inventory/flyout.tsx
  public/components/agents/fim/inventory/registryValues/registryValues.tsx
Labels: bug
