Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2021-04, with the labels that each got.

#3051 Add restart callout manager/cluster button when importing a file in Rule, Decoders and CDB List
  CHANGELOG.md
  public/components/common/restart-cluster-manager-callout.tsx
  public/controllers/management/components/management/ruleset/actions-buttons.js
  public/controllers/management/components/management/ruleset/list-editor.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/controllers/management/components/management/ruleset/ruleset-overview.js
  public/controllers/management/components/upload-files.js
Labels: enhancement

#3077 Added logtest example on devtools.
  CHANGELOG.md
  public/controllers/dev-tools/dev-tools.js
Labels: 4.2, enhancement

#3055 Feature add new dev tools
  CHANGELOG.md
  common/api-info/endpoints.json
  public/components/eui-loader.js
  public/components/wz-menu/wz-menu-tools.js
  public/components/wz-menu/wz-menu.js
  public/controllers/dev-tools/dev-tools.ts
  public/controllers/index.ts
  public/controllers/management/components/management/management-main.js
  public/controllers/management/components/management/ruleset/main-ruleset.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/controllers/management/management.js
  public/controllers/tools/index.ts
  public/controllers/tools/tools.ts
  public/directives/wz-logtest/components/logtest.js
  public/directives/wz-logtest/components/logtest.tsx
  public/redux/actions/appStateActions.js
  public/redux/reducers/rootReducers.js
  public/redux/reducers/toolsReducers.js
  public/styles/common.scss
  public/templates/management/management.html
  public/templates/tools/dev-tools.html
  public/templates/tools/tools.html
Labels: 4.2

#3105 Added page size options in Security events, explore agents
  CHANGELOG.md
  public/components/common/modules/main.tsx
  public/controllers/overview/components/overview-actions/agents-selection-table.js
Labels: enhancement

#3046 Rename Ossec to Wazuh
  CHANGELOG.md
  common/api-info/endpoints.json
  public/controllers/agent/components/register-agent.js
  public/controllers/management/components/management/configuration/global-configuration/global-configuration-remote.js
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  server/controllers/wazuh-api.ts
  server/lib/api-request-list.json
Labels: 4.2

#2696 Daemons names updated
  common/api-info/endpoints.json
  common/api-info/security-actions.json
  server/lib/api-request-list.json
Labels: enhancement

#3088 Applied authorized agents filter in Agent stats and visualizations
  CHANGELOG.md
  public/app.js
  public/controllers/agent/agents-preview.js
  public/kibana-integrations/kibana-vis.js
  public/react-services/wz-agents.ts
  public/react-services/wz-authentication.ts
  public/redux/actions/appStateActions.js
  public/redux/reducers/appStateReducers.js
  server/controllers/wazuh-elastic.ts
  server/routes/wazuh-elastic.ts
Labels: enhancement

#3080 changed allow_run_as way of editing
  CHANGELOG.md
  public/components/common/permissions/button.tsx
  public/components/security/users/components/create-user.tsx
  public/components/security/users/components/edit-user.tsx
  public/components/security/users/services/index.ts
  public/components/security/users/services/update-allow-run-as.service.ts
  public/components/security/users/types/user.type.ts
Labels: 4.2

#3069 Feature/vulnerabilities view that affect each agent
  public/components/agents/vuls/index.ts
  public/components/agents/vuls/inventory.tsx
  public/components/agents/vuls/inventory/detail.tsx
  public/components/agents/vuls/inventory/filterBar.tsx
  public/components/agents/vuls/inventory/flyout.tsx
  public/components/agents/vuls/inventory/index.ts
  public/components/agents/vuls/inventory/lib/getFilterValues.ts
  public/components/agents/vuls/inventory/lib/index.ts
  public/components/agents/vuls/inventory/table.tsx
  public/components/agents/vuls/main.tsx
  public/components/common/modules/main-overview.tsx
  public/components/common/modules/modules-defaults.js
  scripts/generate-api-4.0-info/generate-api-4.0-info.js
  scripts/generate-api-4.0-info/generate-api-4.0-info.sh
  scripts/jest.js
Labels: 4.2

#3120 Alerts table and events with allowed agents only
  CHANGELOG.md
  common/constants.ts
  kibana.json
  public/components/common/hocs/withAllowedAgents.tsx
  public/components/common/hooks/index.ts
  public/components/common/hooks/useAllowedAgents.ts
  public/components/common/modules/discover/discover.tsx
  public/components/kbn-search-bar/kbn-search-bar.tsx
  public/components/overview/metrics/metrics.tsx
  public/components/visualize/components/security-alerts.tsx
  public/components/visualize/wz-visualize.js
  public/components/wz-search-bar/wz-search-badges.tsx
  public/kibana-integrations/discover/build_services.ts
  public/kibana-integrations/kibana-discover.js
  public/kibana-integrations/kibana-vis.js
  public/react-services/filter-authorization-agents.ts
  public/react-services/wz-agents.ts
  public/react-services/wz-authentication.test.ts
  public/react-services/wz-authentication.ts
  public/redux/actions/appStateActions.js
  public/utils/check-plugin-version.ts
  server/controllers/wazuh-reporting.ts
  server/lib/reporting/printer.ts
Labels: enhancement

#3111 Added statistics discover template
  CHANGELOG.md
  common/constants.ts
  public/utils/statistics-fields.ts
  server/controllers/wazuh-elastic.ts
  server/integration-files/statistics-template.ts
  server/integration-files/visualizations/cluster/statistics.ts
  server/start/cron-scheduler/predefined-jobs.ts
  server/start/cron-scheduler/save-document.ts
  server/start/cron-scheduler/scheduler-handler.ts
Labels: enhancement

#3143 Fixing overwriten lines
  public/components/common/modules/discover/discover.tsx
Labels: bug

#3140 Fixed problems with permissions in Rules, Decoders and Groups
  common/api-info/security-actions.json
Labels: bug

#3145 Fix not retrying the API connection in the healthcheck
  public/components/health-check/health-check.tsx
Labels: bug

#3144 Fix the plugin logo path in Kibana menu
  CHANGELOG.md
  public/plugin.ts
Labels: bug

#3126 add link to documentation "Checking connection with Manager"
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: enhancement

#3155 Add permissions control to Logtest
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/directives/wz-logtest/components/logtest.tsx
Labels: enhancement

#3167 Fixing when most active agent doesn't apper
  server/controllers/wazuh-elastic.ts
Labels: bug

#3102 Rename ossec.conf
  common/api-info/endpoints.json
  public/components/add-modules-data/guides/fim.js
  public/components/add-modules-data/module-guide.js
  public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  public/services/config-handler.js
  server/lib/api-request-list.json
Labels: 5.0

#3121 Changed ossec to wazuh in sample data
  CHANGELOG.md
  server/lib/generate-alerts/sample-data/common.js
  server/lib/generate-alerts/sample-data/integrity-monitoring.js
  server/lib/generate-alerts/sample-data/mitre.js
  server/lib/generate-alerts/sample-data/policy-monitoring.js
Labels: 4.3

#3160 Feature/remove module titles
  CHANGELOG.md
  public/components/common/modules/main-overview.tsx
Labels: UI/UX, enhancement

#3161 Fix the broken links when using server.basePath Kibana setting
  CHANGELOG.md
  public/components/add-modules-data/add-modules-data-main.tsx
  public/components/common/modules/overview-current-section.tsx
  public/components/health-check/health-check.tsx
  public/controllers/management/components/management/configuration/configuration-main.js
  public/controllers/management/components/management/groups/groups-main.js
  public/controllers/management/components/management/mg-logs/logs.js
  public/controllers/management/components/management/reporting/reporting-main.js
  public/controllers/management/components/management/ruleset/ruleset-overview.js
  public/controllers/management/components/management/statistics/statistics-overview.js
  public/controllers/management/components/management/status/status-overview.js
  public/controllers/management/monitoring.js
  public/react-services/generic-request.js
  public/react-services/pattern-handler.js
  public/react-services/wz-request.ts
Labels: bug

#3168 feat(prettier): Added prettierrc config file.
  .prettierrc
Labels: enhancement

#3173 Fixing filter in reports
  CHANGELOG.md
  server/controllers/wazuh-reporting.ts
Labels: bug

#3159 Fixed screen flickers in Cluster Visualization
  CHANGELOG.md
  public/controllers/management/management.js
  public/styles/common.scss
  public/templates/management/management.html
Labels: bug

#3174 Modify the default settings related to monitoring indices creation
  CHANGELOG.md
  common/constants.ts
  public/services/resolves/get-config.js
  server/lib/initial-wazuh-config.ts
  server/start/monitoring/index.ts
Labels: enhancement
