Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-12, with the labels that each got.

#4972 Added export logs validation when is empty
  CHANGELOG.md
  public/controllers/management/components/management/mg-logs/logs.js
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd

#4934 Add endpoint response
  docker/imposter/agents/summary_status.json
  docker/imposter/wazuh-config.yml
Labels: backport 4.5-7.16, backport 4.5

#4971 Fix limit property in wazuh-api controller
  CHANGELOG.md
  server/controllers/wazuh-api.ts
Labels: backport 4.4-7.16, backport 4.4-7.10

#4970 Added file saving conditions in File Editor
  CHANGELOG.md
  public/controllers/management/components/management/common/file-editor.tsx
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd

#5001 Add osd 2.4 env
  docker/images/osd-2.4.0-dev.Dockerfile
  docker/images/osd-2.4.1-dev.Dockerfile
  docker/osd-dev/README.md
  docker/osd-dev/dev.sh
Labels: backport 4.4-7.16, backport 4.4-7.10

#4982 [Backport 4.4-2.4-wzd] Fix the agent installation command for macOS
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: bug

#4954 Fixed paste value on server address selected
  CHANGELOG.md
  public/controllers/agent/components/register-agent-service.ts
Labels: bug, backport 4.4-7.16, backport 4.4-2.4-wzd

#4996 Fix agent status evolution visualization overlaps other UI elements
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  server/controllers/wazuh-elastic.ts
Labels: bug

#4943 Fix agent deployment instructions for HP-UX and Solaris
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd

#4985 Fix vulnerabilities in dependencies
  CHANGELOG.md
  package.json
  public/app.js
  public/get_inner_angular.ts
  public/kibana-integrations/kibana-discover.js
  server/routes/wazuh-reporting.test.ts
Labels: backport 4.4-7.16, security

#5004 [Backport 4.4-7.16] Fixed Inventory checks table filters by stats (#4999)
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
  public/components/agents/sca/inventory/checks-table.tsx
Labels: bug

#5014 Fix vulnerabilities in dependencies
  CHANGELOG.md
  package.json
  public/app.js
  public/get_inner_angular.ts
  public/kibana-integrations/kibana-discover.js
Labels: security

#5010 Remove duplicated buttons in SCA inventory
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
Labels: UI/UX, backport 4.4-7.16, backport 4.4-7.10

#5016 [Backport 4.4-7.16] Remove duplicated buttons in SCA inventory
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
Labels: UI/UX

#5017 [Backport 4.4-7.10] Remove duplicated buttons in SCA inventory
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
Labels: UI/UX

#5021 Add validation to agent name
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: enhancement

#5023 [Backport 4.4-2.4-wzd] Add validation to agent name
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: enhancement

#4981 Fixed the manager option in the agent deployment section
  CHANGELOG.md
  public/controllers/agent/components/register-agent-service.test.ts
  public/controllers/agent/components/register-agent-service.ts
  public/controllers/agent/components/register-agent.js
  public/controllers/agent/register-agent/steps/server-address.test.tsx
Labels: backport 4.4-7.10, backport 4.4-2.4-wzd

#4933 Fix deploy new agent section
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
  public/controllers/agent/components/wz-accordion.tsx
  public/controllers/agent/wazuh-config/index.ts
  public/styles/component.scss
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd

#4929 Disable unmapped fields filter
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
  public/components/common/modules/discover/row-details.tsx
  public/kibana-integrations/discover/application/components/table/table_row_btn_filter_add.tsx
  public/kibana-integrations/discover/application/components/table/table_row_btn_filter_exists.tsx
  public/kibana-integrations/discover/application/components/table/table_row_btn_filter_remove.tsx
  public/kibana-integrations/discover/application/components/table/table_row_btn_toggle_column.tsx
  public/plugin.ts
Labels: bug

#5045 Fix section deploy new agent
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
  public/controllers/agent/wazuh-config/index.ts
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd
