Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-09, with the labels that each got.

#3874 [PR] Add agent synchronization statistics
  CHANGELOG.md
  common/api-info/endpoints.json
  common/constants.ts
  public/components/agents/agent-synced.tsx
  public/components/tools/devtools/api-requests-list.js
  public/controllers/agent/agents-preview.js
  public/controllers/agent/agents.js
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-table.js
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  public/controllers/management/components/management/status/actions-buttons-main.js
  public/controllers/management/components/management/status/status-overview.js
  public/controllers/management/components/management/status/status-stats.js
  public/controllers/overview/overview.js
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#3905 Added agents windows events config tab
  CHANGELOG.md
  public/controllers/management/components/management/configuration/log-collection/log-collection-commands.js
  public/controllers/management/components/management/configuration/log-collection/log-collection-logs.js
  public/controllers/management/components/management/configuration/log-collection/log-collection-sockets.js
  public/controllers/management/components/management/configuration/log-collection/log-collection-windowsevents.js
  public/controllers/management/components/management/configuration/log-collection/log-collection.js
  public/controllers/management/components/management/configuration/log-collection/log-collection.test.tsx
  public/controllers/management/components/management/configuration/log-collection/types.js
  public/controllers/management/components/management/configuration/util-components/configuration-setting.js
  public/controllers/management/components/management/configuration/util-components/configuration-settings-group.js
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4439 Fix 60 test cases for Cypress test suite on wzd
  test/cypress/cypress/integration/features/management/decoders/should-list-decoders-and-show-the-pager.feature
  test/cypress/cypress/integration/pageobjects/wzd/filters/filters.page.js
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/decoders.page.js
  test/cypress/cypress/integration/step-definitions/management/decoders/the-user-press-button-custom-decoders.when.js
  test/cypress/cypress/integration/step-definitions/management/decoders/the-user-selects-a-custom-decoder-when.js
  test/cypress/cypress/integration/utils/login-constants.js
  test/cypress/cypress/support/index.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4449 Fix read kibana log test case for Cypress test suite on WZD
  test/cypress/cypress/integration/pageobjects/basic/settings/logs.page.js
  test/cypress/cypress/integration/pageobjects/odfe/settings/logs.page.js
  test/cypress/cypress/integration/pageobjects/wzd/settings/logs.page.js
  test/cypress/cypress/integration/pageobjects/xpack/settings/logs.page.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4363 Agents section performance improvements
  CHANGELOG.md
  public/controllers/agent/agents-preview.js
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-preview.scss
  public/controllers/agent/components/agents-table.js
  public/controllers/agent/components/register-agent.js
  public/kibana-integrations/kibana-vis.js
  public/templates/agents-prev/agents-prev.html
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4425 Fixed dashboard nested fields filtering
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
  public/components/overview/metrics/metrics.tsx
  public/components/overview/mitre/lib/elastic-helpers.ts
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4428 Render nested field rows in security alerts table
  CHANGELOG.md
  public/components/common/modules/discover/discover.scss
  public/components/common/modules/discover/discover.tsx
  public/components/common/modules/discover/row-details.tsx
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4459 Updating XML selector for decoder file
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/decoders.page.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4174 Refactor ruleset management
  public/components/common/buttons/modal-confirm.tsx
  public/components/common/hocs/withButtonOpenOnClick.tsx
  public/components/common/tables/components/export-table-csv.tsx
  public/components/common/tables/table-default.tsx
  public/components/common/tables/table-with-search-bar.tsx
  public/components/common/tables/table-wz-api.tsx
  public/components/common/welcome/components/menu-agent.js
  public/components/wz-menu/wz-menu-agent.js
  public/components/wz-menu/wz-menu-management.js
  public/components/wz-menu/wz-menu-overview.js
  public/controllers/management/components/management/cdblists/components/cdblists-table.tsx
  public/controllers/management/components/management/cdblists/components/columns.tsx
  public/controllers/management/components/management/cdblists/main-cdblists.tsx
  public/controllers/management/components/management/cdblists/views/cdblists-overview.tsx
  public/controllers/management/components/management/cdblists/views/list-editor.tsx
  public/controllers/management/components/management/common/actions-buttons.tsx
  public/controllers/management/components/management/common/colors.ts
  public/controllers/management/components/management/common/constants.ts
  public/controllers/management/components/management/common/error-helper.ts
  public/controllers/management/components/management/common/file-editor.tsx
  public/controllers/management/components/management/common/flyout-detail.scss
  public/controllers/management/components/management/common/interfaces.ts
  public/controllers/management/components/management/common/layout-overview.scss
  public/controllers/management/components/management/common/resources-handler.ts
  public/controllers/management/components/management/common/valid-configuration.ts
  public/controllers/management/components/management/decoders/components/columns.tsx
  public/controllers/management/components/management/decoders/components/decoders-suggestions.ts
  public/controllers/management/components/management/decoders/components/decoders-table.tsx
  public/controllers/management/components/management/decoders/components/flyout-detail.tsx
  public/controllers/management/components/management/decoders/main-decoders.test.tsx
  public/controllers/management/components/management/decoders/main-decoders.tsx
  public/controllers/management/components/management/decoders/views/decoder-info.tsx
  public/controllers/management/components/management/decoders/views/decoders-overview.tsx
  public/controllers/management/components/management/management-main.js
  public/controllers/management/components/management/ruleset/actions-buttons.js
  public/controllers/management/components/management/ruleset/components/columns.tsx
  public/controllers/management/components/management/ruleset/components/flyout-detail.tsx
  public/controllers/management/components/management/ruleset/components/ruleset-suggestions.ts
  public/controllers/management/components/management/ruleset/components/ruleset-table.tsx
  public/controllers/management/components/management/ruleset/decoder-info.js
  public/controllers/management/components/management/ruleset/main-ruleset.js
  public/controllers/management/components/management/ruleset/main-ruleset.tsx
  public/controllers/management/components/management/ruleset/ruleset-filter-bar.js
  public/controllers/management/components/management/ruleset/ruleset-overview.js
  public/controllers/management/components/management/ruleset/ruleset-popover-filters.tsx
  public/controllers/management/components/management/ruleset/ruleset-search-bar.js
  public/controllers/management/components/management/ruleset/ruleset-table.js
  public/controllers/management/components/management/ruleset/section-selector.js
  public/controllers/management/components/management/ruleset/utils/columns.tsx
  public/controllers/management/components/management/ruleset/views/rule-info.tsx
  public/controllers/management/components/management/ruleset/views/ruleset-overview.tsx
  public/controllers/management/components/upload-files.js
  public/controllers/management/management.js
  public/redux/actions/rulesetActions.js
  public/redux/reducers/rootReducers.js
  public/redux/reducers/rulesetReducers.js
  public/styles/common.scss
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4490 change webelement and add new library for mouseover
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-navigates-to-custom-rules-when.js
  test/cypress/package.json
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4496 Test Fixed, change decoder/rule tittle for correct execution
  test/cypress/cypress/integration/step-definitions/management/decoders/the-user-creates-a-new-decoder-when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-writes-a-new-rule-when.js
  test/cypress/cypress/integration/utils/driver.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4508 Changed terms of Office Max Rule Level
  public/components/overview/metrics/metrics.tsx
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4517 Editing selectors to solved duplicated calls
  test/cypress/cypress/integration/pageobjects/basic/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/odfe/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/rules.page.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4519 Shoud list decoders and show the pager
  test/cypress/cypress/integration/pageobjects/basic/wazuh-menu/decoders.page.js
  test/cypress/cypress/integration/pageobjects/odfe/wazuh-menu/decoders.page.js
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/decoders.page.js
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/decoders.page.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4528 fix for #4527- remove filter from modules dashboard
  test/cypress/cypress/integration/features/filters/remove-filter-from-module-dashboard.feature
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4534 fix for configuration feature
  test/cypress/cypress/integration/step-definitions/settings/configuration/valida-configuration.when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4511 fix for 4499-validate-that-the-added-filter-label-is-removed-after-click-remove-filter-option-dashboard
  test/cypress/cypress/integration/features/filters/remove-filter-from-module-dashboard.feature
  test/cypress/cypress/integration/step-definitions/filters/navigate-to-modules.when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4539 Initialize Wazuh plugin with custom logos
  CHANGELOG.md
  public/plugin.ts
  server/controllers/wazuh-api.ts
  server/routes/wazuh-api.ts
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4547 4545-fix for "add sample data" and "About" features
  test/cypress/cypress/integration/features/management/settings/sample-data.feature
  test/cypress/cypress/integration/pageobjects/wzd/settings/api-configuration.page.js
  test/cypress/cypress/integration/pageobjects/wzd/settings/logs.page.js
  test/cypress/cypress/integration/step-definitions/filters/the-user-adds-a-new-filter.when.js
  test/cypress/cypress/integration/step-definitions/settings/navigate-to-settings.when.js
  test/cypress/cypress/integration/step-definitions/settings/sample-data/add-remove-sample-data.when.js
  test/cypress/cypress/integration/step-definitions/settings/wazuh-logs/reload-logs.when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4556 4550-feature/fix for enable modules Virus Total in Xpack
  test/cypress/cypress/integration/step-definitions/settings/navigate-to-settings.when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4563 fix for kibana-xpack cofiguration texts
  test/cypress/cypress/fixtures/configuration.panel.text.json
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4516 Modify agent overview page
  CHANGELOG.md
  public/components/common/modules/module.scss
  public/components/common/welcome/agents-welcome.js
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4569 fix for timeout and change the if conditional
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/wazuh-menu.page.js
  test/cypress/cypress/integration/step-definitions/management/decoders/the-confirm-modal-is-displayed-then.js
  test/cypress/cypress/integration/step-definitions/management/groups/the-confirm-modal-is-displayed-then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-confirm-modal-is-displayed-then.js
  test/cypress/cypress/integration/step-definitions/settings/sample-data/add-remove-sample-data.when.js
  test/cypress/cypress/integration/utils/driver.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4529 Change message for API version mismatch in Kibana
  CHANGELOG.md
  common/constants.ts
  public/components/health-check/container/health-check.container.tsx
  public/components/health-check/services/check-setup.service.ts
Labels: backport 4.4-7.16

#4583 Create pull_request_template.md
  .github/pull_request_template.md
Labels: backport 3.13-7.7, backport 4.3-7.16, backport 4.3-1.2-wzd, backport 4.4-7.16, backport 4.4-1.2-wzd, backport 4.3-7.10, backport 4.4-7.10

#4574 Add new 'workflows for Github actions'.
  .github/workflows/backport.yml
  .github/workflows/create-wazuh-packages.yml
  .github/workflows/cypress-automation-tests.yml
  .github/workflows/cypress-basic.yml
  .github/workflows/cypress-odfe.yml
  .github/workflows/cypress-wzd.yml
  .github/workflows/cypress-xpack.yml
  .github/workflows/wazuh-build-push-docker-action.yml
  .github/workflows/wazuh-unit-test.yml
Labels: enhancement, backport 4.4-7.16, backport 4.4-1.2-wzd, backport 4.4-7.10

#4602 Update workflows
  .github/workflows/cypress-automation-tests.yml
  .github/workflows/wazuh-build-push-docker-action.yml
  .github/workflows/wazuh-unit-test.yml
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd, backport 4.4-7.10

#4607 Fix path to cypress folder
  test/cypress/images/ubuntu-cypress/Dockerfile
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4612 add feature to #4593 rules are displayed after refreshing the page fo…
  test/cypress/cypress/integration/features/management/rules/refresh-rules-page.feature
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-should-see-the-rule-page.then.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4614 Delete CP command for reports on Cypress
  .github/workflows/cypress-basic.yml
  .github/workflows/cypress-odfe.yml
  .github/workflows/cypress-wzd.yml
  .github/workflows/cypress-xpack.yml
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd, backport 4.4-7.10

#4610 Feature/generate reports modules qa
  test/cypress/cypress/integration/features/management/reporting/add-report-from-modules.feature
  test/cypress/cypress/integration/pageobjects/basic/reporting/report.page.js
  test/cypress/cypress/integration/pageobjects/odfe/reporting/report.page.js
  test/cypress/cypress/integration/pageobjects/wzd/reporting/report.page.js
  test/cypress/cypress/integration/pageobjects/xpack/reporting/report.page.js
  test/cypress/cypress/integration/step-definitions/reporting/generate-module-report-when.js
  test/cypress/cypress/integration/step-definitions/reporting/modules-report-data.js
  test/cypress/cypress/integration/step-definitions/reporting/the-user-navigates-to-management-reporting-when.js
  test/cypress/cypress/integration/step-definitions/reporting/the-user-report-is-dispalyed-in-the-table-then.js
  test/cypress/cypress/integration/step-definitions/settings/sample-data/validate-sample-data-added.then.js
  test/cypress/cypress/integration/utils/mappers/basic-pages-mapper.js
  test/cypress/cypress/integration/utils/mappers/odfe-pages-mapper.js
  test/cypress/cypress/integration/utils/mappers/wzd-pages-mapper.js
  test/cypress/cypress/integration/utils/mappers/wzd/reporting-modules-mapper.js
  test/cypress/cypress/integration/utils/mappers/xpack-pages-mapper.js
  test/cypress/cypress/integration/utils/pages-constants.js
  test/cypress/cypress/support/index.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4623 Create CODEOWNERS
  .github/CODEOWNERS
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd, backport 4.4-7.10
