Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-03, with the labels that each got.

#3866 Refactored events documents discover links building
  CHANGELOG.md
  public/kibana-integrations/discover/application/angular/doc_table/components/table_row.ts
  public/kibana-integrations/discover/application/angular/doc_table/components/table_row/details.html
  public/services/resolves/go-to-plugin-platform.js
  public/services/resolves/index.js
  public/services/routes.js
Labels: 4.3

#3901 [FIX] [Vulnerabilities/Inventory] Table not reload when changing the selected agent
  CHANGELOG.md
  public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
  public/components/common/tables/table-default.tsx
  public/components/common/tables/table-with-search-bar.tsx
  public/components/common/tables/table-wz-api.tsx
Labels: bug

#3893 Vulnerability inventory rework
  CHANGELOG.md
  common/api-info/endpoints.json
  common/api-info/security-actions.json
  public/components/agents/vuls/inventory.tsx
  public/components/agents/vuls/inventory/detail.tsx
  public/components/agents/vuls/inventory/flyout.tsx
  public/components/agents/vuls/inventory/lib/api-requests.ts
  public/components/agents/vuls/inventory/lib/getFilterValues.ts
  public/components/agents/vuls/inventory/lib/index.ts
  public/components/agents/vuls/inventory/table.tsx
  public/components/common/charts/charts/donut.tsx
  public/components/common/charts/hooks/use_chart_dimensions.ts
  public/components/common/charts/visualizations/basic.tsx
  public/components/common/charts/visualizations/legend.scss
  public/components/common/charts/visualizations/legend.tsx
  public/components/common/hooks/index.ts
  public/components/common/hooks/use_async_action_run_on_start.ts
  public/components/common/modules/events-selected-fields.js
  public/components/common/modules/main-overview.tsx
  public/components/common/modules/modules-defaults.js
  public/components/common/welcome/agents-welcome.js
  public/components/common/welcome/components/requirement_vis/components/index.ts
  public/components/common/welcome/components/requirement_vis/components/requirement_head/index.ts
  public/components/common/welcome/components/requirement_vis/components/requirement_head/requirements_head.tsx
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/index.ts
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/no_alerts_message.tsx
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_donnut/hooks/index.ts
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_donnut/index.ts
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_donnut/requirements_donnut.tsx
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_leggend/index.ts
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_leggend/requirements_leggend.scss
  public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_leggend/requirements_leggend.tsx
  public/components/common/welcome/components/requirement_vis/components/requitement_body/index.ts
  public/components/common/welcome/components/requirement_vis/components/requitement_body/requirements_body.tsx
  public/components/common/welcome/components/requirement_vis/lib/get_requirement_alerts.ts
  public/components/common/welcome/components/requirement_vis/lib/index.ts
  public/components/common/welcome/components/requirement_vis/requirement_vis.tsx
  public/components/visualize/agent-visualizations.js
  public/react-services/vis-factory-handler.js
  public/styles/common.scss
  public/templates/agents/visualizations.js
  server/integration-files/visualizations/agents/agents-vuls.ts
  server/integration-files/visualizations/agents/index.ts
  server/integration-files/visualizations/overview/index.ts
  server/integration-files/visualizations/overview/overview-vuls.ts
Labels: 4.3

#3924 [Known fields] Add fields to the know fields for the index pattern of alerts
  CHANGELOG.md
  public/utils/known-fields.js
Labels: enhancement
