Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-11, with the labels that each got.

#4784 Fixing login method for WZD
  test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
  test/cypress/cypress/support/index.js
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4507 Add switch to toggle the use of custom branding
  CHANGELOG.md
  common/constants.ts
  common/plugin-settings.test.ts
  common/services/settings.test.ts
  common/services/settings.ts
  public/components/common/form/index.tsx
  public/components/common/hocs/withUserLogged.tsx
  public/components/health-check/container/health-check.container.tsx
  public/components/settings/configuration/components/categories/components/category/category.tsx
  public/components/settings/configuration/configuration.tsx
  public/components/wz-menu/wz-menu.js
  public/plugin.ts
  server/controllers/wazuh-api.ts
  server/lib/reporting/printer.ts
  server/routes/wazuh-utils/wazuh-utils.test.ts
Labels: enhancement, backport 4.4-7.16, backport 4.4-2.3-wzd

#4785 Add multi-line validation parameters in config description
  CHANGELOG.md
  common/constants.ts
  common/services/settings-validator.ts
  common/services/settings.ts
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4798 Fix the rows limit in the textarea input
  public/components/common/form/input_text_area.tsx
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4805 Fix PDF header and footer input max row length
  CHANGELOG.md
  common/constants.ts
  common/plugin-settings.test.ts
  server/lib/reporting/printer.ts
  server/routes/wazuh-utils/wazuh-utils.test.ts
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4794 Adding remove filters from agent module
  test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-dashboard.feature
  test/cypress/cypress/integration/step-definitions/filters/the-user-removes-applied-filter-on-agent.when.js
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4814 Adding a new test
  test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-events.feature
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4758 Add centralized request service
  CHANGELOG.md
  public/plugin.ts
  public/react-services/generic-request.js
  public/react-services/wz-api-check.js
  public/react-services/wz-request.ts
  public/services/request-handler.js
  public/services/request-handler.test.js
  server/plugin.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd, backport 4.4-7.16, backport 4.3-7.10, backport 4.4-7.10

#4815 change function to get the path programatically
  CHANGELOG.md
  public/app.js
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4845 Fixed 4.3.10 changelog
  CHANGELOG.md
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4849 Fixed WAZUH_PROTOCOL param suggestion
  CHANGELOG.md
  public/controllers/agent/components/register-agent-service.test.ts
  public/controllers/agent/components/register-agent-service.ts
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4851 Show name and number in OS version
  CHANGELOG.md
  public/controllers/agent/wazuh-config/index.ts
Labels: 4.4, backport 4.4-7.16, backport 4.4-2.3-wzd

#4831 Add centralized request service
  CHANGELOG.md
  public/plugin.ts
  public/react-services/generic-request.js
  public/react-services/wz-api-check.js
  public/react-services/wz-request.ts
  public/services/request-handler.js
  public/utils/index.ts
  public/utils/odfe-utils.ts
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4867 Fix add mac os version
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
  public/controllers/agent/wazuh-config/index.ts
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4873 Added data-test-subj create policy
  CHANGELOG.md
  public/components/security/policies/create-policy.tsx
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4876 Fix architecture link in the deploy agent wizard
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4879 Post-release v4.3.10
  CHANGELOG.md
  README.md
  kibana.json
  package.json
  public/app.js
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd, backport 4.4-7.10, backport stable

#4888 Fix Changelog for 7.10
  CHANGELOG.md
Labels: backport 4.5-7.10

#4889 Fix Changelog for 7.16
  CHANGELOG.md
Labels: backport 4.5-7.16

#4890 Fix Changelog for WzD
  CHANGELOG.md
Labels: backport 4.5-2.3-wzd

#4896 Bump development Docker environments to 4.5.0
  docker/imposter/agents/agent.json
  docker/imposter/agents/agents.js
  docker/imposter/agents/agents.json
  docker/imposter/api-info/api_info.json
  docker/imposter/cluster/cluster_node_info.js
  docker/imposter/cluster/cluster_node_info.json
  docker/imposter/cluster/cluster_node_info_no_restart.json
  docker/imposter/cluster/cluster_restart.js
  docker/imposter/cluster/cluster_restart.json
  docker/imposter/cluster/cluster_sync.js
  docker/imposter/cluster/cluster_sync.json
  docker/imposter/cluster/cluster_sync_no_sync.json
  docker/imposter/cluster/component_configuration.js
  docker/imposter/cluster/configuration/analysis_active_response.json
  docker/imposter/cluster/configuration/analysis_alerts.json
  docker/imposter/cluster/configuration/analysis_command.json
  docker/imposter/cluster/configuration/analysis_global.json
  docker/imposter/cluster/configuration/analysis_labels.json
  docker/imposter/cluster/configuration/auth_auth.json
  docker/imposter/cluster/configuration/com_cluster.json
  docker/imposter/cluster/configuration/com_logging.json
  docker/imposter/cluster/configuration/csyslog_csyslog.json
  docker/imposter/cluster/configuration/integrator_integration.json
  docker/imposter/cluster/configuration/logcollector_localfile.json
  docker/imposter/cluster/configuration/logcollector_socket.json
  docker/imposter/cluster/configuration/mail_alerts.json
  docker/imposter/cluster/configuration/mail_global.json
  docker/imposter/cluster/configuration/monitor_reports.json
  docker/imposter/cluster/configuration/request_remote.json
  docker/imposter/cluster/configuration/syscheck_rootcheck.json
  docker/imposter/cluster/configuration/syscheck_syscheck.json
  docker/imposter/cluster/configuration/wmodules_wmodules.json
  docker/imposter/cluster/error.json
  docker/imposter/errors/internal_server_error.json
  docker/imposter/initial_data.json
  docker/imposter/rules/get_rules.json
  docker/imposter/security/login.js
  docker/imposter/security/security_policies.json
  docker/imposter/security/security_roles.json
  docker/imposter/vulnerability/vulnerabilities.json
  docker/imposter/vulnerability/vulnerabilities_summary.js
  docker/imposter/vulnerability/vulnerabilities_summary_cve.json
  docker/imposter/vulnerability/vulnerabilities_summary_cvss2_score.json
  docker/imposter/vulnerability/vulnerabilities_summary_cvss3_score.json
  docker/imposter/vulnerability/vulnerabilities_summary_name.json
  docker/imposter/vulnerability/vulnerabilities_summary_severity.json
  docker/imposter/vulnerability/vulnerabilities_summary_version.json
  docker/imposter/wazuh-config.yml
Labels: backport 4.5-7.10, backport 4.5-7.16

#4688 Typo correction
  public/components/add-modules-data/sample-data.tsx
  public/components/agents/fim/inventory/filterBar.tsx
  public/components/agents/prompts/prompt-agent-feature-version.tsx
  public/components/agents/sca/inventory.tsx
  public/components/common/hocs/withButtonOpenOnClick.tsx
  public/components/common/hocs/withGlobalBreadcrumb.tsx
  public/components/common/hocs/with_module_tab_loader.tsx
  public/components/common/modules/panel/main-panel.tsx
  public/components/common/welcome/components/sca_scan/sca_scan.tsx
  public/components/health-check/components/check-result.tsx
  public/components/overview/mitre_attack_intelligence/all_resources_search_results.tsx
  public/components/overview/mitre_attack_intelligence/resources.tsx
  public/components/security/roles/edit-role-table.tsx
  public/components/wz-search-bar/wz-search-badges.tsx
  public/components/wz-search-bar/wz-search-bar.test.tsx
Labels: hacktoberfest-accepted, backport 4.5-7.10, backport 4.5-7.16, backport 4.5

#4902 Update patterns to match branches
  .github/workflows/eslint.yml
  .github/workflows/unit-test.yml
Labels: backport 4.5-7.10, backport 4.5-7.16, backport 4.5

#4911 Typo correction (#4688)
  CHANGELOG.md
  public/components/agents/fim/inventory/filterBar.tsx
  public/components/agents/prompts/prompt-agent-feature-version.tsx
  public/components/agents/sca/inventory.tsx
  public/components/common/hocs/withButtonOpenOnClick.tsx
  public/components/common/hocs/withGlobalBreadcrumb.tsx
  public/components/common/hocs/with_module_tab_loader.tsx
  public/components/common/modules/panel/main-panel.tsx
  public/components/common/welcome/components/sca_scan/sca_scan.tsx
  public/components/health-check/components/check-result.tsx
  public/components/overview/mitre_attack_intelligence/all_resources_search_results.tsx
  public/components/overview/mitre_attack_intelligence/resources.tsx
  public/components/security/roles/edit-role-table.tsx
  public/components/wz-search-bar/wz-search-badges.tsx
  public/components/wz-search-bar/wz-search-bar.test.tsx
  public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
Labels: backport 4.5-7.10, backport 4.5-7.16, backport 4.5

#4909 Fix IPV6 visualizations
  CHANGELOG.md
  public/components/common/welcome/agents-info.js
  public/controllers/agent/components/agents-table.js
  public/services/ipv6-services.test.js
  public/services/ipv6-services.ts
Labels: backport 4.5-7.16, backport 4.5

#4918 4711 error not caught and wrong error message in pci module
  CHANGELOG.md
  public/components/overview/compliance-table/compliance-table.tsx
  public/react-services/generic-request.js
Labels: 4.5, backport 4.5-7.16, backport 4.5

#4917 Fix display of remote protocols when there are more than one
  CHANGELOG.md
  public/controllers/management/components/management/configuration/utils/utils.js
Labels: backport 4.5-7.16, backport 4.5
