Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-06, with the labels that each got.

#4169 [UI] Replaced as the full and partial scan dates are displayed in the Details panel in Vulnerabilites/Inventory
  CHANGELOG.md
  public/components/agents/vuls/inventory.tsx
Labels: enhancement, UI/UX, backport 4.3-7.16, backport 4.3-1.2-wzd, backport cloud/4.3-7.10, backport cloud/4.3-7.10-custom-agents-view

#4166 [Enhancement] Consistency in the non-core visualizations and agent status
  CHANGELOG.md
  common/constants.ts
  common/services/wz_agent_status.ts
  public/components/agents/agent_status.test.tsx
  public/components/agents/agent_status.tsx
  public/components/agents/fim/main.tsx
  public/components/agents/sca/inventory.tsx
  public/components/agents/sca/main.tsx
  public/components/agents/stats/agent-stats.tsx
  public/components/agents/syscollector/inventory.tsx
  public/components/common/charts/visualizations/basic.tsx
  public/components/common/modules/main-agent.tsx
  public/components/common/modules/main-overview.tsx
  public/components/common/modules/overview-current-section.tsx
  public/components/common/welcome/agents-info.js
  public/components/common/welcome/agents-welcome.js
  public/components/d3/pie.js
  public/components/visualize/wz-visualize.js
  public/components/wz-menu/components/wz-agent-info.js
  public/components/wz-menu/wz-menu.js
  public/controllers/agent/agents.js
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-table.js
  public/controllers/management/components/management/configuration/configuration-overview.js
  public/controllers/management/components/management/configuration/configuration-switch.js
  public/controllers/management/components/management/groups/group-agents-table.js
  public/controllers/management/components/management/status/actions-buttons-main.js
  public/controllers/management/components/management/status/status-agent-info.js
  public/controllers/management/components/management/status/status-node-info.js
  public/controllers/management/components/management/status/status-overview.js
  public/controllers/management/components/management/status/status-stats.js
  public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
  public/controllers/overview/components/overview-actions/agents-selection-table.js
  public/controllers/overview/components/stats.js
  public/controllers/overview/overview.js
  public/kibana-integrations/kibana-vis.js
  public/react-services/action-agents.js
  public/templates/visualize/dashboards.html
  public/templates/visualize/overview-welcome.html
  server/controllers/wazuh-reporting.ts
  server/integration-files/visualizations/overview/overview-general.ts
  server/integration-files/visualizations/overview/overview-office.ts
Labels: enhancement, backport 4.3-7.16, backport 4.3-1.2-wzd, backport cloud/4.3-7.10, backport cloud/4.3-7.10-custom-agents-view

#4176 Empty file upload
  CHANGELOG.md
  public/controllers/management/components/upload-files.js
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd, backport cloud/4.3-7.10, backport cloud/4.3-7.10-custom-agents-view

#4180 Overwriting files in rules and decoders
  CHANGELOG.md
  public/controllers/management/components/management/ruleset/actions-buttons.js
  public/controllers/management/components/upload-files.js
  public/styles/common.scss
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd, backport cloud/4.3-7.10, backport cloud/4.3-7.10-custom-agents-view

#4196 [FIX][Kibana][7.16.x-7.17.x] Fix error when building the visualizations
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  public/kibana-integrations/kibana-vis.js
Labels: bug

#4198 Agents tooltip background
  CHANGELOG.md
  public/components/common/charts/charts/donut.tsx
Labels: UI/UX

#4200 [FIX] Visualizations are not built due a Types was not set error in a production package
  CHANGELOG.md
  public/kibana-integrations/kibana-vis.js
Labels: backport 4.3-1.2-wzd, backport cloud/4.3-7.10, backport cloud/4.3-7.10-custom-agents-view

#4239 Changed phrase "Wazuh server"
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: UI/UX

#4237 [BUG] Plugin crash when searching with a query with syntax errors in Modules/Security events
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4244 Ruleset test messages
  CHANGELOG.md
  public/directives/wz-logtest/components/logtest.tsx
Labels: enhancement, UI/UX, backport 4.3-7.16, backport 4.3-1.2-wzd

#4235 [Statistics] Remove logged error related to the creation of an existent index
  CHANGELOG.md
  server/start/cron-scheduler/save-document.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4261 Added authorization prompt in Mitre > Intelligence
  CHANGELOG.md
  public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
  public/components/overview/mitre_attack_intelligence/intelligence.test.tsx
  public/components/overview/mitre_attack_intelligence/intelligence.tsx
Labels: enhancement, backport 4.3-7.16, backport 4.3-1.2-wzd

#4253 Fixed code editor component height in logs layout (Management and Settings)
  CHANGELOG.md
  public/components/settings/settings-logs/logs.js
  public/controllers/management/components/management/mg-logs/logs.js
Labels: bug, UI/UX, backport 4.3-7.16, backport 4.3-1.2-wzd

#4254 Enhancement/4211 improve visualizations text size
  CHANGELOG.md
  public/components/agents/vuls/inventory.tsx
  public/components/agents/vuls/inventory/table.tsx
  public/components/common/charts/visualizations/basic.tsx
  public/components/common/charts/visualizations/legend.tsx
Labels: enhancement, UI/UX, backport 4.3-7.16, backport 4.3-1.2-wzd

#4264 Timeout change in the restart manager in the configuration
  CHANGELOG.md
  public/components/security/policies/create-policy.tsx
  public/components/visualize/components/sample-data-warning.js
  public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  public/controllers/management/components/management/reporting/utils/reporting-handler.js
  public/react-services/wz-request.ts
Labels: bug, backport 4.3-7.16, backport 4.3-1.2-wzd

#4266 Fixed parsedError string handling
  CHANGELOG.md
  public/controllers/dev-tools/dev-tools.test.tsx
  public/controllers/dev-tools/dev-tools.ts
Labels: bug, backport 4.3-7.16, backport 4.3-1.2-wzd

#4267 Remove the filtered tags of manager logs
  CHANGELOG.md
  common/api-info/endpoints.json
  public/controllers/management/components/management/mg-logs/logs.js
Labels: enhancement, backport 4.3-7.16, backport 4.3-1.2-wzd
