Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-05, with the labels that each got.

#4130 Fixed Responsive agents evolution
  public/controllers/agent/components/agents-preview.js
Labels: bug, 4.3

#4132 Fix windows command for agent installation
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: 4.3

#4141 [Logtest] Enhance the output of Ruleset Test
  CHANGELOG.md
  public/directives/wz-logtest/components/logtest.tsx
Labels: 4.3

#4142 Add powershell version warning
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: enhancement

#4146 [FIX] Avoid to remove the implicit filters in the modules
  CHANGELOG.md
  public/components/common/modules/modules-helper.js
Labels: bug
