Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-02, with the labels that each got.

#3826 Override the navigation drawer `Home` link behaviour
  CHANGELOG.md
  kibana.json
  package.json
  public/assets/custom-style.js
Labels: cloud

#3831 Fix internal xpack user request forbidden
  CHANGELOG.md
  package.json
  server/lib/security-factory/security-factory.ts
Labels: 4.3

#3847 [TESTS] Fix and update the tests
  public/components/agents/stats/table.test.tsx
  public/components/common/util/markdown/markdown.test.tsx
  public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
  public/components/health-check/container/health-check.container.test.tsx
  public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/SubscriptionTab.test.tsx
  public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
  public/controllers/management/components/management/ruleset/main-ruleset.test.tsx
  public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
  public/controllers/management/components/management/status/status-main.test.tsx
Labels: enhancement

#3846 [FEAT] [Deploy agent guide] Add step to start the agent on Windows
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: enhancement

#3845 Fixed agents details card style
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  public/styles/common.scss
Labels: 4.3

#3854 Fixed agents evolutions card
  CHANGELOG.md
  public/components/wz-kibana-vis/wz-kibana-vis.tsx
  public/controllers/agent/components/agents-preview.js
  public/kibana-integrations/kibana-vis.js
  server/controllers/wazuh-elastic.ts
  server/routes/wazuh-elastic.ts
Labels: 4.3

#3860 Fixed agents link mobile style in Agents details card
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  public/styles/common.scss
Labels: 4.3
