Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-07, with the labels that each got.

#4280 Display a message related to missing user permissions when finding index patterns in a route resolver
  CHANGELOG.md
  public/services/resolves/get-ip.js
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4326 Added feature searchbar conjuntion parser
  public/components/wz-search-bar/components/wz-search-badges/wz-search-badges.tsx
  public/components/wz-search-bar/lib/filters-to-object.test.ts
  public/components/wz-search-bar/lib/filters-to-object.ts
  public/components/wz-search-bar/lib/q-interpreter.test-cases.ts
  public/components/wz-search-bar/lib/q-interpreter.test.ts
  public/components/wz-search-bar/lib/q-interpreter.ts
  public/components/wz-search-bar/lib/suggest-handler.ts
  public/components/wz-search-bar/wz-search-bar.test-cases.ts
  public/components/wz-search-bar/wz-search-bar.test.tsx
Labels: bug, 4.3, backport 4.3-7.16, backport 4.3-1.2-wzd

#4330 Sanitize report's inputs and usernames
  public/controllers/management/components/management/reporting/reporting-table.js
  public/react-services/reporting.js
  server/controllers/wazuh-reporting-security-endpoint-handler.test.ts
  server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
  server/controllers/wazuh-reporting.ts
  server/lib/error-response.ts
  server/lib/security-factory/factories/default-factory.ts
  server/lib/security-factory/factories/opendistro-factory.ts
  server/lib/security-factory/factories/xpack-factory.ts
  server/plugin.ts
  server/routes/wazuh-reporting.ts
  server/start/index.ts
  server/start/migration-tasks/index.ts
  server/start/migration-tasks/reports_directory_name.test.ts
  server/start/migration-tasks/reports_directory_name.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4333 Support for Wazuh 4.3.6
  README.md
  kibana.json
  package.json
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4323 Sorting by agents in the table groups
  CHANGELOG.md
  public/controllers/management/components/management/groups/utils/columns-main.js
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4341 Fix MD5 dependency
  package.json
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4352 Fixed path in logo customization section
  CHANGELOG.md
  common/constants.ts
  public/utils/config-equivalences.js
  server/lib/initial-wazuh-config.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd
