Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-08, with the labels that each got.

#4377 Feature/sca module
  test/performance/modules/sca-module.js
Labels: Performance Test

#4358 Fix creating PDF reports in x-pack without authentication context
  CHANGELOG.md
  common/constants.ts
  server/lib/security-factory/factories/default-factory.ts
  server/lib/security-factory/factories/xpack-factory.ts
Labels: backport 4.3-7.16

#4375 Feature/tsc
  test/performance/common/constants.js
  test/performance/common/logger.js
  test/performance/modules/GDPR-module-controls.js
  test/performance/modules/GDPR-module-dashboard.js
  test/performance/modules/GDPR-module-events.js
  test/performance/modules/NIST-module-controls.js
  test/performance/modules/NIST-module-dashboard.js
  test/performance/modules/NIST-module-events.js
  test/performance/modules/PCI-DSS-module-controls.js
  test/performance/modules/PCI-DSS-module-dashboard.js
  test/performance/modules/PCI-DSS-module-events.js
  test/performance/modules/TSC-module-controls.js
  test/performance/modules/TSC-module-dashboard.js
  test/performance/modules/TSC-module-events.js
  test/performance/modules/mitre-attack-module.js
Labels: Performance Test

#4367 Fixed searchbar error on SCA Inventory table
  public/components/agents/sca/inventory.tsx
  public/components/wz-search-bar/lib/suggest-handler.ts
Labels: bug, backport 4.3-7.16, backport 4.3-1.2-wzd

#4350 Fixed errors in group reports
  CHANGELOG.md
  common/csv-key-equivalence.ts
  public/utils/monitoring-fields.ts
  server/controllers/wazuh-reporting.ts
  server/integration-files/monitoring-known-fields.ts
Labels: bug, backport 4.3-7.16, backport 4.3-1.2-wzd

#4359 Fix modules settings persistence between updates
  CHANGELOG.md
  server/start/initialize/index.test.ts
  server/start/initialize/index.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4362 TypeError resolved
  CHANGELOG.md
  public/plugin.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4378 Fix wazuh.yml link and in-file documentation
  CHANGELOG.md
  common/constants.ts
  public/services/resolves/get-config.js
  public/utils/config-equivalences.js
  server/controllers/wazuh-hosts.ts
  server/lib/initial-wazuh-config.ts
  server/lib/manage-hosts.ts
  server/lib/update-registry.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4372 Add performance scripts for the Vulnerabilities module
  test/performance/modules/vulnerabilities-events-modules.js
  test/performance/modules/vulnerabilities-inventory-modules.js
Labels: performance

#4336 Sanitize report's inputs and usernames - 3.13.x
  CHANGELOG.md
  README.md
  package.json
  public/react-services/reporting.js
  public/services/reporting.js
  server/controllers/wazuh-reporting.js
  server/routes/wazuh-reporting-enpoint-parameters-validation.test.ts
  server/routes/wazuh-reporting.js
  test/jest/jest.config.js
  test/jest/jest.js
Labels: enhancement

#4365 Create service to restart wazuh
  public/components/common/restart-cluster-manager-callout.tsx
  public/components/common/restart-modal/restart-modal.tsx
  public/components/common/wz-restart-callout.tsx
  public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  public/controllers/management/components/management/ruleset/actions-buttons.js
  public/controllers/management/components/management/ruleset/list-editor.js
  public/controllers/management/components/management/ruleset/ruleset-editor.js
  public/controllers/management/components/management/ruleset/ruleset-overview.js
  public/controllers/management/components/management/status/actions-buttons-main.js
  public/controllers/management/components/management/status/status-overview.js
  public/controllers/management/components/management/status/utils/status-handler.js
  public/controllers/management/management.js
  public/react-services/check-daemons-status.js
  public/react-services/index.ts
  public/react-services/wz-restart.js
  public/redux/actions/appStateActions.js
  public/redux/reducers/appStateReducers.js
  public/services/check-daemon-status.js
  public/services/config-handler.js
  public/services/index.js
  public/styles/common.scss
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4373 Fixed a routes loop when reinstalling Wazuh indexer
  CHANGELOG.md
  public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
  public/components/health-check/services/check-pattern-support.service.ts
  public/react-services/saved-objects.js
  server/start/initialize/index.ts
Labels: bug, backport 4.3-7.16, backport 4.3-7.10

#4399 Moved the file config-equivalences to common
  CHANGELOG.md
  common/config-equivalences.js
  public/components/settings/configuration/components/header.tsx
  public/components/settings/configuration/configuration.tsx
  server/lib/initial-wazuh-config.ts
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd
