Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-10, with the labels that each got.

#4617 Fix typo in API getAppLogos endpoint catch log
  server/controllers/wazuh-api.ts
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4635 Add test feature: list rules filtered by level
  test/cypress/CODEOWNERS
  test/cypress/cypress/integration/features/management/rules/should-list-rules-by-level.feature
  test/cypress/cypress/integration/pageobjects/basic/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/odfe/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-filter-label-is-displayed.then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-can-see-the-rule-then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-search-bar-when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4639 Add test feature: rules are displayed after refreshing the page using a filtered label
  test/cypress/cypress/integration/features/management/rules/filter-rules-si-displayed-after-refresh.feature
  test/cypress/cypress/integration/step-definitions/management/rules/the-filtered-label-is-still-visible-then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4655 Bump 4.3.9
  CHANGELOG.md
  README.md
  kibana.json
  package.json
Labels: backport 4.3-7.16, backport 4.3-1.2-wzd

#4663 Add feature rules are displayed when user clicks the first page - wzd - 4648
  test/cypress/cypress/integration/features/management/rules/draft--check-rows-dropdow.feature
  test/cypress/cypress/integration/features/management/rules/filter-rules-is-displayed-after-refresh.feature
  test/cypress/cypress/integration/features/management/rules/validate-paginator.feature
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/step-definitions/management/rules/The-user-clicks-on-the-page-when.js
  test/cypress/cypress/integration/step-definitions/management/rules/a-new-set-of-rules-displayed.when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-first-page-is-displayed-then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-page-button-disable.then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-rule-page-is-available.then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-rule-page-is-not-available.when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-redirected-next-rule-page-then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-see-that-the-rule-list-is-paginated.then.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4673 Remove draft file
  test/cypress/cypress/integration/features/management/rules/draft--check-rows-dropdow.feature
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4677 add feature for row dropdown on the rule page - WZD - 4676
  test/cypress/cypress/integration/features/management/rules/validator-rows-dropdow.feature
  test/cypress/cypress/integration/pageobjects/basic/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/odfe/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/rules.page.js
  test/cypress/cypress/integration/step-definitions/management/rules/a-maximum-rules-are-displayed-then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-click-limit-row-when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-see-rule-list-per-row-when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4682 fix for misspelling on features 4648
  test/cypress/cypress/integration/features/management/rules/validate-paginator.feature
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4664 Fix logout from Wazuh when SAML is enabled
  CHANGELOG.md
  public/app.js
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4680 Enhance and fix some GitHub actions workflows
  .github/workflows/build.yml
  .github/workflows/create-wazuh-packages.yml
  .github/workflows/dev-environment.yml
  .github/workflows/playground.yml
  .github/workflows/unit-test.yml
  .github/workflows/wazuh-build-push-docker-action.yml
  .github/workflows/wazuh-unit-test.yml
Labels: enhancement, backport 4.4-7.16, backport 4.4-1.2-wzd, backport 4.4-7.10, backport stable

#4691 Fix feature after test suite execution on WZD - 4687
  test/cypress/cypress/integration/step-definitions/management/rules/the-rule-page-is-available.then.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
  test/cypress/cypress/integration/step-definitions/management/rules/the-user-see-that-the-rule-list-is-paginated.then.js
  test/cypress/cypress/integration/step-definitions/settings/api-configuration/check-api-connection-from-instructions-modal.when.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-1.2-wzd

#4713 Fix the unit tests on Kibana 7.16.x-7.17.x
  public/components/agents/stats/__snapshots__/table.test.tsx.snap
  public/components/common/error-boundary/__snapshots__/error-boundary.test.tsx.snap
  public/components/common/hocs/error-boundary/__snapshots__/with-error-boundary.test.tsx.snap
  public/components/common/tables/__snapshots__/table-default.test.tsx.snap
  public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
  public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
  public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
  public/components/health-check/components/__snapshots__/check-result.test.tsx.snap
  public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
  public/controllers/management/components/management/decoders/__snapshots__/main-decoders.test.tsx.snap
  public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
  public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
  public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
  scripts/jest.js
  server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
  test/jest/config.js
Labels: bug

#4715 Fix the unit tests on Wazuh dashboard 4.4
  public/components/agents/stats/__snapshots__/table.test.tsx.snap
  public/components/common/error-boundary/__snapshots__/error-boundary.test.tsx.snap
  public/components/common/hocs/error-boundary/__snapshots__/with-error-boundary.test.tsx.snap
  public/components/common/tables/__snapshots__/table-default.test.tsx.snap
  public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
  public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
  public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
  public/components/health-check/components/__snapshots__/check-result.test.tsx.snap
  public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
  public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
  public/controllers/management/components/management/configuration/alerts/__snapshots__/alerts-configurations.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/__snapshots__/office365.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
  public/controllers/management/components/management/decoders/__snapshots__/main-decoders.test.tsx.snap
  public/controllers/management/components/management/groups/__snapshots__/groups-main.test.tsx.snap
  public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
  public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
  public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
  server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
  server/start/cron-scheduler/save-document.test.ts
  server/start/initialize/index.test.ts
  test/jest/config.js
Labels: bug

#4653 Fixed pagination to SCA table
  CHANGELOG.md
  public/components/agents/sca/inventory.tsx
  public/components/agents/sca/inventory/checks-table.tsx
  public/components/agents/sca/inventory/index.ts
  public/components/agents/sca/inventory/lib/api-request.ts
  public/components/agents/sca/inventory/lib/index.ts
  public/components/agents/vuls/inventory.tsx
  public/components/common/tables/table-default.tsx
  public/components/common/tables/table-wz-api.tsx
  public/components/wz-search-bar/lib/base-handler.ts
Labels: 4.4, backport 4.4-7.16, backport 4.4-1.2-wzd

#4710 Replace generic HTTP status codes in the API controller
  CHANGELOG.md
  common/constants.ts
  server/controllers/wazuh-api.ts
  server/routes/wazuh-api-http-status.test.ts
Labels: backport 4.4-7.16, backport 4.4-1.2-wzd

#4720 feature search by parameters And , Or
  test/cypress/cypress/integration/features/filters/Search-by-parameters.feature
  test/cypress/cypress/integration/features/filters/pin-filter-from-dashboard-to-events.feature
  test/cypress/cypress/integration/pageobjects/wzd/filters/filters.page.js
  test/cypress/cypress/integration/step-definitions/filters/The-user-types-particular-search.when.js
  test/cypress/cypress/integration/step-definitions/filters/the-query-is-accepted.then.js
  test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
  test/cypress/cypress/integration/utils/driver.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-2.3-wzd

#4728 Fix typos and errors code status replacement in wazuh-api controller
  CHANGELOG.md
  server/controllers/wazuh-api.ts
  server/routes/wazuh-api-http-status.test.ts
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4729 Adding sample data call on test definition
  test/cypress/cypress/integration/features/management/reporting/add-report-from-modules-agent.feature
  test/cypress/cypress/integration/features/management/reporting/add-report-from-modules.feature
Labels: backport 4.4-2.3-wzd, backport 4.4-7.10

#4738 Add an environment validation to check the request
  test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
Labels: backport 4.4-7.16, backport 4.4-2.3-wzd

#4512 Redesign the SCA table from agent's dashboard
  CHANGELOG.md
  public/components/agents/sca/index.ts
  public/components/agents/sca/inventory.tsx
  public/components/agents/sca/inventory/agent-policies-table.tsx
  public/components/agents/sca/inventory/checks-table.tsx
  public/components/agents/sca/inventory/index.ts
  public/components/common/modules/module.scss
  public/components/common/tables/__snapshots__/table-default.test.tsx.snap
  public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
  public/components/common/tables/table-default.tsx
  public/components/common/welcome/agents-welcome.js
  public/components/common/welcome/components/sca_scan/sca_scan.tsx
Labels: 4.4, backport 4.4-7.16, backport 4.4-2.3-wzd

#4750 fix for test suite execution from github actions
  test/cypress/cypress/integration/features/agents/add-agent-from-deploy-new-agent.feature
  test/cypress/cypress/integration/features/filters/add-filter-from-agent-events.feature
  test/cypress/cypress/integration/features/filters/add-filter-from-agent.feature
  test/cypress/cypress/integration/features/filters/add-new-filter-from-events.feature
  test/cypress/cypress/integration/features/filters/add-new-filter.feature
  test/cypress/cypress/integration/features/filters/pin-filter-from-dashboard-to-events.feature
  test/cypress/cypress/integration/features/filters/pin-filter-from-events-to-events.feature
  test/cypress/cypress/integration/features/management/decoders/create-new-decoder.feature
  test/cypress/cypress/integration/features/management/decoders/should-list-decoders-and-show-the-pager.feature
  test/cypress/cypress/integration/features/management/groups/edit-groups-without-saving.feature
  test/cypress/cypress/integration/features/management/rules/create-a-new-rule.feature
  test/cypress/cypress/integration/features/management/rules/edit-rules-without-saving.feature
  test/cypress/cypress/integration/features/management/rules/refresh-rules-page.feature
  test/cypress/cypress/integration/features/management/rules/validate-paginator.feature
  test/cypress/cypress/integration/features/management/settings/about.feature
  test/cypress/cypress/integration/features/management/settings/miscellaneous.feature
  test/cypress/cypress/integration/features/management/settings/sample-data.feature
  test/cypress/package.json
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-2.3-wzd

#4759 fix for tiemeout error on the github actions executon
  test/cypress/cypress/integration/utils/driver.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-2.3-wzd

#4503 Add validation to the plugin settings
  CHANGELOG.md
  common/constants.ts
  common/plugin-settings.test.ts
  common/services/settings-validator.ts
  public/components/common/form/__snapshots__/index.test.tsx.snap
  public/components/common/form/hooks.test.tsx
  public/components/common/form/hooks.tsx
  public/components/common/form/index.test.tsx
  public/components/settings/configuration/components/bottom-bar.tsx
  public/components/settings/configuration/components/categories/components/category/category.tsx
  server/routes/wazuh-utils/wazuh-utils.test.ts
  server/routes/wazuh-utils/wazuh-utils.ts
Labels: enhancement, backport 4.4-7.16, backport 4.4-2.3-wzd

#4739 Add agent name to the deployment command
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: 4.4

#4504 Upload file for `customization.logo.*` settings
  .gitignore
  CHANGELOG.md
  common/constants.ts
  common/plugin-settings.test.ts
  common/services/file-extension.test.ts
  common/services/file-extension.ts
  common/services/file-size.test.ts
  common/services/file-size.ts
  common/services/settings-validator.ts
  common/services/settings.ts
  public/components/common/form/__snapshots__/index.test.tsx.snap
  public/components/common/form/hooks.tsx
  public/components/common/form/index.test.tsx
  public/components/common/form/index.tsx
  public/components/common/form/input_filepicker.tsx
  public/components/common/form/input_number.tsx
  public/components/common/form/types.ts
  public/components/settings/configuration/components/categories/components/category/category.tsx
  public/components/settings/configuration/components/categories/components/show-toasts.tsx
  public/components/settings/configuration/configuration.tsx
  public/components/wz-menu/wz-menu.js
  public/components/wz-menu/wz-menu.scss
  public/controllers/management/components/upload-files.js
  public/react-services/wz-request.ts
  server/controllers/wazuh-utils/wazuh-utils.ts
  server/lib/filesystem.ts
  server/routes/wazuh-utils/fixtures/fixture_file.txt
  server/routes/wazuh-utils/fixtures/fixture_image_big.png
  server/routes/wazuh-utils/fixtures/fixture_image_small.jpg
  server/routes/wazuh-utils/fixtures/fixture_image_small.png
  server/routes/wazuh-utils/fixtures/fixture_image_small.svg
  server/routes/wazuh-utils/wazuh-utils.test.ts
  server/routes/wazuh-utils/wazuh-utils.ts
Labels: enhancement, backport 4.4-7.16, backport 4.4-2.3-wzd

#4770 Fix after login
  test/cypress/cypress/integration/pageobjects/basic/modules-directory.page.js
  test/cypress/cypress/integration/pageobjects/odfe/modules-directory.page.js
  test/cypress/cypress/integration/pageobjects/wzd/modules-directory.page.js
  test/cypress/cypress/integration/pageobjects/xpack/modules-directory.page.js
  test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
  test/cypress/cypress/integration/utils/pages-constants.js
  test/cypress/cypress/support/index.js
Labels: automation, automated-testcase, backport 4.4-7.16, backport 4.4-2.3-wzd

#4505 Add header and footer report customization
  CHANGELOG.md
  common/constants.ts
  common/plugin-settings.test.ts
  common/services/settings-validator.ts
  public/components/common/form/__snapshots__/index.test.tsx.snap
  public/components/common/form/index.test.tsx
  public/components/common/form/index.tsx
  public/components/common/form/input_text_area.tsx
  public/components/settings/configuration/components/categories/components/category/category.tsx
  public/components/settings/configuration/configuration.tsx
  server/controllers/wazuh-reporting.ts
  server/lib/reporting/printer.ts
  server/routes/wazuh-reporting.test.ts
  server/routes/wazuh-utils/wazuh-utils.test.ts
Labels: enhancement, backport 4.4-7.16, backport 4.4-2.3-wzd
