Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-01, with the labels that each got.

#3748 Dashboards PDF report error when switching pinned agent
  CHANGELOG.md
  public/components/common/modules/buttons/generate_report.tsx
Labels: bug, 4.3

#3772 [FIX] [API Console] Styles of action buttons overlaying the request text
  CHANGELOG.md
  public/templates/tools/tools.html
Labels: enhancement

#3783 [FIX] [HEALTH CHECK] Run `template` and `fields` checks depends on the app configuration
  CHANGELOG.md
  public/components/health-check/services/check-index-pattern/check-index-pattern.service.ts
  public/utils/config-equivalences.js
  server/lib/initial-wazuh-config.ts
Labels: bug, 4.3

#3790 [FIX] [Modules] [Panel] Update aggregation data when the time filter is changed
  CHANGELOG.md
  public/components/common/hooks/use-es-search.ts
Labels: bug, 4.3

#3753 [FIX] Component rendering of command to deploy new Windows agent
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: bug, 4.3

#3792 Enhance agent deployment UI
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.scss
  public/controllers/agent/components/register-agent.js
  public/styles/dark_theme/wz_theme_dark.scss
Labels: enhancement, 4.3

#3795 Changed user for sample data management
  CHANGELOG.md
  public/components/add-modules-data/sample-data.tsx
  server/controllers/wazuh-elastic.ts
Labels: 4.3

#3787 Github/Office365 multi-select filters fix to get suggested values
  CHANGELOG.md
  public/components/common/hooks/use-value-suggestion.ts
  public/react-services/saved-objects.js
Labels: bug, 4.3

#3776 Fix add single agent to group
  CHANGELOG.md
  public/components/management/groups/multiple-agent-selector.tsx
Labels: 4.3

#3777 [FIX] [Modules] Avoid the implicit filters can be removables
  CHANGELOG.md
  public/components/common/modules/modules-helper.js
Labels: bug, 4.3

#3778 Fixed Office365/Github module the side panel tab
  CHANGELOG.md
  public/components/common/modules/panel/components/module-side-panel.tsx
Labels: 4.3

#3780 [FIX] [MODULES] [MITRE ATT&CK] [Intelligence] Wrap text in the `Description` column for the resources info table
  CHANGELOG.md
  public/components/overview/mitre_attack_intelligence/resources.tsx
Labels: bug, 4.3

#3781 Fixed visualization echTooltip position
  CHANGELOG.md
  public/styles/7.9.0/index.dark.scss
  public/styles/7.9.0/index.light.scss
Labels: bug, 4.3

#3796 Fixed the styles on the evolution card
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  public/styles/common.scss
Labels: 4.3

#3806 [FEAT]: Add new options of auth for the Registration service configuration
  CHANGELOG.md
  public/controllers/management/components/management/configuration/registration-service/registration-service.js
  public/controllers/management/components/management/configuration/util-components/configuration-settings-group.js
Labels: enhancement

#3804 [FIX] [GROUPS] Fixes creating a new group with invalid name and no display the remove button in the agents table for the `default` group
  CHANGELOG.md
  public/controllers/management/components/management/groups/actions-buttons-main.js
  public/controllers/management/components/management/groups/group-agents-table.js
Labels: enhancement
