Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2022-04, with the labels that each got.

#3937 Fixed async problem when checking for unknown fields
  CHANGELOG.md
  public/components/common/modules/events.tsx
  public/components/visualize/wz-visualize.js
Labels: 4.3

#3942 Map visualization render problem
  CHANGELOG.md
  public/kibana-integrations/kibana-vis.js
Labels: 4.3

#3877 [BUG][Tools/Api Console] Parse error when using character on the line start
  CHANGELOG.md
  public/controllers/dev-tools/dev-tools.ts
Labels: bug

#3949 Change google group icon
  CHANGELOG.md
  public/assets/images/icons/google_groups.svg
  public/assets/images/icons/icon_google_groups.svg
  public/controllers/settings/settings.js
  public/templates/settings/settings-about.html
  public/templates/settings/settings.html
  public/utils/add_help_menu_to_app.tsx
Labels: 4.3

#3945 GitHub configuration panel text overflow
  CHANGELOG.md
  public/components/common/modules/panel/components/module_configuration.scss
  public/components/common/modules/panel/components/module_configuration.tsx
Labels: 4.3

#3857 Disable `Agents` and `Configuration checksum` sorting
  CHANGELOG.md
  public/controllers/management/components/management/groups/utils/columns-main.js
Labels: 4.3

#3944 [FIX][Modules][Events] Fixed cell enhancement when the value is a sub technique
  CHANGELOG.md
  public/components/common/modules/events-enhance-discover-fields.ts
Labels: bug

#3881 [BUG][Reports] Generate reports not manage the Wazuh API token expiration
  CHANGELOG.md
  public/react-services/reporting.js
  server/controllers/wazuh-reporting.ts
  server/routes/wazuh-reporting.ts
Labels: bug

#3947 Details flyout date picker
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
Labels: 4.3

#3952 Changed office365 config description
  CHANGELOG.md
  public/components/overview/office-panel/views/office-stats.tsx
  public/controllers/management/components/management/configuration/office365/components/general-tab/general-tab.tsx
Labels: 4.3

#3957 Change logout path
  CHANGELOG.md
  public/app.js
  public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
Labels: 4.3

#3991 [Fix] Unhandled promise error when Wazuh API
  CHANGELOG.md
  server/start/cron-scheduler/scheduler-job.ts
Labels: 4.3

#4102 The selected text is visible in API Console
  CHANGELOG.md
  public/utils/codemirror/codemirror.scss
Labels: 4.3

#4101 Changed breadcrumb agent push
  CHANGELOG.md
  public/components/common/globalBreadcrumb/globalBreadcrumb.tsx
  public/components/common/modules/agents-current-section.tsx
  public/components/common/modules/main-overview.tsx
Labels: 4.3

#4055 [Jobs] Change the `shards` configuration for the `statistics` indices
  CHANGELOG.md
  common/constants.ts
  public/services/resolves/get-config.js
  server/lib/initial-wazuh-config.ts
  server/start/cron-scheduler/save-document.ts
  server/start/monitoring/index.ts
Labels: enhancement, 4.3

#4066 Modules-> Mitre-> Widget: Rows per page
  CHANGELOG.md
  public/components/overview/mitre_attack_intelligence/resource.tsx
Labels: enhancement, 4.3

#4063 OS selection in agent installation
  public/controllers/agent/components/register-agent.js
Labels: enhancement, 4.3

#4115 Fix error when selecting date range in discover
  CHANGELOG.md
  public/components/common/modules/discover/discover.tsx
Labels: 4.3

#4079 Fix routes resolvers circular redirections - infinite loop
  CHANGELOG.md
  public/components/health-check/services/check-api.service.ts
  public/react-services/generic-request.js
  public/services/resolves/api-count.js
  public/services/resolves/index.js
  public/services/resolves/settings-wizard.js
  public/services/routes.js
Labels: 4.3

#3894 Fixed refreshing agents evolution visualization
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  public/kibana-integrations/kibana-vis.js
  public/styles/common.scss
Labels: 4.3

#4119 Fixed "See full error" on error toast
  CHANGELOG.md
  public/react-services/wz-request.ts
Labels: bug

#4126 management -> groups -> agent: selectors appear when there are more t…
  CHANGELOG.md
  public/controllers/agent/components/export-configuration.js
Labels: 4.3

#4125 Fixed searchbar suggest handler undefined input ref
  CHANGELOG.md
  public/components/wz-search-bar/lib/suggest-handler.ts
  public/components/wz-search-bar/wz-search-bar.tsx
Labels: 4.3
