Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-02, with the labels that each got.

#5200 Fix a crash in the vulnerability details flyout
  CHANGELOG.md
  public/components/agents/vuls/inventory/detail.tsx
  public/components/agents/vuls/inventory/table.tsx
Labels: backport 4.4-7.16, backport 4.4-7.10

#5135 Fix cannot read null properties bug in settings section
  CHANGELOG.md
  public/components/common/hooks/use-kbn-loading-indicator.ts
Labels: 4.5, backport 4.5-7.16, backport 4.5

#5201 Change RexExp
  CHANGELOG.md
  public/react-services/wz-user-permissions.ts
Labels: backport 4.5-7.10, backport 4.5-7.16

#5197 Add `rel="noopener noreferrer"` in documentation links
  CHANGELOG.md
  public/components/agents/syscollector/inventory.tsx
  public/components/common/modules/discover/row-details.tsx
  public/components/common/welcome/agents-welcome.js
  public/controllers/agent/components/register-agent.js
  public/controllers/management/components/management/configuration/configuration-no-agent.js
  public/controllers/management/components/management/ruleset/views/rule-info.tsx
  public/utils/check-plugin-version.tsx
Labels: backport 4.5-7.10, backport 4.5-7.16
