Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-01, with the labels that each got.

#5060 Implement new versioning methodology
  Makefile
  package.json
  public/package.test.ts
  scripts/tag.py
Labels: backport 4.4-7.16, backport 4.4-7.10

#5062 Update dependencies
  CHANGELOG.md
  package.json
  test/cypress/package-lock.json
  test/cypress/package.json
Labels: backport 4.4-7.16, backport 4.4-7.10

#5031 Fix filtering of `not applicable` SCA checks using `result` filter
  CHANGELOG.md
  common/api-info/endpoints.json
  common/api-info/security-actions.json
  common/constants.ts
  public/components/agents/sca/inventory.tsx
  public/components/agents/sca/inventory/checks-table.tsx
  public/components/common/welcome/components/sca_scan/sca_scan.tsx
Labels: backport 4.4-7.16, backport 4.4-7.10

#5046 Fix errors on closing flyouts in Firefox
  CHANGELOG.md
  public/components/common/flyouts/wz-flyout.tsx
Labels: bug

#5094 Fix error when clicking on the multiple agent selector
  CHANGELOG.md
  public/components/management/groups/multiple-agent-selector.tsx
Labels: backport 4.4-7.16, backport 4.4-7.10

#4936 Fix changelog
  CHANGELOG.md
Labels: backport 4.5-7.16, backport 4.5

#5107 Fix mispeliing in NIST module
  CHANGELOG.md
  public/components/visualize/visualizations.js
  server/integration-files/visualizations/overview/overview-nist.ts
Labels: backport 4.4-7.16, backport 4.4-7.10

#5098 Fix password input in deploy new agent section
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd

#5055 Add mocked API responses for Imposter
  docker/imposter/agents/agents.json
  docker/imposter/cluster/cluster-logs.js
  docker/imposter/cluster/cluster_logs.json
  docker/imposter/cluster/cluster_no_logs.json
  docker/imposter/cluster/cluster_status.json
  docker/imposter/sca/policy-checks.js
  docker/imposter/sca/policy_checks.json
  docker/imposter/sca/policy_checks_failed.json
  docker/imposter/sca/policy_checks_not_applicable.json
  docker/imposter/sca/policy_checks_passed.json
  docker/imposter/vulnerability/default_last_scan.json
  docker/imposter/vulnerability/last_scan.json
  docker/imposter/wazuh-config.yml
Labels: backport 4.4-7.16, backport 4.4-7.10

#5150 Serialize cronjob doc and remove type property
  CHANGELOG.md
  server/start/cron-scheduler/save-document.ts
Labels: backport 4.4-7.16, backport 4.4-7.10

#5131 Fix Alerts Summary table truncated results
  CHANGELOG.md
  server/controllers/wazuh-reporting.ts
  server/lib/reporting/audit-request.ts
  server/lib/reporting/base-query.ts
  server/lib/reporting/extended-information.ts
  server/lib/reporting/gdpr-request.ts
  server/lib/reporting/overview-request.ts
  server/lib/reporting/pci-request.ts
  server/lib/reporting/rootcheck-request.ts
  server/lib/reporting/summary-table.ts
  server/lib/reporting/syscheck-request.ts
  server/lib/reporting/tsc-request.ts
  server/lib/reporting/vulnerability-request.ts
Labels: backport 4.4-7.16, backport 4.4-7.10

#5166 Added server address and wazuh protocol definition in Deploy agent section
  CHANGELOG.md
  public/controllers/agent/components/register-agent-service.ts
  public/controllers/agent/components/register-agent.js
  public/controllers/agent/register-agent/steps/wz-manager-address.tsx
Labels: backport 4.4-7.16, backport 4.4-2.4-wzd

#5177 Agents table action buttons style fix
  CHANGELOG.md
  public/styles/common.scss
Labels: backport 4.4-7.16, backport 4.4-7.10
