Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-04, with the labels that each got.

#4163 Added new global error treatment (client-side)
  CHANGELOG.md
  public/components/agents/fim/inventory/fileDetail.tsx
  public/components/agents/sca/inventory.tsx
  public/components/health-check/services/check-api.service.test.ts
  public/components/health-check/services/check-api.service.ts
  public/controllers/management/components/management/configuration/alerts/alerts-configurations.test.tsx
  public/controllers/management/components/management/configuration/office365/office365.test.tsx
  public/controllers/settings/settings.test.ts
  public/react-services/error-handler.ts
  public/react-services/error-management/docs/README.md
  public/react-services/error-management/docs/examples/README.md
  public/react-services/error-management/docs/examples/error-handler-class-example.test.tsx
  public/react-services/error-management/docs/examples/images/error-handler-examples-unit-tests.jpg
  public/react-services/error-management/docs/examples/images/log-error.png
  public/react-services/error-management/docs/examples/images/toast-error-details.png
  public/react-services/error-management/docs/examples/images/toast-error.png
  public/react-services/error-management/error-factory/error-factory.test.ts
  public/react-services/error-management/error-factory/error-factory.ts
  public/react-services/error-management/error-factory/errors/HttpError.ts
  public/react-services/error-management/error-factory/errors/IndexerApiError.ts
  public/react-services/error-management/error-factory/errors/WazuhApiError.ts
  public/react-services/error-management/error-factory/errors/WazuhError.ts
  public/react-services/error-management/error-factory/errors/WazuhReportingError.ts
  public/react-services/error-management/error-factory/errors/index.ts
  public/react-services/error-management/error-factory/index.ts
  public/react-services/error-management/error-handler/decorator/error-handler-decorator.test.tsx
  public/react-services/error-management/error-handler/decorator/error-handler-decorator.ts
  public/react-services/error-management/error-handler/error-handler.test.ts
  public/react-services/error-management/error-handler/error-handler.ts
  public/react-services/error-management/error-handler/hoc/withErrorHandler.test.tsx
  public/react-services/error-management/error-handler/hoc/withErrorHandler.tsx
  public/react-services/error-management/error-handler/hooks/useErrorHandler.test.tsx
  public/react-services/error-management/error-handler/hooks/useErrorHandler.ts
  public/react-services/error-management/error-handler/index.ts
  public/react-services/error-management/index.ts
  public/react-services/error-management/types.ts
  public/react-services/error-orchestrator/error-orchestrator-ui.test.ts
  public/react-services/error-orchestrator/error-orchestrator-ui.ts
  public/react-services/generic-request.js
  public/react-services/generic-request.test.ts
  public/react-services/saved-objects.js
  public/react-services/saved-objects.test.ts
  public/react-services/wz-api-check.js
  public/react-services/wz-api-check.test.ts
  public/react-services/wz-request.ts
  public/services/request-handler.js
  server/lib/error-response.ts
Labels: type/enhancement, level/task

#5406 Bump Wazuh and platform versions for v4.4.2
  CHANGELOG.md
  README.md
  opensearch_dashboards.json
  package.json
  scripts/tag.py
Labels: backport 4.4-7.16, backport 4.4-7.10

#5409 Fix Most active agent button in the Agents section
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
Labels: backport 4.5-7.10, backport 4.5-7.16
