Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-05, with the labels that each got.

#5419 Changed the title and added a description to step 3 of the deploy a new agent section
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5424 Removed logic related to deprecated endpoint GET /api/agents-unique/{api}
  public/controllers/management/components/management/configuration/utils/wz-fetch.js
  public/react-services/error-handler.ts
  public/services/error-handler.js
  test/server/wazuh-api.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5429 Changed step 3 in the "Deploy a new agent" section.
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5470 Fix macos apple install command
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5481 Change macOS register agent installation script
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5451 Remove deprecated code
  CHANGELOG.md
  public/components/common/welcome/agents-welcome.js
  public/controllers/agent/agents.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5465 Fix repeated request in groups-table
  CHANGELOG.md
  public/controllers/management/components/management/groups/groups-table.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5453 Remove unnecessary dashboard queries
  CHANGELOG.md
  public/controllers/agent/agents-preview.js
  public/controllers/overview/overview.js
  public/templates/visualize/dashboards.html
Labels: backport 4.5-7.10, backport 4.5-7.16

#5476 Change the search bar to the one that does not make the request on rendering
  CHANGELOG.md
  public/components/wz-field-search-bar/wz-field-search-bar.tsx
  public/controllers/management/components/management/mg-logs/logs.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5416 Changed step 3 in the "Deploy a new agent" section.
  .gitignore
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5500 Remove repeated and unnecessary requests in security section
  CHANGELOG.md
  public/components/security/main.tsx
  public/components/security/policies/create-policy.tsx
  public/components/security/policies/policies.tsx
Labels: backport 4.5-7.10, backport 4.5-7.16

#5403 Update installation guide in README.md
  README.md
Labels: backport 4.5-7.10
