Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-07, with the labels that each got.

#5633 Add kbn-dev 7.17.11
  docker/images/kbn-7.17.11-dev.Dockerfile
  docker/kbn-dev/dev.sh
Labels: backport 4.5.1-7.10

#5639 Bump Wazuh and platform versions for v4.4.5
  CHANGELOG.md
  README.md
  opensearch_dashboards.json
  package.json
  scripts/tag.py
Labels: backport 4.4.5-7.10, backport 4.4.5-7.16

#5645 Prepare tag.py for v4.4.5-rc1
  scripts/tag.py
Labels: backport 4.4.5-7.10, backport 4.4.5-7.16

#5655 Update unit-test.yml
  .github/workflows/unit-test.yml
Labels: backport 4.4.5-7.10, backport 4.4.5-7.16

#5659 Add support for Wazuh 4.4.5-rc2
  scripts/tag.py
Labels: backport 4.4.5-7.10, backport 4.4.5-7.16

#5592 Remove unused embedded jquery-ui
  .eslintrc.json
  CHANGELOG.md
  plugins/main/public/app.js
  plugins/main/public/utils/jquery-ui.js
Labels: backport 4.6.0-7.10, backport 4.6.0-7.16

#5685 Fixes redirection problem to inventory data, stats and configuration in an agent
  plugins/main/public/components/common/welcome/agents-welcome.js
Labels: backport 4.7.0, backport master

#5692 Fix 4.6.0 changelog merge errors
  CHANGELOG.md
Labels: backport 4.6.0-7.10, backport 4.6.0-7.16

#5677 Update release utilities
  Makefile
  RELEASING.md
  package.json
  public/package.test.ts
  scripts/release/bump.js
  scripts/release/lib/logger.js
  scripts/release/lib/read-manifest-package.js
  scripts/release/lib/update-manifest-package.js
  scripts/release/lib/update-manifest-plugin.js
  scripts/release/tag.js
  scripts/tag.py
Labels: backport 4.5.0-7.10, backport 4.5.0-7.16

#5687 Fix API request to get the manager labels and broken documentation link
  CHANGELOG.md
  docker/imposter/agents/configuration.js
  docker/imposter/agents/configuration/agent_labels.json
  docker/imposter/agents/configuration/default.json
  docker/imposter/cluster/configuration/agent_labels.json
  docker/imposter/manager/configuration.js
  docker/imposter/manager/configuration/agent_labels.json
  docker/imposter/manager/configuration/default.json
  docker/imposter/manager/configuration/monitor_reports.json
  docker/imposter/wazuh-config.yml
  public/controllers/management/components/management/configuration/alerts/alerts-labels.js
  public/controllers/management/components/management/configuration/alerts/alerts.js
Labels: backport 4.5.1-7.10, backport 4.5.1-7.16
