Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-03, with the labels that each got.

#4828 Remove trailing `-` character for OS value in the list of agents
  CHANGELOG.md
  public/controllers/agent/components/agents-table.js
Labels: backport 4.5-7.16, backport 4.5

#5234 Fix possessive 'it's' in the Vulnerability dashboard
  public/components/agents/vuls/main.tsx
Labels: 4.5

#5274 Add noopener noreferrer to externals links
  CHANGELOG.md
  public/components/add-modules-data/module-guide.js
  public/components/agents/fim/inventory.tsx
  public/components/common/util/markdown/markdown.test.tsx
  public/components/common/util/markdown/markdown.tsx
  public/components/health-check/container/health-check.container.tsx
  public/components/management/cluster/cluster-disabled.js
  public/components/security/roles-mapping/components/rule-editor.tsx
  public/components/settings/configuration/components/categories/components/category/category.tsx
  public/components/settings/configuration/components/header.tsx
  public/components/wz-blank-screen/wz-blank-screen.js
  public/controllers/agent/components/register-agent.js
  public/controllers/management/components/management/configuration/util-components/help-button-popover.js
  public/kibana-integrations/discover/application/angular/directives/no_results.js
  public/react-services/saved-objects.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5285 Fixed Deploy Agent wrong use of connection secure property
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5291 Header in agent view is rendered correctly
  CHANGELOG.md
  public/components/common/modules/module.scss
  public/components/common/welcome/agents-welcome.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5295 Fixed deploy new agent refactor secure connection conditions
  CHANGELOG.md
  public/controllers/agent/components/register-agent-service.ts
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5299 Add agent never connected to the imposter
  docker/imposter/agents/agent_active_groups.json
  docker/imposter/agents/agent_disconnected.json
  docker/imposter/agents/agent_macos.json
  docker/imposter/agents/agent_never_connected.json
  docker/imposter/agents/agent_pending.json
  docker/imposter/agents/agents.js
  docker/imposter/agents/agents.json
Labels: backport 4.5-7.10, backport 4.5-7.16

#5305 Add dockerized yarn runner
  docker/runner/docker-compose.yml
  package.json
  scripts/manifest.js
  scripts/runner.js
Labels: type/enhancement, automation, backport 4.5-7.10, backport 4.5-7.16

#5311 Fix pre-release environments for kibana 7.10.2
  docker/wazuh-4.3-es/pre.sh
  docker/wazuh-4.3-es/pre.yml
  docker/wazuh-4.3-es/rel.sh
  docker/wazuh-4.3-es/rel.yml
Labels: backport 4.5-7.16, backport 4.5

#5326 Prepare 4.4.0 release
  CHANGELOG.md
  package.json
  scripts/tag.py
Labels: backport 4.4-7.16, backport 4.4-7.10

#5313 Add different responses to endpoints
  docker/imposter/agents/agents-configuration.js
  docker/imposter/agents/configuration/agent-buffer.json
  docker/imposter/agents/configuration/agent-client.json
  docker/imposter/agents/configuration/agent-labels.json
  docker/imposter/agents/configuration/auth-auth.json
  docker/imposter/agents/configuration/com-active-response.json
  docker/imposter/agents/configuration/logcollector-localfile.json
  docker/imposter/agents/configuration/logcollector-socket.json
  docker/imposter/agents/configuration/request-remote.json
  docker/imposter/agents/configuration/syscheck-rootcheck.json
  docker/imposter/agents/configuration/syscheck-syscheck.json
  docker/imposter/agents/configuration/wmodules-wmodules.json
  docker/imposter/wazuh-config.yml
Labels: backport 4.5-7.10, backport 4.5-7.16

#5329 Change link to Malware detection documentation
  CHANGELOG.md
  public/controllers/management/components/management/configuration/policy-monitoring/help-links.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5196 Fix the search in the agent inventory data tables
  CHANGELOG.md
  public/components/agents/syscollector/components/syscollector-table.tsx
Labels: backport 4.4-7.16, backport 4.4-7.10

#5347 Bump Wazuh and platform versions for v4.4.1
  README.md
  common/api-info/security-actions.json
  scripts/tag.py
Labels: backport 4.4-7.16, backport 4.4-7.10
