Repository wazuh/wazuh-dashboard-plugins, pull requests merged in 2023-06, with the labels that each got.

#5521 Fix error of request body parameter suggestions in API Console
  CHANGELOG.md
  public/controllers/dev-tools/dev-tools.ts
Labels: backport 4.5-7.10, backport 4.5-7.16

#5528 Wazuh api usage magement/status
  CHANGELOG.md
  docker/imposter/overview/agents.json
  docker/imposter/wazuh-config.yml
  public/controllers/management/components/management/status/actions-buttons-main.js
  public/controllers/management/components/management/status/status-overview.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5544 Improved changelog
  CHANGELOG.md
  scripts/tag.py
Labels: backport 4.4-7.16, backport 4.4-7.10

#5485 Remove deprecated code and request in Management
  CHANGELOG.md
  public/controllers/management/components/management/cdblists/components/cdblists-table.tsx
  public/controllers/management/components/management/cdblists/main-cdblists.tsx
  public/controllers/management/components/management/cdblists/views/cdblists-overview.tsx
  public/controllers/management/components/management/common/actions-buttons.tsx
  public/controllers/management/components/management/configuration/configuration-switch.js
  public/controllers/management/components/management/decoders/__snapshots__/main-decoders.test.tsx.snap
  public/controllers/management/components/management/decoders/components/decoders-table.tsx
  public/controllers/management/components/management/decoders/main-decoders.tsx
  public/controllers/management/components/management/decoders/views/decoders-overview.tsx
  public/controllers/management/components/management/groups/__snapshots__/groups-main.test.tsx.snap
  public/controllers/management/components/management/groups/groups-main.test.tsx
  public/controllers/management/components/management/management-main.js
  public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
  public/controllers/management/components/management/ruleset/components/ruleset-table.tsx
  public/controllers/management/components/management/ruleset/main-ruleset.tsx
  public/controllers/management/components/management/ruleset/views/ruleset-overview.tsx
  public/controllers/management/management.js
  public/redux/actions/appStateActions.js
  public/redux/reducers/appStateReducers.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5519 Create CLI to extract API data from specification file
  CHANGELOG.md
  common/api-info/endpoints.json
  package.json
  scripts/generate-api-4.0-info/generate-api-4.0-info.js
  scripts/generate-api-4.0-info/generate-api-4.0-info.sh
  scripts/generate-api-data.js
Labels: backport 4.5-7.10, backport 4.5-7.16

#5469 [Redesign add agent] Add register agent command generator
  public/controllers/register-agent/config/os-commands-definitions.ts
  public/controllers/register-agent/core/register-commands/README.md
  public/controllers/register-agent/core/register-commands/command-generator/command-generator.test.ts
  public/controllers/register-agent/core/register-commands/command-generator/command-generator.ts
  public/controllers/register-agent/core/register-commands/exceptions/index.ts
  public/controllers/register-agent/core/register-commands/optional-parameters-manager/optional-parameters-manager.test.ts
  public/controllers/register-agent/core/register-commands/optional-parameters-manager/optional-parameters-manager.ts
  public/controllers/register-agent/core/register-commands/services/get-install-command.service.test.ts
  public/controllers/register-agent/core/register-commands/services/get-install-command.service.ts
  public/controllers/register-agent/core/register-commands/services/search-os-definitions.service.test.ts
  public/controllers/register-agent/core/register-commands/services/search-os-definitions.service.ts
  public/controllers/register-agent/core/register-commands/types.ts
  public/controllers/register-agent/hooks/README.md
  public/controllers/register-agent/hooks/use-register-agent-commands.test.ts
  public/controllers/register-agent/hooks/use-register-agent-commands.ts
Labels: backport 4.5-7.10, backport 4.5-7.16

#5538 Change windows agent service name
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5497 Remove agent name in agent info ribbon
  CHANGELOG.md
  public/components/common/welcome/agents-welcome.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5471 Fix IPV6 visualizations
  CHANGELOG.md
  docker/imposter/agents/agent.json
  docker/imposter/agents/agents.json
  docker/imposter/agents/group.json
  docker/imposter/cluster/cluster_node_info.json
  docker/imposter/syscollector/netaddr.js
  docker/imposter/syscollector/ports.js
  docker/imposter/wazuh-config.yml
  public/components/agents/syscollector/components/syscollector-table.tsx
  public/components/common/welcome/agents-info.js
  public/components/management/cluster/node-list.tsx
  public/controllers/agent/components/agents-table.js
  public/controllers/management/components/management/configuration/client/client.js
  public/controllers/management/components/management/configuration/global-configuration/global-configuration-remote.js
  public/controllers/management/components/management/groups/group-agents-table.js
Labels: backport 4.4-7.16, backport 4.4-7.10

#5478 Add Apple Silicon architecture to the register Agent wizard
  CHANGELOG.md
  public/controllers/agent/components/register-agent.js
  public/controllers/agent/wazuh-config/index.ts
Labels: backport 4.4-7.16, backport 4.4-7.10

#5584 Add missing supported versions to the Docker environments
  docker/kbn-dev/dev.sh
  docker/osd-dev/dev.sh
  docker/wazuh-4.4-wz/pre.sh
  docker/wazuh-4.4-wz/rel.sh
  docker/wazuh-4.x-es/pre.sh
  docker/wazuh-4.x-es/rel.sh
Labels: backport 4.4-7.16, backport 4.4-7.10

#5539 Change the method to make the redirect
  CHANGELOG.md
  public/controllers/agent/components/agents-preview.js
  public/controllers/agent/components/agents-table.js
Labels: backport 4.5.1-7.10, backport 4.5.1-7.16

#5490 Fix agents active coverage stat as NaN
  CHANGELOG.md
  public/controllers/agent/agents-preview.js
  public/controllers/agent/components/agents-preview.js
Labels: backport 4.5.1-7.10, backport 4.5.1-7.16

#5601 Update test snapshots for 4.5
  .github/workflows/eslint.yml
  .github/workflows/unit-test.yml
  common/api-info/endpoints.json
  common/services/web_documentation.test.ts
  docker/kbn-dev/dev.sh
  docker/osd-dev/dev.sh
  docker/wazuh-4.4-wz/pre.sh
  docker/wazuh-4.4-wz/rel.sh
  docker/wazuh-4.x-es/pre.sh
  docker/wazuh-4.x-es/rel.sh
  public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
  public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
Labels: backport 4.5.1-7.10, backport 4.5.1-7.16, backport 4.5.1, backport 4.5.0-7.10, backport 4.5.0-7.16

#5551 Add specific RBAC permissions to Security section
  CHANGELOG.md
  docker/imposter/security/security-actions.json
  docker/imposter/security/security-me-policies.js
  docker/imposter/security/security-policies.json
  docker/imposter/security/security-roles.json
  docker/imposter/security/security-rules.json
  docker/imposter/security/users.json
  docker/imposter/wazuh-config.yml
  plugins/main/common/constants.ts
  plugins/main/public/components/security/main.tsx
  plugins/main/public/components/security/policies/create-policy.tsx
  plugins/main/public/components/security/policies/edit-policy.tsx
  plugins/main/public/components/security/policies/policies-table.tsx
  plugins/main/public/components/security/policies/policies.tsx
  plugins/main/public/components/security/roles-mapping/components/roles-mapping-create.tsx
  plugins/main/public/components/security/roles-mapping/components/roles-mapping-edit.tsx
  plugins/main/public/components/security/roles-mapping/components/roles-mapping-table.tsx
  plugins/main/public/components/security/roles-mapping/components/rule-editor.tsx
  plugins/main/public/components/security/roles-mapping/roles-mapping.tsx
  plugins/main/public/components/security/roles/create-role.tsx
  plugins/main/public/components/security/roles/edit-role-table.tsx
  plugins/main/public/components/security/roles/edit-role.tsx
  plugins/main/public/components/security/roles/roles-table.tsx
  plugins/main/public/components/security/roles/roles.tsx
  plugins/main/public/components/security/users/components/create-user.tsx
  plugins/main/public/components/security/users/components/edit-user.tsx
  plugins/main/public/components/security/users/components/users-table.tsx
  plugins/main/public/components/security/users/users.tsx
Labels: backport 4.6.0-7.10, backport 4.6.0-7.16
